- src/Asset.js
> ✏️ Fix small typo

- src/Bundler.js
Fixes #21. normalizeOptions can now support publicUrl and publicURL.
> Fix issue with normalizeOptions and publicUrl

- package.json
- src/FSCache.js
- src/utils/config.js
- test/hmr.js
- yarn.lock
Replaced `JSON.parse` with `parseJson` other than on Line - https://github.com/parcel-bundler/parcel/blob/master/src/builtins/hmr-runtime.js#L20 , I think we create event so I think this should be ok. Thoughts?
Fixes: https://github.com/parcel-bundler/parcel/issues/82
> using parse-json for more helpful messages

- README.md
Add slack badge, slack/twitter links
Closes #103.
> Add Community section to README.md

- src/Bundler.js
- src/Logger.js
> Print stack traces on error

- src/Parser.js
> jsm support

- src/Bundler.js
> Exit on build error when running parcel build

- package.json
- src/utils/config.js
- yarn.lock
Strips comments from Json as requested here: closes #168
> Strip json comments

- .gitignore
- package.json
- src/Parser.js
- src/assets/CoffeeScriptAsset.js
- test/integration/coffee/index.js
- test/integration/coffee/local.coffee
- test/javascript.js
Poor test coverage, but other than that I modeled this after #84. Seems to work great.
> Initial CoffeeScript support

- src/packagers/HTMLPackager.js
> Minor typo

- src/assets/GlobAsset.js
https://github.com/webpack/webpack/pull/1227#issuecomment-120780108
> Normalize filenames to nfc for hfs+

- src/assets/JSAsset.js
- src/visitors/dependencies.js
- test/integration/workers/index.js
- test/integration/workers/service-worker.js
- test/integration/workers/worker.js
- test/javascript.js
> web worker support

- src/Bundler.js
- test/bundler.js
- test/integration/bundler-middleware/index.js
- test/integration/bundler-middleware/local.js
> Make bundler middleware usage intuitive

- README.md
Quick fix for input file type sentence.
> Fix small sentence in README.md

- src/utils/urlJoin.js
- test/url-join.js
#409  
#405 
> and should we use the absolute path instead of relative path ?
if we do, i can make a pr next
> fix: when the publicUrl is url not a path of os

- .travis.yml
- README.md
- appveyor.yml
- package.json
- yarn.lock
- Made a script for test + coverage and reporting the coverage to codecov.io
- Linked the forked repo with codecov.io and the results can be found [here](https://codecov.io/gh/ksashikumar/parcel)
- Checked [travis](https://travis-ci.org/ksashikumar/parcel/builds/326943870) build against a test PR in my forked repo: https://github.com/ksashikumar/parcel/pull/1
> Code coverage and integrate codecov.io

- src/WorkerFarm.js
While the workers are starting up, we already process assets on the main thread. But it turns out that even after the workers have started, it takes a bit of time for them to warm up. The JS engine needs to do JIT things, optimize the code of some giant libraries like babel, etc.
We now send assets to both the worker and main process simultaneously in order to warm up the workers, and then transition to the workers only once they are warmed up. This seems to cause a pretty big improvement in perf for small apps, while large apps remain pretty much the same.
**Small app (`import 'react'`):**
Without patch (with workers): 752ms
Without workers: 357ms
With patch: 487ms
**Large app:**
Without patch (with workers): 6.76s
Without workers: 15.53s
With patch: 6.77s
cc. @DeMoorJasper @brandon93s …
> Warm up worker processes before switching to them

- src/utils/urlJoin.js
- test/url-join.js
> Fixes bug where double slashes isn't parsed as host.

- appveyor.yml
- test/rust.js
> Fix rust wasm-gc test

- src/Bundler.js
- src/HMRServer.js
- src/builtins/hmr-runtime.js
> 🐛 launch https websocket server if --https

- README.md
I was going to make a feature request, then happily discovered that this feature already exists - but was undocumented. Until now. 🍻
> Added -o option to readme

- src/builtins/hmr-runtime.js
Removed call to window.location to fix #846
> remove call to window.location (fix #846)

- src/builtins/hmr-runtime.js
> Fix HMR runtime error call stack message

- test/hmr.js
Hey,
CI has been a bit flaky lately and I would like to help make it pass consistently.
This PR fixes some flakiness in HMR tests. The flakiness happened because some tests have finished while the bundler was still doing some work. That caused the next test to start running while the previous one could have been working on the same files.
> Fix flakiness of HMR tests

- src/transforms/posthtml.js
- yarn.lock
> Only do safe cssnano transforms inside htmlnano

- src/assets/HTMLAsset.js
- test/html.js
- test/integration/html-object/file.svg
- test/integration/html-object/index.html
> Add support for resolving links in object element's data attribute

- src/Bundler.js
Fixes #1112 
I was reading up on #918 and #919, which may necessitate a change to include more patterns. Maybe wait on merging this until that is decided upon?
> Add support for scoped plugin packages (#1112)

- package.json
- yarn.lock
Prevents issues with the `<component>` tags in vue files
> Bump dependencies (#1089)

- .github/ISSUE_TEMPLATE/Bug_Report.md
- .github/ISSUE_TEMPLATE/Feature_Request.md
- .github/ISSUE_TEMPLATE/Question.md
- .github/ISSUE_TEMPLATE/RFC.md
Splits up the current issue_template into 4 issue templates, will probably improve overview of newly created issues
* Bug Report
* Feature Request
* Question
* RFC
> Issue templates

- src/cli.js
This will enable wss in hmr
Fixes https://github.com/parcel-bundler/parcel/issues/1282
> Allow --https for watch

- src/assets/PugAsset.js
> Use config.locals to render pug template

- src/assets/SASSAsset.js
Please reference to #1211 for further information
Closes #1211
> Fix indented syntax type for single file vue components

- test/integration/vue-preprocessors/pre-processors.vue
One of the vue tests was failing since now we properly seperate scss and sass.
And the tests file was incorrectly stating scss as sass.
This PR fixes the test file
> Fix failing vue test

- test/lineCounter.js
Follow-up on previous PR to use async fs on the linecounter tests
> Use async fs on new linecounter tests

- .prettierignore
It prevented committing when tests failed
> Add `test/dist` to .prettierignore

- package.json
- yarn.lock
> Upgrade to cssnano@4

- src/Bundler.js
> Fix 'buildStart' event is not firing

- src/packagers/JSConcatPackager.js
- src/packagers/JSPackager.js
- src/utils/getExisting.js
> Load minified version if available

- src/SourceMap.js
> Fix mappings no longer having names

- yarn.lock
Remove artifactory from yarn.lock
> Remove corporate npm proxy from yarn.lock

- src/builtins/prelude.js
- test/integration/node_require_cache/main.js
- test/javascript.js
* Added a simple stub for require.cache in prelude (#1959)
> Added stub for require.cache

- src/Asset.js
> bundle name hash-key generation is not environment independent #2001

- .github/PULL_REQUEST_TEMPLATE/bugfix.md
see following discussions: 
- https://github.com/parcel-bundler/parcel/pull/2010#discussion_r217498532
- https://github.com/parcel-bundler/parcel/pull/2010#discussion_r217456075
- https://github.com/parcel-bundler/parcel/pull/2010#discussion_r217499822
> PR Templates | Fixing minor things

- src/transforms/babel/babelrc.js
This was blocking me from using 1.10.beta0.
> Fix require

- src/utils/env.js
- test/integration/plugins/node_modules/parcel-plugin-test/TextAsset.js
---
name: 🙋 New Pull Request
about: Do you want to change something on parcel?
---
This fixes node 6 tests failing, apparently there was still a babel 6 register in the tests...
> Fix node 6 tests

- src/assets/JSAsset.js
Do not load existing sourcemaps if sourcemaps are disabled
> Don't load existing sourcemaps if sourcemaps are disabled

- .github/PULL_REQUEST_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE/Documentation.md
- .github/PULL_REQUEST_TEMPLATE/bugfix.md
- .github/PULL_REQUEST_TEMPLATE/feature.md
This PR updates the PR templates to be slightly more structured (especially the default one)
Mainly adds a test instructions section
> Slightly improve PR templates

- packages/core/is-v2-ready-yet/src/Footer.js
Corrects url for **is-v2-ready-yet** 
N/A
N/A
> corrects url for is-v2-ready-yet source

- packages/configs/default/index.json
- packages/configs/default/package.json
- packages/core/types/index.js
- packages/examples/simple/src/child.css
- packages/examples/simple/src/index.js
- packages/examples/simple/src/styles.css
- packages/resolvers/default/src/DefaultResolver.js
- packages/transformers/css/.eslintrc.json
- packages/transformers/css/package.json
- packages/transformers/css/src/CSSTransformer.js
- yarn.lock
CSS transformer plugin for Parcel 2.
See #2155 for details.
> Parcel 2: Add CSS transformer

- packages/core/integration-tests/test/pug.js
Fix failing pug test introduced by #2582
> Fix pug test

- packages/core/cache/src/Cache.js
- packages/core/core/src/loadEnv.js
- packages/core/parcel-bundler/src/Bundler.js
- packages/core/utils/getRootDir.js
- packages/core/utils/serializer.js
Extracted from #2802.
Test Plan: lint, flow, test
> Flowify serialize and getRootDir

- CHANGELOG.md
Also fixed release date for 1.12.0 (March instead of Februrary)
> Update changelog for 1.12.1

- packages/core/cache/.eslintrc.json
- packages/core/core/.eslintrc.json
- packages/core/core/test/.eslintrc.json
- packages/core/integration-tests/test/.eslintrc.json
- packages/core/logger/test/.eslintrc.json
- packages/core/plugin/.eslintrc.json
- packages/core/utils/src/.eslintrc.json
- packages/core/watcher/test/.eslintrc.json
- packages/core/workers/src/.eslintrc.json
- packages/core/workers/test/.eslintrc.json
- packages/dev/eslint-config/index.js
- packages/packagers/js/.eslintrc.json
- packages/reporters/cli/.eslintrc
- packages/reporters/cli/package.json
- packages/reporters/cli/test/.eslintrc
- packages/transformers/babel/.eslintrc.json
- packages/transformers/css/.eslintrc.json
- packages/transformers/js/.eslintrc.json
- packages/transformers/terser/.eslintrc.json
Extracted from #2826. Check out that PR for context.
Test Plan: flow, lint, test
> Centralize eslint configuration

- CHANGELOG.md
> Changelog for 1.12.2 and 1.12.3

- packages/core/integration-tests/data/lastTestRun.json
- packages/core/integration-tests/ready-yet-reporter.js
- packages/core/is-v2-ready-yet/src/Footer.js
Update links pointing to `v2-work-so-far` branch
> update v2 branch links

- packages/dev/eslint-plugin/test/rules/no-self-package-imports.test.js
- packages/dev/eslint-plugin/test/utils.test.js
Update eslint-plugin tests to also use src instead of lib
> Parcel 2: Fix eslint-plugin tests

- .gitattributes
- packages/core/parcel-bundler/package.json
- yarn.lock
- Update .gitattributes to make sure binary files in the repo are recognized as such (was having issues with png)
- Don't pin some babel packages to <7.4.0 to prevent a possible future case of incompatibility between resolved versions
> Update deps & gitattributes

- flow-typed/npm/source-map_v0.7.x.js
- packages/core/source-map/src/SourceMap.js
@DeMoorJasper, feel free to merge or do what you want with this.
> Add source-map types from flow-typed and integrate them

- packages/core/core/package.json
> Remove unused dependencies from core package.json

- packages/core/integration-tests/test/integration/scope-hoisting/commonjs/wrap-destructuring-array/a.js
- packages/core/integration-tests/test/integration/scope-hoisting/commonjs/wrap-destructuring-array/b.js
- packages/core/integration-tests/test/integration/scope-hoisting/commonjs/wrap-destructuring-array/package.json
- packages/core/integration-tests/test/integration/scope-hoisting/commonjs/wrap-destructuring-object/a.js
- packages/core/integration-tests/test/integration/scope-hoisting/commonjs/wrap-destructuring-object/b.js
- packages/core/integration-tests/test/integration/scope-hoisting/commonjs/wrap-destructuring-object/package.json
- packages/core/integration-tests/test/scope-hoisting.js
- packages/shared/scope-hoisting/src/concat.js
> Scope hoisting destructuring

- packages/bundlers/default/package.json
- packages/core/cache/package.json
- packages/core/plugin/package.json
- packages/core/register/package.json
- packages/packagers/css/package.json
- packages/packagers/html/package.json
- packages/packagers/js/package.json
- packages/packagers/raw/package.json
- packages/reporters/cli/package.json
- packages/reporters/json/package.json
- packages/runtimes/hmr/package.json
- packages/runtimes/js/package.json
- packages/transformers/babel/package.json
- packages/transformers/css/package.json
- packages/transformers/html/package.json
- packages/transformers/js/package.json
- packages/transformers/postcss/package.json
- packages/transformers/raw/package.json
- packages/transformers/terser/package.json
- packages/utils/events/package.json
This is extracted from work to get Parcel 2 to build with Parcel 2.
Test Plan: flow, lint, test. The effects of these changes are exercised in PRs to follow to build Parcel with Parcel.
> Add missing engines

- packages/configs/default/package.json
> Add missing default config dependency

- packages/configs/default/package.json
- packages/core/core/package.json
- packages/core/core/src/dumpGraphToGraphViz.js
> some miscellaneous fixes

- packages/configs/default/index.json
- packages/configs/default/package.json
- packages/core/integration-tests/test/javascript.js
- packages/transformers/coffeescript/package.json
- packages/transformers/coffeescript/src/CoffeeScriptTransformer.js
Used the v1 transformer to add the v2 transformer.
fixes #2160
> Add V2 CoffeeScript Transformer

- packages/core/integration-tests/test/css.js
- packages/packagers/css/src/CSSPackager.js
Specifically handles the case where the media was prefixed to an import. This will wrap the imported asset in a media block. 
fixes #2524
> Updates V2 CSSPackager to include media 

- .flowconfig
- package.json
- yarn.lock
Updates to the latest flow version
Test Plan: `yarn flow`, `yarn test`
> Update flow to v0.102

- .github/ISSUE_TEMPLATE/Feature_Request.md
Pretty straightforward:
<table>
<tr><td>
<table>
<tr><td>
<table>
<tr><td>
<table>
<tr><td>
<table>
<tr><td>
<table>
<tr><td>
<table>
<tr><td>
<table>
<tr><td>
<table>
<tr><td>
<table>
<tr><td>
<table>
<tr><td>
<table>
<tr><td>
<table>
<tr>
<th>Before
<td><h1>🙋 feature request
<tr>
<th>After
<td><h1>🙋 Feature request
> Use uppercase for the first letter of the issue template

- packages/core/core/src/ConfigLoader.js
- packages/core/core/src/Graph.js
- packages/core/core/src/RequestGraph.js
- packages/core/core/src/Transformation.js
- packages/core/core/src/public/Config.js
- packages/core/core/src/resolveOptions.js
- packages/core/core/src/types.js
- packages/core/core/test/AssetGraphBuilder.test.js
- packages/core/types/index.js
- packages/reporters/cli/test/SimpleCLIReporter.test.js
This PR adds functionality to invalidate transformations when previously used plugins change versions.
> Plugin version invalidation

- packages/core/parcel-bundler/src/cli.js
Fixes #3157
The usage information that shows up with help message was misleading.  
N/A
> cli: fix up misleading usage information

- .flowconfig
- package.json
- yarn.lock
Updated flow config, package.json & lockfile to reflect most recent flow version (v0.102.0 -> 0.103.0).
flow version update from v0.102.0 to 0.103.0
- [✔️] Included links to related issues/PRs
> Flow update

- packages/transformers/coffeescript/package.json
- packages/transformers/coffeescript/src/CoffeeScriptTransformer.js
Adds sourcemaps to v2 coffescript transformer
resolves #2160
> Parcel 2: CoffeeScript sourcemaps

- .flowconfig
- package.json
- yarn.lock
Updates to the latest flow version
> Update flow to v0.104.0

- packages/core/core/src/RequestGraph.js
- packages/core/core/src/Validation.js
> Speedup validations

- packages/configs/default/index.json
- packages/configs/default/package.json
- packages/core/integration-tests/test/sugarss.js
- packages/transformers/sugarss/package.json
- packages/transformers/sugarss/src/SugarssTransformer.js
Resolved #3360 .
Move v1 SSSAsset to v2 SugarssTransformer.
Compiling SugarSS to CSS using PostCSS with parcel v2 api.
> V2: SugarSS transformer

- packages/core/core/src/RequestGraph.js
This appears unused.
Test Plan: flow and test
> Remove RequestGraph#addSubRequest

- packages/core/integration-tests/test/typescript.js
Pass json support tests since it supported on v2 branch https://github.com/parcel-bundler/parcel/pull/3089
> Pass json support tests

- packages/configs/default/index.json
- packages/configs/default/package.json
- packages/core/integration-tests/test/javascript.js
- packages/transformers/yaml/package.json
- packages/transformers/yaml/src/YAMLTransformer.js
> refactor: Add yaml transformer and make test pass

- packages/configs/default/index.json
- packages/configs/default/package.json
- packages/core/integration-tests/test/integration/pug-include-extends/expect.html
- packages/core/integration-tests/test/integration/pug-locals/.pugrc
- packages/core/integration-tests/test/integration/pug-locals/index.pug
- packages/core/integration-tests/test/pug.js
- packages/transformers/pug/package.json
- packages/transformers/pug/src/PugTransformer.js
- yarn.lock
> Add PugTransformer

- packages/core/integration-tests/test/integration/pug-include-extends/absolute/nested.pug
- packages/core/integration-tests/test/integration/pug-include-extends/index.pug
- packages/core/integration-tests/test/pug.js
- packages/core/test-utils/src/utils.js
- packages/transformers/pug/src/PugTransformer.js
Resolves: https://github.com/parcel-bundler/parcel/pull/3462#discussion_r318368505
Resolves #3358
> Add Pug Dependencies Handling

- packages/examples/eslint-example/.eslintrc
- packages/examples/eslint-example/.parcelrc
- packages/examples/eslint-example/package.json
- packages/examples/eslint-example/src/index.js
- packages/validators/eslint/.babelrc
- packages/validators/eslint/package.json
- packages/validators/eslint/src/EslintValidator.js
This PR Implements the ESLint Validator for Parcel 2.
Also includes some minor cleanup to the typescript validator
Closes #3380
See the example project.
> Parcel 2: Eslint validator

- .flowconfig
- package.json
- yarn.lock
No code changes necessary.
Test Plan: `flow`
> Update to Flow 0.107

- packages/core/integration-tests/test/json-reporter.js
- packages/core/integration-tests/test/metrics-reporter.js
- packages/reporters/build-metrics/package.json
- packages/reporters/build-metrics/src/BuildMetricsReporter.js
This reporter creates a `parcel-metrics.json` file in the `cwd` on each succesfull build.
Useful for consumption by other tools that can show these metrics. Currently I wrote it to improve the accuracy and details in the Parcel Benchmark Github Action
Run the integration test.
> Parcel 2: Metrics reporter

- .github/workflows/main.yml
This PR adds a workflow file to trigger the PR Benchmark action, code for this action can be found here: https://github.com/DeMoorJasper/parcel-benchmark-action
The action is still lacking some features and timings aren't really reliable on the Github action infrastructure. However updates to the action will not affect the workflow file in any way.
The action uses the metrics reporter, so please merge that one first (#3596) otherwise the action will always fail...
> Parcel 2: Add Benchmark Action

- .flowconfig
- package.json
- yarn.lock
> Flow upgrade to v0.110.1

- packages/core/codeframe/package.json
- packages/core/codeframe/src/codeframe.js
- packages/core/utils/src/prettyDiagnostic.js
- yarn.lock
This PR improves the diagnostic ansi formatter to have file links that IDE's understand thanks to @mischnic for bringing this up.
Also implement syntax highlighting using `emphasize`/`lowlight` supporting pretty much all languages parcel supports
> Parcel 2: Add code highlighting and fix file:line:column link in codeframe

- packages/transformers/js/src/JSTransformer.js
> Fixup fs inlining

- packages/core/codeframe/src/codeframe.js
- packages/core/codeframe/test/codeframe.test.js
- packages/core/core/src/Transformation.js
- packages/core/diagnostic/src/diagnostic.js
- packages/reporters/cli/src/Log.js
Adds tabs support in codeframes.
Also starts the catching of errors in plugins to append the correct origin
Closes T-185
> [T-185] Codeframe tabs support

- packages/core/types/index.js
- packages/transformers/babel/src/BabelTransformer.js
- packages/transformers/babel/src/babelErrorUtils.js
This PR copies some string manipulation util from parcel 1 to use diagnostics properly instead of the default babel formatting.
> Improve babel errors to use diagnostics properly

- packages/core/utils/src/ansi-html.js
- packages/core/utils/src/escape-html.js
- packages/core/utils/src/index.js
This PR escapes any html in a codeframe before creating the html version.
> [T-228] Escape html in an ascii codeframe before converting it into html

- packages/transformers/react-refresh-wrap/src/ReactRefreshWrapTransformer.js
and ensure it uses `/` on Windows
> Fix require path in react-refresh transformer

- packages/utils/ts-utils/index.js
- packages/utils/ts-utils/package.json
Fixes a broken package.json. This can never have worked 😉
Try using parcel v2.0.0-alpha.3.2 with `@parcel/transformer-typescript-tsc`.
> Fix `main` field in ts-utils' package.json

- packages/core/diagnostic/src/diagnostic.js
- packages/core/logger/src/Logger.js
- packages/core/utils/package.json
- packages/core/utils/src/prettyDiagnostic.js
- packages/core/workers/test/workerfarm.js
- Skip markdown formatting for console logged values.
- Use chalk for filepath formatting not markdown to prevent issues
> [T-246] Markdown fixes for diagnostics

- packages/core/core/src/ParcelConfig.schema.js
- packages/core/utils/src/schema.js
Follow-up for #3880 was a bit too quick to merge it...
Fixes consistency in JSON validator.
cc @mischnic
> change validate -> _validate

- .github/workflows/stale.yml
Remove stale label and comment if someone comments
> Remove stale label and comment if someone comments

- packages/dev/eslint-config/index.js
- packages/dev/eslint-config/package.json
- yarn.lock
Makes the lint fail  when `describe.only` or `it.only` are used
> Lint mocha `(it|describe).only`

- azure-pipelines-template.yml
- azure-pipelines.yml
Stop using nightly builds of Rust, fix windows rust install and update all environments
> Use the stable version of rust

- packages/core/parcel/README.md
- Clarify that the common targets don't bundle dependencies
- Document the target options
> Update targets 'docs'

- flow-libs/serialize-to-js.js.flow
- packages/core/utils/package.json
- packages/core/utils/src/serializeObject.js
- yarn.lock
I really hope this is the last time we are forced to do this.
Closes #4042
> Bump serialize-to-js

- .github/workflows/nightly-release.yml
- package.json
This NPM implements a GitHub workflow to release a nightly version of Parcel every day at midnight
TODO:
- Add `NPM_TOKEN` secret to the repo with read/write permission to the `@parcel` npm organisation (probably devon's account)
> Publish a nightly to NPM every day

- packages/core/core/src/ResolverRunner.js
- packages/core/integration-tests/test/html.js
- packages/core/integration-tests/test/integration/html-protocol-relative/index.css
- packages/core/integration-tests/test/integration/html-protocol-relative/index.html
- packages/transformers/css/src/CSSTransformer.js
Closes https://github.com/parcel-bundler/parcel/issues/4005, Closes https://github.com/parcel-bundler/parcel/issues/4015
> Support protocol-relative URLs for URL dependencies

- packages/shared/scope-hoisting/package.json
I'm getting this linting error locally. Not totally sure how it seems to be getting past CI builds yet.
> List dependency in package.json

- packages/core/core/test/Graph.test.js
- packages/core/utils/test/objectHash.test.js
- packages/core/utils/test/prettifyTime.test.js
This PR adds a couple tests for utilities.
Based on #3798
> Add some unit tests

- packages/core/integration-tests/test/sass.js
- packages/transformers/sass/src/SassTransformer.js
Will take effect after https://github.com/parcel-bundler/parcel/issues/3708 is fixed
Closes https://github.com/parcel-bundler/parcel/issues/4127
> SASS add included files

- packages/reporters/dev-server/src/Server.js
This fixes a bug where sourcemaps were not properly served when publicUrls used a non-root path.
The main html bundle was sent whenever the request path didn't match the root url's path, but sourcemaps are always served from `/__parcel_source_root`, which made that branch unreachable in this case.
Test Plan:
* Run the kitchen sink example without supplying a custom publicUrl and verify example and sourcemaps work
* Run the kitchen sink example and supply a custom publicUrl `/foo` and verify example and sourcemaps work.
* Verify a request to `/bar/baz.js` 404s.
> Devserver: support sourcemaps for non-root publicUrls

- packages/core/package-manager/package.json
Adds the `@parcel/diagnostic` dependency to `@parcel/package-manager` to resolve undeclared dependency issue with Yarn.
I'm not exactly sure how these kinds of dependencies are managed in a monorepo of this scale, so if this is an unnecessary or superfluous change, just close this PR!
Installing and running nightly `parcel` with Yarn 2 yielded an error for me concerning this undeclared dependency.
I'm afraid I don't know what's expected for this kind of housekeeping change in terms of testing. Feel free to instruct me, or reject the PR.
> add parcel diagnostic dependency

- packages/core/parcel/README.md
> Fix link to sources in readme

- packages/core/fs/package.json
- packages/core/parcel-bundler/package.json
- yarn.lock
This PR shouldn't really have any impact, it might fix some issues installing watcher when using the lockfile.
Maybe resolves the issue in #4254
> Update watcher dependency

- packages/shared/scope-hoisting/package.json
- packages/shared/scope-hoisting/src/concat.js
- packages/transformers/js/package.json
- packages/transformers/js/src/JSTransformer.js
- packages/utils/babylon-walk/LICENSE.md
- packages/utils/babylon-walk/README.md
- packages/utils/babylon-walk/package.json
- packages/utils/babylon-walk/src/explode.js
- packages/utils/babylon-walk/src/index.js
- yarn.lock
The change was already contributed by Jasper but never released.
> Fork babylon-walk to use v7 types

- packages/utils/node-libs-browser/package.json
- yarn.lock
> Bump buffer polyfill for SharedArrayBuffer support

- packages/core/source-map/src/SourceMap.js
- packages/packagers/js/src/JSPackager.js
This PR changes the interface of create empty map to not recount the amount of lines in a file. Should be slightly faster
> Minor performance tweak source-maps

- packages/core/workers/src/Worker.js
- packages/core/workers/src/WorkerFarm.js
↪️ Pull Request
This PR ensures that shared references are are not sent to child workers until they have finished initializing. This fixes an issue where reverse handles in a shared reference are deserialized before `childId` is set in `childInit`, leaving the handle broken (Close T-393). It also ensures that all existing shared references at the time a worker is started are instantiated before the worker emits that it is ready, so they exist for worker handles that use them.
> Instantiate shared references after child worker is initialized

- packages/core/core/src/AssetGraphBuilder.js
This fixes an issue where Parcel attempts to validate files that no longer exist.
> Fix validation of removed files

- packages/core/integration-tests/test/integration/.eslintrc.json
- packages/core/logger/src/Logger.js
- packages/dev/eslint-config-browser/index.js
- packages/dev/eslint-config/index.js
- packages/examples/.eslintrc.json
- packages/examples/html/src/async.js
- packages/examples/html/src/async2.js
- packages/examples/kitchen-sink/src/index.js
- packages/utils/babylon-walk/src/explode.js
> Reenable no-console eslint rule

- packages/reporters/cli/src/utils.js
Minor performance fix for cli-reporter to not refetch terminal size unnecessarily.
> Improve performance in cli-reporter

- flow-libs/terser.js.flow
- packages/core/core/src/PackagerRunner.js
- packages/core/types/index.js
- packages/optimizers/terser/src/TerserOptimizer.js
- packages/packagers/js/src/JSPackager.js
- packages/packagers/ts/src/TSPackager.js
Fixes #4390
Should not return a sourcemapReference when `sourcemaps` are disabled
> Fix issue with no-sourcemaps

- packages/core/integration-tests/test/fs.js
- packages/core/integration-tests/test/integration/fs-destructure/index.js
- packages/transformers/js/src/visitors/fs.js
There was a wrong assertion when I updated that file for flow, a variable declaration can indeed contain a rest element.
Reported by @padmaia
> Don't crash with rest element in require("fs")

- packages/transformers/babel/src/config.js
- packages/transformers/js/src/JSTransformer.js
Some quick fixes to some bugs I found in the wild.
> Random fixes

- packages/transformers/babel/src/babel7.js
- packages/utils/babel-plugin-transform-runtime/src/index.js
Followup from review of https://github.com/parcel-bundler/parcel/pull/4342
> Wrapper for Babel tranform runtime plugin followup

- packages/configs/default/index.json
Added when native esmodule were introduced in Node.
https://github.com/marijnh/w3c-keyname/blob/e9fe840569bd2e090a4686436b918aa30ac49d51/package.json#L5
> Add cjs type to JSTransformer config

- packages/core/core/package.json
- packages/core/core/src/Transformation.js
- packages/core/integration-tests/test/sourcemaps.js
- packages/optimizers/cssnano/package.json
- packages/optimizers/terser/package.json
- packages/packagers/css/package.json
- packages/packagers/js/package.json
- packages/shared/babel-ast-utils/package.json
- packages/shared/scope-hoisting/package.json
- packages/transformers/coffeescript/package.json
- packages/transformers/css/package.json
- packages/transformers/less/package.json
- packages/transformers/less/src/LessTransformer.js
- packages/transformers/sass/package.json
- packages/transformers/sass/src/SassTransformer.js
- packages/transformers/typescript-types/package.json
This PR implements sourcemaps for LESS and SASS, it also fixes some bugs with sourcemaps I discover along the way.
> LESS and SASS Sourcemaps and a couple bugfixes

- packages/examples/kitchen-sink/package.json
- packages/shared/babel-ast-utils/src/index.js
This PR aims to fix the various issues with JS Sourcemaps.
I've already found the cause of the bug @wbinnssmith originally reported but while figuring out why that one occured I discovered a couple more bugs that I'll be fixing in follow-up PRs.
> Babel sourcemap bugfix

- packages/core/integration-tests/test/integration/scope-hoisting/commonjs/conditional-import-reference/a.js
- packages/core/integration-tests/test/integration/scope-hoisting/commonjs/conditional-import-reference/index.js
- packages/core/integration-tests/test/integration/scope-hoisting/es6/conditional-import-reference/a.js
- packages/core/integration-tests/test/integration/scope-hoisting/es6/conditional-import-reference/index.js
- packages/core/integration-tests/test/scope-hoisting.js
- packages/shared/scope-hoisting/src/link.js
Fixes #4299 
Close T-374
Uses test case & proposed solution in #4299 
yarn test
> allow conditionally referencing an imported symbol and unconditionally referencing it

- packages/core/integration-tests/test/integration/scope-hoisting/es6/used-assignmentexpression/a.js
- packages/core/integration-tests/test/scope-hoisting.js
Just to ensure that it continues to work...
Closes #4361
> Add test for when an AssignmentExpresission's value is used

- .flowconfig
- package.json
- yarn.lock
> Upgrade to flow 0.124.0

- packages/core/core/src/AssetGraph.js
- packages/core/core/src/BundleGraph.js
- packages/core/core/src/Dependency.js
- packages/core/core/src/dumpGraphToGraphViz.js
- packages/core/core/src/public/BundleGraph.js
- packages/core/core/src/public/Dependency.js
- packages/core/core/src/types.js
- packages/core/types/index.js
- packages/shared/scope-hoisting/src/link.js
Makes more sense conceptionally and fixes a problem for Will (though a test/reproduction would be nice)
> Reuse isDeferred from the bundle graph node, remove from dependency value

- packages/core/parcel/src/cli.js
- packages/core/utils/package.json
- packages/core/utils/src/index.js
- packages/core/utils/src/openInBrowser.js
- packages/examples/kitchen-sink/package.json
- yarn.lock
Implements the `--open` flag to automatically open the app in the browser. Based on port and hostname provided in the serve options.
Based on #3825
Run `yarn serve` in the kitchen-sink example
> Implement `--open` flag in cli

- packages/core/core/src/Transformation.js
- packages/core/integration-tests/test/html.js
- packages/core/integration-tests/test/pug.js
- packages/core/parcel/README.md
- packages/core/types/index.js
- packages/transformers/posthtml/src/PostHTMLTransformer.js
This PR updates the latest transformer to the new config loading spec.
Close T-345
> T-345 use loadconfig for posthtml

- packages/core/fs/package.json
- yarn.lock
This PR fixes the watcher version to the latest alpha, this ensures we can do breaking changes in the watcher without having to worry about any old versions breaking.
This matches what we do for source-map and all other parcel packages.
This also ensures everyone receives the bugfix Devon did yesterday.
> Update watcher and use fixed version

- packages/core/parcel/README.md
Indent issues
Indent issues on readme
> README.md Indent issues

- packages/core/package-manager/test/NodePackageManager.test.js
- packages/core/test-utils/src/utils.js
This PR aims to improve testing stability on windows and CI.
Fixed everything I could reproduce on a slow windows laptop
> Improve testing stability on windows

- packages/core/integration-tests/test/html.js
- packages/core/integration-tests/test/integration/data-url/index.html
- packages/packagers/html/src/HTMLPackager.js
Closes #4869
```html
<!DOCTYPE html>
```
> HTML: data-url inline bundles

- packages/core/parcel/package.json
The latest release is missing a dependency, so tests are failing:
https://github.com/yarnpkg/berry/runs/947729059?check_suite_focus=true
> Adds the missing events dep

- packages/transformers/image/package.json
- packages/transformers/image/src/ImageTransformer.js
This PR adds some improvements to the image transformer, to make it only require sharp and process using sharp when it really needs to, this means only when query params are defined.
> Image Transformer improvements

- packages/core/core/src/requests/PathRequest.js
- packages/core/types/index.js
- packages/resolvers/default/src/DefaultResolver.js
- packages/utils/node-resolver-core/src/NodeResolver.js
- packages/utils/node-resolver-core/test/resolver.js
Resolver should fail on throw.
Related to https://github.com/parcel-bundler/parcel/discussions/4992
> Make resolver fail on throw

- packages/transformers/js/src/visitors/process.js
> Mark AST dirty after replacing `process.browser`

- packages/core/parcel/package.json
- yarn.lock
> Remove unused react dependency of `parcel` package

- packages/core/diagnostic/src/diagnostic.js
- packages/core/logger/src/Logger.js
@DeMoorJasper I've copied the text from your docs page. Not sure about `skipFormatting` though...
Preview:
https://website-git-api-logging.devongovett.vercel.app/plugin-system/logging/
https://github.com/parcel-bundler/website/pull/649
> JSDoc: Logging

- packages/core/integration-tests/test/server.js
- packages/core/utils/src/http-server.js
This PR reverts our HTTP/2 devserver back to https.
Closes #4998
> Revert http/2 devserver

- .flowconfig
- package.json
- packages/core/core/src/dumpGraphToGraphViz.js
- packages/core/integration-tests/test/hmr.js
- packages/reporters/dev-server/src/HMRServer.js
- packages/reporters/dev-server/src/ServerReporter.js
- packages/utils/node-resolver-core/src/NodeResolver.js
- yarn.lock
> Flow 0.133

- packages/core/utils/src/path.js
- packages/core/utils/src/sourcemap.js
- packages/core/utils/test/input/sourcemap/referenced-min.js
- packages/core/utils/test/sourcemap.test.js
This PR implements the removal of `file://` and support for absolute paths in sourcemap comments.
This does seem to be a very niche edge case but apprarently it happens so this PR implements it.
Fixes #4316
> support absolute paths and file:// extension

- packages/core/integration-tests/test/integration/scope-hoisting/es6/export-default-global/a.js
- packages/core/integration-tests/test/integration/scope-hoisting/es6/export-default-global/b.js
- packages/core/integration-tests/test/scope-hoisting.js
- packages/shared/scope-hoisting/src/hoist.js
Closes #4348
```js
export default Number;
```
> Fix crash when default exporting a global variable

- packages/transformers/pug/src/PugTransformer.js
> pug config debug typo

- .flowconfig
- package.json
- yarn.lock
> Upgrade to flow 0.135.0

- packages/configs/default/index.json
- packages/configs/default/package.json
- packages/core/integration-tests/test/glsl.js
- packages/core/integration-tests/test/integration/glsl/local.frag
- packages/core/integration-tests/test/integration/glsl/local.vert
- packages/core/parcel/README.md
- packages/transformers/glsl/package.json
- packages/transformers/glsl/src/GLSLTransformer.js
- yarn.lock
Closes #3352
```JS
import vertex_shader from './vertex_shader.vert';
import fragment_shader from './fragment_shader.frag';
```
> GLSL Transformer

- packages/core/workers/src/child.js
> Fix memory leak

- packages/shared/scope-hoisting/src/concat.js
> Use project-relative path in the "ASSET:" comments

- flow-typed/npm/tempy_v0.x.x.js
- packages/core/core/test/TargetRequest.test.js
- packages/core/core/test/test-utils.js
Adds flow types for `tempy` package.
Add `// @flow strict-local` to each file that imports the `tempy` package and ensure that there are no flow type errors.
@padmaia @wbinnssmith @AGawrys
> Flow types for 'tempy' package

- .flowconfig
- flow-libs/browserslist.js.flow
- packages/core/core/src/public/Asset.js
- packages/core/core/src/public/Bundle.js
- packages/core/core/src/public/Config.js
- packages/core/core/src/public/Environment.js
- packages/transformers/babel/src/getBabelTargets.js
Adds a flow type lib def for `browserslist`.
Run `yarn flow` to ensure that there are no flow errors.
@padmaia @wbinnssmith
> Add flow types for browserslist

- packages/core/core/src/Environment.js
- packages/core/integration-tests/test/integration/js-multi-target-scope-hoist/index.js
- packages/core/integration-tests/test/integration/js-multi-target-scope-hoist/package.json
- packages/core/integration-tests/test/javascript.js
> Include scopeHoist in environment hash

- packages/core/integration-tests/test/integration/scope-hoisting/es6/side-effects-re-exports-import-different/a.js
- packages/core/integration-tests/test/integration/scope-hoisting/es6/side-effects-re-exports-import-different/node_modules/bar/foo.js
- packages/core/integration-tests/test/integration/scope-hoisting/es6/side-effects-re-exports-import-different/node_modules/bar/index.js
- packages/core/integration-tests/test/integration/scope-hoisting/es6/side-effects-re-exports-import-different/node_modules/bar/package.json
- packages/core/integration-tests/test/scope-hoisting.js
https://github.com/parcel-bundler/parcel/issues/5375
Was apparently fixed by the symbol propagation PR, but let's add this to be sure...
> Add regression test for #5375

- flow-libs/fastest-levenshtein.js.flow
- packages/core/utils/src/schema.js
Adds flow typings for `fastest-levenshtein` package. I used 
https://github.com/ka-weihe/fastest-levenshtein/blob/59e9f163ab4514b77d9cc4304c5fc6eaf5bec5e2/mod.ts#L114-L127
for reference
Ensure that there are no flow errors.
@wbinnssmith
> Add flow types for fastest-levenshtein

- packages/core/core/package.json
- packages/core/utils/package.json
- packages/optimizers/cssnano/package.json
- packages/optimizers/terser/package.json
- packages/packagers/css/package.json
- packages/packagers/js/package.json
- packages/reporters/sourcemap-visualiser/src/SourceMapVisualiser.js
- packages/shared/babel-ast-utils/package.json
- packages/shared/scope-hoisting/package.json
- packages/transformers/coffeescript/package.json
- packages/transformers/css/package.json
- packages/transformers/less/package.json
- packages/transformers/sass/package.json
- packages/transformers/typescript-types/package.json
- packages/transformers/vue/package.json
- yarn.lock
When reading sourcemaps with inlined content the sourcemap visualiser ignored them and just read the files from the filesystem, sometimes this will be impossible, so this PR fixes that.
Besides this will also help w/ performance.
Code extracted from #5427 as that PR will probably take a while before it's in a mergeable state.
> Fix sourcemap visualiser inlined content bug

- .flowconfig
- package.json
- yarn.lock
This upgrades flow to 0.139.0. No code changes were needed.
> Upgrade flow to 0.139.0

- .flowconfig
- package.json
- packages/core/core/src/types.js
- packages/core/core/test/Graph.test.js
- yarn.lock
Made the `type` property required on all `Node`s.
> Upgrade Flow to 0.140.0

- packages/core/integration-tests/test/integration/js-export-import-same/index.js
- packages/core/integration-tests/test/integration/js-export-import-same/other.js
- packages/core/integration-tests/test/javascript.js
- packages/shared/scope-hoisting/package.json
- packages/transformers/js/package.json
- packages/transformers/react-refresh-wrap/package.json
- packages/utils/babylon-walk/package.json
- yarn.lock
Also update our lockfile entry
Closes #5500
> Add test for simultaneous import and reexports of the same identifier

- packages/core/integration-tests/test/integration/react-refresh/App.js
- packages/core/integration-tests/test/integration/react-refresh/index.js
- packages/transformers/react-refresh-wrap/src/helpers/helpers.js
> Fix react refresh for getters on the namespace

- packages/core/parcel/src/cli.js
This PR is an attempt at improving the error handling for the cli, now it should catch any errors that occur in the run() function without relying on `unhandledRejection` which is probably a bad practise.
Related to #5516
> Improve cli error handling

- .github/workflows/nightly-release.yml
Not sure if this syntax is correct... YAML is a mystery.
> Support manually dispatching nightly releases

- .flowconfig
- package.json
- yarn.lock
> Upgrade to Flow 0.141.0

- .flowconfig
- package.json
- packages/core/core/src/Parcel.js
- yarn.lock
Required moving a `$FlowFixMe`, which has now been narrowed.
> Upgrade Flow to 0.142.0

- packages/core/integration-tests/test/integration/scope-hoisting/es6/async-internalize-unused/a.js
- packages/core/integration-tests/test/integration/scope-hoisting/es6/async-internalize-unused/b.js
- packages/core/integration-tests/test/integration/scope-hoisting/es6/async-internalize-unused/c.js
- packages/core/integration-tests/test/scope-hoisting.js
- packages/shared/scope-hoisting/src/link.js
alternative title: *Don't use FlowFixMe*
Closes https://github.com/parcel-bundler/parcel/issues/5624
> Fix unused internalized async imports

- package.json
- packages/core/register/package.json
- scripts/unlink-all.js
Use `rimraf` instead of `rm -rf`
> Make clean scripts cross-platform

- packages/core/integration-tests/test/html.js
- packages/core/integration-tests/test/integration/html-inline-importmap/index.html
- packages/transformers/html/src/inline.js
> Skip inline scripts with unknown type

- packages/core/fs/src/NodeFS.js
- packages/core/package-manager/src/NodeResolver.js
- packages/core/package-manager/src/NodeResolverBase.js
- packages/core/package-manager/src/NodeResolverSync.js
- packages/utils/node-resolver-core/src/NodeResolver.js
> Call PnP in package manager and don't use Rust file searching with PnP

- packages/shared/babel-ast-utils/src/generator.js
- packages/shared/babel-ast-utils/test/fixtures/function.js
Closes https://github.com/parcel-bundler/parcel/issues/5645
> Fix double comments and too much indentation

- packages/core/integration-tests/test/babel.js
- packages/core/integration-tests/test/integration/babel-optional-chaining/index.js
- packages/shared/babel-ast-utils/src/generator.js
Same as https://github.com/parcel-bundler/parcel/pull/5632, but OptionalCallExpression
@wbinnssmith
> Fix optional calls astring generation

- packages/core/integration-tests/test/html.js
- packages/transformers/html/src/inline.js
This was never actually asserted...
Closes #5475
> Actually replace inline style attributes with the transform result

- packages/shared/babel-ast-utils/package.json
- packages/shared/babel-ast-utils/src/generator.js
- packages/shared/babel-ast-utils/test/fixtures/async.js
- packages/shared/babel-ast-utils/test/fixtures/await.js
- yarn.lock
> Bump astring to fix missing parenthesis

- packages/core/core/src/TargetDescriptor.schema.js
Closes https://github.com/parcel-bundler/parcel/issues/5792
> Add service-worker as a target descriptor context

- packages/core/core/package.json
- packages/core/utils/package.json
- packages/optimizers/cssnano/package.json
- packages/optimizers/esbuild/package.json
- packages/optimizers/terser/package.json
- packages/packagers/css/package.json
- packages/packagers/js/package.json
- packages/shared/babel-ast-utils/package.json
- packages/shared/scope-hoisting/package.json
- packages/transformers/coffeescript/package.json
- packages/transformers/css/package.json
- packages/transformers/less/package.json
- packages/transformers/sass/package.json
- packages/transformers/typescript-types/package.json
- packages/transformers/vue/package.json
- yarn.lock
Update source-map library, to include some bugfixes in findClosestMapping
> update sourcemap linbrary

- packages/core/parcel/README.md
The pinned topic on Spectrum states that it has been moved to GitHub Discussions, so it shouldn't be linked in the README.
> Remove spectrum from README

- packages/core/fs/package.json
https://github.com/parcel-bundler/watcher/pull/48
> Bump the watcher to fix renames on macOS

- packages/transformers/image/package.json
- yarn.lock
1. Prebuilds!
2. More formats are supported, I couldn't see any breaking changes.
> Bump sharp version

- packages/core/package-manager/src/Npm.js
- packages/core/package-manager/src/Yarn.js
- packages/core/package-manager/src/installPackage.js
This seems to solve https://github.com/parcel-bundler/parcel/issues/5829.
> Try to fix npm autoinstall

- azure-pipelines.yml
- packages/core/parcel-bundler/package.json
- yarn.lock
This PR updates node-forge and the azure pipeline for parcel v1
> Node forge update
